### ISSUE TITLE
scaling concerto horizontally  

### ISSUE THREAD

**Issue by hadyrashwan** [campsych/concerto-platform#101]
I noticed that  everything in concerto is stored in the db as once I connect a clean concerto build to a database with some tests already made it just detects them.

but is it sticky-session or not ?? if I'm going to put a load balancer  in front of concerto

also any recommendation for :
scheduled backup 
deploying new tests to the production(devOps)

**Comment by przemyslawlis** [comment]
Yes, sticky-session.

Scheduled backup:
At the minimum backup your database.

Deployment:
You could keep your tests export files in your source control, checkout on deployment and import it with:
**php app/console concerto:content:import [path_to_dir_with_export_files] --convert**

Closing this for tracking purposes. Feel free to comment if you have more questions.
