### ISSUE TITLE
Index.php is not loading, where to see error logs

### ISSUE THREAD

**Issue by buddhapuneeth** [campsych/concerto-platform#105]
Apache is configured in right way and it is working fine. But index.php is not loading after we upgraded OS from 14 to 16. Where can I see error logs? Apache error logs are not giving enough information even at debug level.

**Comment by buddhapuneeth** [comment]
I progressed a bit, error is coming some where from Ini.php or User.php model. Unable to find the exact code which is causing error. No error logs are available. Let me know where can see error logs.

**Comment by buddhapuneeth** [comment]
I'm able to find the errors:
PHP Deprecated:  mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in /var/www/concerto/Ini.php on line 231
[Mon Mar 20 16:08:42.583171 2017] [:error] [pid 20127] [client 129.219.77.134:49685] PHP Stack trace:
[Mon Mar 20 16:08:42.583181 2017] [:error] [pid 20127] [client 129.219.77.134:49685] PHP   1. {main}() /var/www/concerto/index.php:0
[Mon Mar 20 16:08:42.583210 2017] [:error] [pid 20127] [client 129.219.77.134:49685] PHP   2. Ini->__construct() /var/www/concerto/index.php:23
[Mon Mar 20 16:08:42.583220 2017] [:error] [pid 20127] [client 129.219.77.134:49685] PHP   3. Ini->initialize_db_connection() /var/www/concerto/Ini.php:97
[Mon Mar 20 16:08:42.583228 2017] [:error] [pid 20127] [client 129.219.77.134:49685] PHP   4. mysql_connect() /var/www/concerto/Ini.php:231
[Mon Mar 20 16:08:42.584103 2017] [:error] [pid 20127] [client 129.219.77.134:49685] PHP Fatal error:  Class 'DOMDocument' not found in /var/www/concerto/cms/model/Language.php on line 45
[Mon Mar 20 16:08:42.584143 2017] [:error] [pid 20127] [client 129.219.77.134:49685] PHP Stack trace:
[Mon Mar 20 16:08:42.584154 2017] [:error] [pid 20127] [client 129.219.77.134:49685] PHP   1. {main}() /var/www/concerto/index.php:0
[Mon Mar 20 16:08:42.584163 2017] [:error] [pid 20127] [client 129.219.77.134:49685] PHP   2. Ini->__construct() /var/www/concerto/index.php:23
[Mon Mar 20 16:08:42.584172 2017] [:error] [pid 20127] [client 129.219.77.134:49685] PHP   3. Language::load_dictionary() /var/www/concerto/Ini.php:109

**Comment by przemyslawlis** [comment]
This is stack trace from Concerto v4 which is not supported anymore. Please move to Concerto v5 to have the latest and supported version.
