### ISSUE TITLE
Session resuming overrides internal session ID

### ISSUE THREAD

**Issue by chvancooten** [campsych/concerto-platform#106]
When enabling the session resume option in the "start_session" node (with user registration enabled), the user's entry in the session table is overwritten when a user actually resumes the session. This is not a logical feature since it breaks traceability in the data (user IDs for old sessions cannot be retrieved from the database entries). This can easily be fixed by having the resumeSession function in source_start_session create a new entry in the session db rather than overwrite the existing user's entry.

source_start_session (line 167):
``concerto.table.query("UPDATE `{{table}}` SET `{{internal_id_column}}`='{{internal_id}}', `{{last_activity_time_column}}`=NOW() WHERE `id`={{id}}", list())``

Altered query to add new entry to session db rather than update existing entry:
``concerto.table.query("INSERT INTO `{{table}}` SET `{{internal_id_column}}` = '{{internal_id}}', `test_id` = {{test_id}}, `user_id` = '{{user_id}}', `last_activity_time`= NOW()", list())``

**Comment by chvancooten** [comment]
Hi, thanks for your answer!

My use case is as follows:

> User 1 registers an account and answers some question in my system. New user (say user1) and internal session (session1) entries are created, linking the user to the session. User 1 leaves the system temporarily.
> 
> Meanwhile, user 2 also registers and answers some questions, same thing (user2, session2).
> 
> User 1 comes back and resumes their session (in my system, this works through the "resume session" option in the "start_session" node, so users have to sign in to resume their session.
> 
> At this point, a new session (session3) is created and linked to user1, overriding the link to session1.
> 
> Now, if I want to link the answers from my test to a specific user, this is only in part possible, since the linear test entries are linked to the internal session IDs and I cannot find in my data who session1 belongs to (since user1 belongs to session3 in this case). 

I am aware that it is possible to make the test nodes refer to a user ID rather than an internal session ID, but I only found this out later. Wouldn't it be more safe to create new session entries to combat this traceability issue for future users?

Thanks again for looking at this issue!

**Comment by przemyslawlis** [comment]
Thanks for your detailed explanation. I think I understand the problem now.

There are two kinds of sessions: 
* internal (created by Concerto Platform)
* ... and higher level one (created by the test in **start_session** node).

You shouldn't care about the internal one when using **start_session** node, as you have your own higher level session that can be used across multiple internal sessions lifetimes. Internal session is just a fall-back solution for simple tests without **start_session** node. 

Each test node (like **CAT**, **linear_test**, **questionnaire**, etc) requires to have some kind of session reference for their answers records. You should use your **session** object created in **start_session** node as a input parameter. See below:
![session](https://cloud.githubusercontent.com/assets/6590627/24455750/11312032-1491-11e7-8624-86a27be4d989.png)

This way the session id will be used from the session created by **start_session** node, and the id will be the same across all session resumes.

**Comment by chvancooten** [comment]
Thank you, that makes complete sense!

The only feedback I would have in this case is to automatically link the 'session' parameters if a 'start_session' node is present. That would (at least in my case) prevent a lot of confusion.

Thanks again for your help!
