### ISSUE TITLE
use R to create variable in Concerto 5

### ISSUE THREAD

**Issue by reductionist** [campsych/concerto-platform#107]
Hi all, apologies if this is not the right forum for this type of question, but I was wondering how I can use R to create a new variable from the "theta" (or "score$theta"?) output of a CAT node.  For example, once the CAT is complete, it outputs theta.  I want to use that to create a new variable like so:

pbelow <- pnorm(theta)

I then want to use "pbelow" in the feedback node.  I'm attaching my test diagram with my attempt to do the above.  All the typical steps work fine: test start -> create_template_definition -> CAT -> if_statement(s) -> feedback.  I figured I could use an "R_code" node to define a variable and then send that output ("result"?) to the feedback nodes, but it's not working.  Any help would be greatly appreciated.

Thanks!

Tyler

![concerto_cat_w_rcode](https://cloud.githubusercontent.com/assets/26654958/24300720/bbeaeda8-1083-11e7-92a1-d9062f2b91c6.png)

**Comment by davidstillwell** [comment]
Hi Tyler,

Thanks for this clear statement of your issue. One thing to fix and one to watch out for:

(1) You need the execution flow to go through the R_code node. i.e. connect "out" from CAT to "in" to R_code, and then "out" from R_code to "in" to your top if_statement node. This ensures that this code gets executed.

(2) Watch out that you refer to score$theta as arg1$theta within the R_code node

**Comment by reductionist** [comment]
Hi David, thanks so much for the quick response.  Your suggestion 1 makes perfect sense - done.  Suggestion 2 also makes sense to me, but I still can't get it to work.

I'm attaching the new diagram.  The R_code node contains this:

pbelow <- round(pnorm(arg1$theta),2)*100

The top if_statement node contains this:

ifdata$theta < 0.4

And the top feedback node contains this:

Congratulations, you have completed the test!  Your final score is {{theta}}, which is within the normal range of schizotypy in the population.  Only {{pbelow}} percent of people in the population score below {{theta}}.

The strange thing is that, now, even "{{theta}}" doesn't work in the feedback node, whereas it did previously.

Also, in taking the test for troubleshooting, I'm sure to make the first if_statement true, so haven't added any more connections to the other if statements yet.

Thanks again!

Tyler


![concerto_cat_w_rcode2](https://cloud.githubusercontent.com/assets/26654958/24304595/49f596a0-1090-11e7-8293-e854d6d9f1a5.png)

**Comment by davidstillwell** [comment]
Hi Tyler, I think the problem is that you're passing in two variables (result$whatever from the R code and score$whatever from the CAT node). You need to merge the two lists together so that both variables become a single input. To do that, add a new "merge_lists" node (https://github.com/campsych/concerto-platform/wiki/Merge-Lists-node ), connect both as inputs, and then connect the output to the Feedback node where you need to use both.

**Comment by reductionist** [comment]
Hi David, thank you - makes sense.  I now have the outputs from the R_code and CAT nodes connecting to a merge_lists node, and the output from the merge_lists node going to the feedback nodes.  It now recognizes {{theta}} again and includes that in the feedback now, but I can't figure out how to refer to the input ultimately coming from the R_code node.  The R code is this:

pbelow <- round(pnorm(arg1$theta),2)*100

So in the feedback node, I've tried referring to:

{{pbelow}}
{{merged_list$pbelow}}
{{result$pbelow}}
{{list1$pbelow}}
{{list1$result$pbelow}}
{{merged_list$list1$result$pbelow}}
{{result}}
{{list1$result}}
{{merged_list$result}}
{{inserts$pbelow}}
{{inserts$result$pbelow}}
{{inserts$result}}

Is it possible that it's not interpreting the R code the way I think it should?  For example, does it know that I am trying to create the object "pbelow", or would it be better for me to change the R code to simply:

round(pnorm(arg1$theta),2)*100  ?

Then, the result of that would be the "result" coming from the R_code node?  Or is the way I'm currently doing it correct?

Thanks again!

Tyler


![concerto_cat_w_rcode3](https://cloud.githubusercontent.com/assets/26654958/24372585/79183b68-12fc-11e7-8ba7-3e146dee18fd.png)

**Comment by davidstillwell** [comment]
pbelow needs to be a list itself. Add this line of code to the bottom of your R_code node:

result$pbelow = pbelow

**Comment by reductionist** [comment]
Thanks!

Now I get this message:

"Error in result$pbelow = pbelow: object 'result' not found"

**Comment by davidstillwell** [comment]
Sorry, this is just an R error. It wants the list to be created first before you can put data into it. So you need it like this:

result = list()
result$pbelow = pbelow

**Comment by reductionist** [comment]
Hi David, yes that makes sense.  I've changed it, but "pbelow" is still not showing up in the feedback node.  I'm not sure what other info I can give to help resolve this, but I'm going to email you an export of the test itself.  Please let me know if I can send anything else that might help.

Best,
Tyler

**Comment by reductionist** [comment]
This has been resolved.  Thank you, David!

Best,
Tyler

**Comment by talvinder** [comment]
@reductionist can you share the final solution
