### ISSUE TITLE
Can we run concerto 4 and concerto 5 in parallel?

### ISSUE THREAD

**Issue by buddhapuneeth** [campsych/concerto-platform#108]
We have concerto 4 configured and running in apache httpd server, now we configured concerto 5 also on the same server. But we cannot able to access concerto 5, all the apache configurations seem to be correct. Do you have inputs to this?

**Comment by przemyslawlis** [comment]
Yes, Concerto v4 and v5 can be run in parallel on your web server like any other web apps.
Please provide some more details about the issue you are having so I can help you with the installation process.
First of all, please make sure, that you followed all steps from: https://github.com/campsych/concerto-platform/wiki/Linux-installation

**Comment by przemyslawlis** [comment]
Closing for tracking purposes. Feel free to leave a comment if you have more questions regarding this issue.
