### ISSUE TITLE
 Can't connect to MySQL server on '127.0.0.1'

### ISSUE THREAD

**Issue by TimCode1** [campsych/concerto-platform#111]
I'm trying to install this on a Centos (version 6.8) server. 

Setup all went well. The database exists and the command php app/console concerto:setup works fine. 

Tables are all created in the database through the set-up process. Apache, PHP and mysql are all happy, mysql -V returns mysql  Ver 14.14 Distrib 5.1.73, for redhat-linux-gnu (i386) using readline 5.1.

PHP is version 5.6.30

But on attempting to access from the browser I get this (password replaced) .. Any help would be appreciated.

PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2003] Can't connect to MySQL server on '127.0.0.1' (13)' in /var/www/vhosts/concerto/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43\nStack trace:\n#0 /var/www/vhosts/concerto/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(43): PDO->__construct('mysql:host=127....', 'root', '<correct password>', Array)\n#1 /var/www/vhosts/concerto/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php(45): Doctrine\\DBAL\\Driver\\PDOConnection->__construct('mysql:host=127....', 'root', '<correct password>', Array)\n#2 /var/www/vhosts/concerto/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\\DBAL\\Driver\\PDOMySql\\Driver->connect(Array, 'root', '<correct password>', Array)\n#3 /var/www/vhosts/concerto/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): Doctrine\\DBAL\\Connection->connect()\n#4 /var/www/vhosts/concerto/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\\DBAL\\Connection->getDatabasePlatformVersion()\n#5 /var/w in /var/www/vhosts/concerto/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 115

**Comment by przemyslawlis** [comment]
Can you please paste contents of app/config/parameters.yml file here (you can remove password lines)?
Can you log in to MySQL client manually using parameters from the file?

**Comment by TimCode1** [comment]
Hi,

Thanks for getting back to me. parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: concerto
    database_user: root
    database_password: <correct password>
    database_path: null
    database_unix_socket: null
    test_database_name: ThisIsYourTestDatabaseName
    test_database_user: ThisIsYourTestDatabaseUserName
    test_database_password: ThisIsYourTestDatabaseUserPassword
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en_GB
    secret: ThisTokenIsNotSoSecretChangeIt

I have tried a few other options, including 'localhost' instead of
'127.0.0.1'

I can log in manually and from MySQL workbench.

Tim

**Comment by przemyslawlis** [comment]
It might be a production environment cache that was made before you made changes to the config files. Please try to remove:
**app/cache/prod** and all of its contents and see if that helps.

**Comment by przemyslawlis** [comment]
Closing. Feel free to respond if you still have the problem and we'll reopen the report.
