### ISSUE TITLE
Installation windows 7 - 64bits

### ISSUE THREAD

**Issue by lvbeltranb** [campsych/concerto-platform#112]
Setup has detected that the file 'C:\Users\test\AppData\Local\Temp\VSD31EC.tmp\DotNetFX46\NDP46-KB3045560-Web.exe' has changed since it was initially published.

Installation failed.

**Comment by przemyslawlis** [comment]
Try to install .NET 4.6 manually. You can download it from: https://www.microsoft.com/en-us/download/details.aspx?id=48130. 
Please let me know if that helped.

**Comment by przemyslawlis** [comment]
Closing. Feel free to comment if that didn't help.
