### ISSUE TITLE
Can't run the setup

### ISSUE THREAD

**Issue by mgonper** [campsych/concerto-platform#113]
This is the error report:

INFORMACIÓN DE VERSIÓN DE LA PLATAFORMA
	Windows 			: 10.0.14393.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.6.1586.0 built by: NETFXREL2
	clr.dll 			: 4.6.1637.0 built by: NETFXREL3STAGE
	dfdll.dll 			: 4.6.1586.0 built by: NETFXREL2
	dfshim.dll 			: 10.0.14393.0 (rs1_release.160715-1616)

ORÍGENES
	Dirección URL de la implementación			: http://concertoplatform.com/installers/concertolauncher/x64/ConcertoLauncher.application
						Servidor		: nginx
						X-Powered-By	: PleskLin
	Dirección URL del proveedor de la implementación		: http://concertoplatform.com/installers/concertolauncher/x64/ConcertoLauncher.application
	Dirección URL de la aplicación			: http://concertoplatform.com/installers/concertolauncher/x64/Application%20Files/ConcertoLauncher_0_9_14_2/ConcertoLauncher.exe.manifest
						Servidor		: nginx
						X-Powered-By	: PleskLin

IDENTIDADES
	Identidad de la implementación		: ConcertoLauncher.application, Version=0.9.14.2, Culture=neutral, PublicKeyToken=0000000000000000, processorArchitecture=amd64
	Identidad de la aplicación		: ConcertoLauncher.exe, Version=0.9.14.2, Culture=neutral, PublicKeyToken=0000000000000000, processorArchitecture=amd64, type=win32

RESUMEN DE LA APLICACIÓN
	* Aplicación instalable.

RESUMEN DEL ERROR
	Abajo se muestra un resumen de los errores; los detalles de estos errores se incluyen en el registro.
	* La activación de http://concertoplatform.com/installers/concertolauncher/x64/ConcertoLauncher.application dio como resultado una excepción. Se detectaron los siguientes mensajes de error:
		+ Excepción durante la operación de almacenamiento.
		+ Acceso denegado. (Excepción de HRESULT: 0x80070005 (E_ACCESSDENIED))

RESUMEN DE ERRORES DE TRANSACCIÓN DEL ALMACÉN DE COMPONENTES
	* Transacción en [02/04/2017 18:37:08]
		- No se realizó correctamente el almacenamiento provisional de un archivo de componente (ConcertoLauncher.exe).
		- La implementación (http://concertoplatform.com/installers/concertolauncher/x64/ConcertoLauncher.application#ConcertoLauncher.application, Version=0.9.14.2, Culture=neutral, PublicKeyToken=0000000000000000, processorArchitecture=amd64) no se instaló correctamente.
		- No se pudo establecer uno o varios metadatos de la implementación correctamente.

ADVERTENCIAS
	* El manifiesto para esta aplicación no tiene signatura. Se ignorará la validación de signatura.
	* El manifiesto para esta aplicación no tiene signatura. Se ignorará la validación de signatura.

ESTADO DE PROGRESO DE LA OPERACIÓN
	* [02/04/2017 18:36:44] : Se ha iniciado la activación de http://concertoplatform.com/installers/concertolauncher/x64/ConcertoLauncher.application.
	* [02/04/2017 18:36:44] : El procesamiento del manifiesto de la implementación finalizó correctamente.
	* [02/04/2017 18:36:44] : Se ha iniciado la instalación de la aplicación.
	* [02/04/2017 18:36:44] : Ha finalizado correctamente el procesamiento del manifiesto de la aplicación.
	* [02/04/2017 18:37:07] : Se ha encontrado una versión del runtime compatible 4.0.30319.
	* [02/04/2017 18:37:07] : Ha finalizado la solicitud de confianza y detección de plataforma.
	* [02/04/2017 18:37:08] : Finalizó la descarga de las dependencias de la suscripción.
	* [02/04/2017 18:37:08] : Se ha iniciado la confirmación de la aplicación descargada.

DETALLES DEL ERROR
	Se detectaron los siguientes errores durante esta operación.
	* [02/04/2017 18:37:08] System.Deployment.Application.DeploymentException (ComponentStore)
		- Excepción durante la operación de almacenamiento.
		- Origen: System.Deployment
		- Seguimiento de la pila:
			en System.Deployment.Application.ComponentStore.SubmitStoreTransaction(StoreTransactionContext storeTxn, SubscriptionState subState)
			en System.Deployment.Application.ComponentStore.SubmitStoreTransactionCheckQuota(StoreTransactionContext storeTxn, SubscriptionState subState)
			en System.Deployment.Application.ComponentStore.CommitApplication(SubscriptionState subState, CommitApplicationParams commitParams)
			en System.Deployment.Application.SubscriptionStore.CommitApplication(SubscriptionState& subState, CommitApplicationParams commitParams)
			en System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			en System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			en System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Excepción interna ---
		System.UnauthorizedAccessException
		- Acceso denegado. (Excepción de HRESULT: 0x80070005 (E_ACCESSDENIED))
		- Origen: System.Deployment
		- Seguimiento de la pila:
			en System.Deployment.Internal.Isolation.IStore.Transact(IntPtr cOperation, StoreTransactionOperation[] rgOperations, UInt32[] rgDispositions, Int32[] rgResults)
			en System.Deployment.Internal.Isolation.Store.Transact(StoreTransactionOperation[] operations, UInt32[] rgDispositions, Int32[] rgResults)
			en System.Deployment.Application.ComponentStore.SubmitStoreTransaction(StoreTransactionContext storeTxn, SubscriptionState subState)

DETALLES DE TRANSACCIÓN DEL ALMACÉN DE COMPONENTES
	* Transacción en [02/04/2017 18:37:08]
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Estado: Installed
			- HRESULT: 0x0
			- Manifiesto: YXC6QTEG.PRH.application
		+ System.Deployment.Internal.Isolation.StoreOperationSetDeploymentMetadata
			- Estado: Set
			- HRESULT: 0x0
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Estado: Installed
			- HRESULT: 0x0
			- Manifiesto: ConcertoLauncher.exe.manifest
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Estado: Installed
			- HRESULT: 0x0
			- Archivo: Resources\favicon.ico
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Estado: Installed
			- HRESULT: 0x0
			- Archivo: ConcertoLauncher.exe.config
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Estado: Installed
			- HRESULT: 0x0
			- Manifiesto: ConcertoLauncher.exe.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Estado: Failed
			- HRESULT: 0x80070005
			- Archivo: ConcertoLauncher.exe
		+ System.Deployment.Internal.Isolation.StoreOperationInstallDeployment
			- Estado: Failed
			- HRESULT: 0x1
			- Id. de aplicación: http://concertoplatform.com/installers/concertolauncher/x64/ConcertoLauncher.application#ConcertoLauncher.application, Version=0.9.14.2, Culture=neutral, PublicKeyToken=0000000000000000, processorArchitecture=amd64
		+ System.Deployment.Internal.Isolation.StoreOperationSetDeploymentMetadata
			- Estado: Failed
			- HRESULT: 0x1
		+ System.Deployment.Internal.Isolation.StoreTransactionOperationType (27)
			- HRESULT: 0x1

**Comment by przemyslawlis** [comment]
Are you running the setup as a system administrator?
Can you please share some more details about when does exactly the error message appear?

**Comment by mgonper** [comment]
Thank yoy, I wasn't running it as an administrator
