### ISSUE TITLE
concerto-platform and GNU license 

### ISSUE THREAD

**Issue by hadyrashwan** [campsych/concerto-platform#114]
I made a small template for ipsative tests. https://github.com/hadyrashwan/concerto_ipsative_template
and I'm planning to create wizards and full modules in the near feature.

my question is what modification do I need to publish according to the gnu license.

**Comment by davidstillwell** [comment]
Amazing! Thanks for sharing!

It was a couple of years ago we worked out the licensing, so I honestly forgot how we did it. I'll ask one of the software engineers to get back to you.

**Comment by hadyrashwan** [comment]
any news :)

**Comment by bkielczewski** [comment]
@hadyrashwan GPL3 allows you to do any modification you wish, but you can't distribute it to others (like call it Concerto++) without publishing source code of your modifications. Keyword here is 'distribution'. So, for example you should be ok as long as you do it for yourself or it would be used internally. 

However, if it's something that can benefit others - please consider contributing it to upstream. Besides just making a better place and lots of good karma for being a contributor you wouldn't have to upgrade/maintain it later to keep it inline with any future changes. 

Hope that helps?
b.

**Comment by hadyrashwan** [comment]
yes, ofcourse, contributions is what made Github possible, to begin with. Thanks a lot
