### ISSUE TITLE
Test's stuck on "please wait" page on Concerto 5

### ISSUE THREAD

**Issue by AnandGanesh7** [campsych/concerto-platform#115]
I have installed concerto on Ubuntu 16.04. I have a couple of tests that I created on Concerto 5 before. But when I click run, I only see the intermediate "please wait" page shown in the screen shots below.

There is nothing wrong with the tests as they worked completely fine on another system with Concerto 5. Any idea as to what the problem could be?
![screenshot from 2017-04-05 15-54-02](https://cloud.githubusercontent.com/assets/10592892/24730395/486e9f3e-1a18-11e7-91fc-d773f2a56a6f.png)

I am able to login and change my admin/password credentials and the UI renders fine. However, I had troubles earlier with the login URL. As you can see from the screenshot of the login page. "localhost/admin" does not work even now. Instead when I type in just "localhost", it redirects to "localhost/app.php" and then it shows the page where I can run tests from. Therefore I had to type in "localhost/app.php/admin" to land at the login page and then continue on. Does this have anything to do with the tests not running? From the Linux wiki page and from my own experience in installing Concerto 5 before, I was able to land at the login page simply by typing "localhost/admin" and the same tests ran. Where am I going wrong? 
Below you can see the redirection work when I typed in "localhost/app.php/admin'
![screenshot from 2017-04-05 16-03-41](https://cloud.githubusercontent.com/assets/10592892/24730618/77bdeef6-1a19-11e7-8048-0d163b2748d9.png)

But this still fails (even though this is the expected URL that needs to work)
![screenshot from 2017-04-05 16-06-00](https://cloud.githubusercontent.com/assets/10592892/24730669/cec76c86-1a19-11e7-8db6-266a4b0833cb.png)

All help is appreciated.

**Comment by AnandGanesh7** [comment]
So it turns out that my apache had "mod rewrite" disabled. This was the URL redirection errors. Additionally there is another issue. If you are using php7.0 then the corresponding xml package during installation should be php7.0-xml on Ubuntu and not just php-xml. This will remove the DOMDocument errors during installation. This did the trick and concerto works for me now. Hope this helps somebody.

**Comment by davidstillwell** [comment]
Thanks Anand for diagnosing the issue and sharing the answer. I'll ask Przemek to update the installation instructions.

**Comment by ibrahimabdulla** [comment]
hi @davidstillwell  im facing the same issue with concerto .please reply ASAP 
Thank you.

**Comment by davidstillwell** [comment]
@ibrahimabdulla - did you see the response already from AnandGanesh? He solved his own issue so you should see whether his solution works for you too.

**Comment by ibrahimabdulla** [comment]
i have tried both disabling mod rewrite and php7.0-xml !

**Comment by AnandGanesh7** [comment]
Hello Ibrahim, I'm sorry if I wrote it in a confusing way. I meant that it was disabled and that I needed to enable mod rewrite in Apache.

**Comment by ibrahimabdulla** [comment]
ooh sorry but i have enabled it and tried ... nothing changed ! my specs ubuntu 16.04 , php 7.1 etc

**Comment by AnandGanesh7** [comment]
Could you describe the problem further and order

**Comment by AnandGanesh7** [comment]
Could you please double check that mod rewrite is on and try restarting Apache using a reload and then a restart.

**Comment by ibrahimabdulla** [comment]
![screenshot from 2017-04-10 23-45-28](https://cloud.githubusercontent.com/assets/13494383/24876082/01e4a598-1e48-11e7-8a62-7dfdfd709da7.png)

and Error encountered. Execution halted.

**Comment by AnandGanesh7** [comment]
Error encountered, execution halted is a compilation/interpretation issue. The concerto engine seems to work as intended. Please have a look at the debug page to debug your errors. It could be anything from missing packages, to sql errors or just syntax.

**Comment by ibrahimabdulla** [comment]
![screenshot_2](https://cloud.githubusercontent.com/assets/13494383/24890169/e3b2e4ce-1e8b-11e7-8a97-321a3308e43e.png)

**Comment by ibrahimabdulla** [comment]
issue has been solved. Thanks for the help @AnandGanesh7 and @davidstillwell

**Comment by AnandGanesh7** [comment]
I'm curious to know how you solved it and what was the problem. It could help other people in the future, please put it up here if you've the time. Thank you

**Comment by Deleetdk** [comment]
Versions:

- Ubuntu 17.04
- Concerto v5.0.beta.2.186
- php 7.0.18-0ubuntu0.17.04.1
- Apache/2.4.25 (Ubuntu)

Installed by following [the linux admin guide](https://github.com/campsych/concerto-platform/wiki/Linux-installation).

I had this error. I solved it by:

```
sudo a2enmod rewrite
sudo systemctl restart apache2
```

I already had `php7.0-xml` installed.
