### ISSUE TITLE
Can't run test on Questionaire test 

### ISSUE THREAD

**Issue by baothuy1311** [campsych/concerto-platform#118]
Hi all, 
Do you have any problem with the annoucement: ''Error encountered. Execution halted.'' I check with F12, Network tag, but I can't find any problem. I have limited technical knowledge, please support me.  
![error with run test](https://cloud.githubusercontent.com/assets/27630697/25072119/bf998bca-22c7-11e7-8f1f-ed2a6738fb2d.jpg)
Thank you!

**Comment by przemyslawlis** [comment]
Hi,
It's a test logic error.
Run the test in debug mode. There is a debug button available when you are editing the test, see below:
![debug](https://cloud.githubusercontent.com/assets/6590627/25335190/41700428-28f2-11e7-8b24-36877e0ab1a8.png)

When running in debug mode you can see R output in your browser console. Alternatively you can check for test error logs when editing your test, see below:
![errors](https://cloud.githubusercontent.com/assets/6590627/25335313/cd5c8cae-28f2-11e7-9921-9612ae43349e.png)

You should be able to find error description using any of the method above.

**Comment by przemyslawlis** [comment]
No response. Closing.

**Comment by suleymandemir** [comment]
Hi 

I have a problem like this. Could anybody help me? 
![adsiz](https://user-images.githubusercontent.com/34800147/34460704-4cf450d8-ee27-11e7-8d3a-1a45f4909c15.png)

**Comment by Aidenloe** [comment]
Hi,

I think the number of columns in the data table do not match the number of variables you are trying to insert.

**Comment by suleymandemir** [comment]
I have 5 categories but I have 4 threshold parameters. So the first parameter is blank. (https://github.com/campsych/concerto-platform/wiki/polyCAT-Test-node) Isn't it true?
