### ISSUE TITLE
Error : CAT with Fill-in the blank - Item

### ISSUE THREAD

**Issue by jch4r1s** [campsych/concerto-platform#122]
Hi All,

I am trying to do CAT with Fill-In-The-Blank (open question) items. 
I am using "flow-chart" method.

In the CAT "Node" - under Item Bank Section - it says:
"CAT item bank definition.
Leave item response options list empty for open question."

I've tried using these versions, but failed:
-	Localhost (Windows version)
-	v5.0.beta.2.183 
-	v5.0.beta.2.171 

DR. David Stillwell of Cambridge informed me that it was running on old versions.
Can anyone help me with this?

Many thanks,
br,
Jeriel

**Comment by przemyslawlis** [comment]
Hi 
Can you please explain what are you seeing instead of open question?

**Comment by jch4r1s** [comment]
Hi @przemyslawlis 
Sorry for the late response from my side.

I am working to create ability test using CAT. Currently I have "paper & pencil" version of that test (classical test). The test is in open question format. 
Thus, i was wondering if i can do do the CAT using open question format.

Many thanks @przemyslawlis 
cheers

**Comment by Abuamany** [comment]
Refer to Jch4ris example : numeric sequence items

![screenshot from 2017-05-27 17-17-00](https://cloud.githubusercontent.com/assets/16170999/26520604/5954b16a-4300-11e7-9beb-2336cf0020ae.png)

**Comment by przemyslawlis** [comment]
@jch4r1s:
You can do that by clearing possible response options for a specific item that you want to be in open text format.

This is how your item 'response options' field should look like:
![opentext](https://cloud.githubusercontent.com/assets/6590627/26588891/de2cf7be-4556-11e7-80c0-92a2e1e59fad.png)

**Comment by Abuamany** [comment]
I was change response options in cat table with : {"response_type":"open_text","response_options":[]}

the error logs : 
Error: lexical error: invalid char in json text.
                                      {&quot;response_type&quot;:&quot
                     (right here) ------^

Any suggestions?

**Comment by Abuamany** [comment]
If I am using default cat itembank, and clik response options only one options (value,  labels), I think the default in multiple choice format, we can not found open text (options)
![screenshot from 2017-05-31 07-59-26](https://cloud.githubusercontent.com/assets/16170999/26611279/6a0caed4-45d7-11e7-8a49-f15882ba3d55.png)

**Comment by jch4r1s** [comment]
Hello @przemyslawlis,

Thanks for your reply. Sorry for the late reply.
I tried to do as advised, but still failed.
The error message: 

"Error in concerto.template.join(templateId = CAT_template, params = list(paragraph = paragraph, : object 'section_classes' not found"

Kindly advise.
many thanks

**Comment by jch4r1s** [comment]
@Abuamany 

Yes Mr. Heru, thanks for helping me out with the screenshot.
cheers.
jeriel
