### ISSUE TITLE
Database issues while upgrading concerto

### ISSUE THREAD

**Issue by chuenlok** [campsych/concerto-platform#123]
Hi,

I was trying to upgrade concerto from version `v5.0.beta.2.129` to `v5.0.beta.2.186`. The below error showed while executing `php app/console concerto:content:import --convert`.  I guess the upgrade did not take the old db schema into account. Is it safe to add a dummy column `rev` to ConcertoUser so that the upgrade might work?

Thank you very much.

```sql
An exception occurred while executing 'SELECT t0.username AS username_1, t0.salt AS salt_2, 
t0.password AS password_3, t0.email AS email_4, t0.accessibility AS accessibility_5, t0.groups AS 
groups_6, t0.archived AS archived_7, t0.protected AS protected_8, t0.starterContent AS 
starterContent_9, t0.rev AS rev_10, t0.id AS id_11, t0.updated AS updated_12, t0.created AS 
created_13, t0.tags AS tags_14, t0.owner_id AS owner_id_15, t0.updatedBy_id AS updatedBy_id_16 
FROM ConcertoUser t0 WHERE t0.username = ? LIMIT 1' with params ["admin"]: SQLSTATE[42S22]: 
Column not found: 1054 Unknown column 't0.rev' in 'field list'
```

**Comment by chuenlok** [comment]
I added the field so that the upgrade works. I found that the upgrade procedure missed the step to update db sturcture. A few tables miss `rev` and a table (sorry forgot the name) misses `css`, `js`. I think the upgrade process should take db structure into account. Thanks :)

**Comment by przemyslawlis** [comment]
Can you please explain how did you tried to update the platform?
Did you use update guide at: https://github.com/campsych/concerto-platform/wiki/Linux-Update ?
The guide already contains instructions that update database schema.

**Comment by chuenlok** [comment]
I did follow the Linux update guide. It was fine until the command
```
php app/console concerto:content:import --convert
```
I guess this command is to update the database schema but it seems it still missed some field?

**Comment by przemyslawlis** [comment]
I've just updated the guide as there was incorrect order of commands earlier on (switched places of points 6 & 7).

<pre>cd /var/www/vhosts/concerto/
php app/console concerto:setup</pre>
Needs to be run before:
<pre>php app/console concerto:content:import --convert</pre>

Thanks for pointing that out.
