### ISSUE TITLE
start session error

### ISSUE THREAD

**Issue by Abuamany** [campsych/concerto-platform#126]
pls advice, we have put create sessions node, and run the test... appear this error :
Error in .local(conn, statement, ...): could not run statement: Field 'finished' doesn't have a default value

**Comment by przemyslawlis** [comment]
If you're one MySQL server it's possible that you will have to disable strict SQL mode.
In latest dev version (which is not yet part of the master branch) this is done on the session level automatically.

**Comment by Abuamany** [comment]
I will try, thanks alots
