### ISSUE TITLE
Concerto for Windows Installer

### ISSUE THREAD

**Issue by GarryGelade** [campsych/concerto-platform#127]
I tried to install Concerto for Windows, but setup.exe failed. It refused to download the Microsoft Visual C++ redistributables because there is a later version installed.

There seems no way to continue with the installation.
Please can you advise.

Thanks very much
Dr Garry Gelade

**Comment by przemyslawlis** [comment]
I suggest you try other installation method than Windows Installer for now (e.g. https://github.com/campsych/concerto-platform/wiki/Linux-installation). Windows installer will be retired very soon and replaced with new install method.
