### ISSUE TITLE
Questionaire in Stages

### ISSUE THREAD

**Issue by chandangs16** [campsych/concerto-platform#129]
Is it possible to have a questionnaire where we have for example 3 stages, and each stage has 3 questions.?
1. Each of those questions has the buttons: "next question", "previous question" and "next stage".
2. within each stage, the user can move to next or previous questions of the same stage, but the user can't go to questions of the previous stage.
Is it possible to implement something like this is Concerto v5 through code?

**Comment by chandangs16** [comment]
@davidstillwell - could you help me with this? Thank you.

**Comment by chandangs16** [comment]
Is there a limit on the number of buttons to be used on each page?? @davidstillwell

**Comment by albamrt** [comment]
Hi! I am creating a CAT test and I would like to add a "previous question" button. As I've seen it's one of the things being asked here I was wondering if it had been finally accomplished.

**Comment by albamrt** [comment]
Sure, it's true, thank you! 
Also, my initial concern was if that "return" button could be used in a start_session node. So if, for example, one clicked the "register" button but wanted to go back to "login".

**Comment by przemyslawlis** [comment]
> Is it possible to have a questionnaire where we have for example 3 stages, and each stage has 3 questions.?

Each of those questions has the buttons: "next question", "previous question" and "next stage".
within each stage, the user can move to next or previous questions of the same stage, but the user can't go to questions of the previous stage.
Is it possible to implement something like this is Concerto v5 through code?

^ Of course it's possible. You'll need to edit current starter content source or create a new questionnaire test on your own.

> Is there a limit on the number of buttons to be used on each page??

^ No there is no limit.
