### ISSUE TITLE
Installation for ubuntu 14 - 64 bits

### ISSUE THREAD

**Issue by johnfelipe** [campsych/concerto-platform#13]
https://docs.google.com/document/d/1mxQzb0qV9F4sOAmki-cDbjzgX7uailJCkS4FdCnucYw/edit?usp=drive_web

Is not working for vers 4, tell me how fix that

**Comment by przemyslawlis** [comment]
This repository is dedicated to Concerto Platform v5. v4 is outdated now and we strongly recommend you use v5. You can check installation guide at: https://github.com/campsych/concerto-platform/wiki/Linux-installation . 
If you already have some content created on v4 you should have no problems transferring it to v5 (some minor tweaks might be required).
