### ISSUE TITLE
windows offline installer does not work

### ISSUE THREAD

**Issue by stochl** [campsych/concerto-platform#131]
Hi, I am trying to install Concerto on my local windows computer. The setup you provide does not work,  Windows just shows error saying that this app cannot run on Windows. 
I have Windows 10 64bit version, so according to your description it should work. Thank for any advice, thanks.
Jan

**Comment by GarryGelade** [comment]
I'm also having a problem.  In my case it won't install because there is a later version of Microsoft C++ redistributable already on my machine.

**Comment by oloabbott** [comment]
In my case  I have succeeded in downloading the launcher but it refused to install concerto. It showed the same error as that above  What else should I do?

**Comment by przemyslawlis** [comment]
I suggest you try other installation method than Windows Installer for now (e.g. https://github.com/campsych/concerto-platform/wiki/Linux-installation). Windows installer will be retired very soon and replaced with new install method.
