### ISSUE TITLE
Windows local installer problems

### ISSUE THREAD

**Issue by uqswalk5** [campsych/concerto-platform#132]
I have installed Concerto on a local Windows machine running Windows 7 64bit. The installation was successful (see attached)

However, when I run the software I receive this error message (see attached)

Please advise

Stephen Walker
University of Queensland, Australia
[Concerto issues.docx](https://github.com/campsych/concerto-platform/files/1084060/Concerto.issues.docx)

**Comment by przemyslawlis** [comment]
Duplicate of #144
