### ISSUE TITLE
CSV download issue

### ISSUE THREAD

**Issue by Bob36281** [campsych/concerto-platform#133]
We have a version of Concerto successfully running in an AWS container.  I would like to download the data currently present in the default_data_table.  When I select Download I am able to download the data successfully as a PDF.  When I try to do the same as a CSV file nothing happens.  The debugger gives the following error:

Could not locate http://ipaddress/bundles/concertotest/angularjs/bower_components/bootstrap/dist/css/less/mixins/vendor-prefixes.less specified in source map http://ipaddress/bundles/concertotest/angularjs/bower_components/bootstrap/dist/css/bootstrap.min.css.map

Any help gratefully received.

**Comment by davidstillwell** [comment]
Did you create the AWS container yourself? We already created a Concerto AMI for AWS so it should avoid you having to install everything yourself. See: https://github.com/campsych/concerto-platform/wiki/Concerto-Platform-AMI-launch-guide

**Comment by Bob36281** [comment]
Yes,  we used the Concerto AMI for AWS.

**Comment by przemyslawlis** [comment]
Do you see any javascript errors in browser console?
Is it possible for me to log in to your panel remotely to check it out?

**Comment by przemyslawlis** [comment]
No response - closing. Feel free to answer and reopen.
