### ISSUE TITLE
Creating a graph 

### ISSUE THREAD

**Issue by jin239fa** [campsych/concerto-platform#134]
Hi,

I am missing something when creating a chart for the end results. I can create the graph but there are no scores there.  I am unsure as to why, I have connected the CAT node to Create Graph then to info. The graph saves itself in the file but the data doesn't come out. It just shows an empty chart.

Many Thanks, 

Jin

**Comment by przemyslawlis** [comment]
Can you post a screenshot of your flowchart?

**Comment by jin239fa** [comment]
I managed to get the results. Thank you.
However, I have got some questions.

It is shown as ggplot. how can i change the graph as standard deviation?
Do i have to use R code node without create graph node?
I want to convert theta results to percentile 0 %to 100% . Is that possible?
I am looking forward to hearing from you.

Thank you

**Comment by jin239fa** [comment]
![image](https://user-images.githubusercontent.com/29307240/29067160-8a7a19ce-7c6c-11e7-8fe1-7950d0dad702.png)

**Comment by jin239fa** [comment]
![image](https://user-images.githubusercontent.com/29307240/29067188-afa6ba0e-7c6c-11e7-978c-70eadc74d6dc.png)

**Comment by przemyslawlis** [comment]
Edit **source_create_graph** subtest if you want to change the R code for creating graph.

**Comment by jin239fa** [comment]
![-aaa](https://user-images.githubusercontent.com/29307240/29411338-64de700a-838f-11e7-892b-f37fe1e4170b.jpg)

**Comment by jin239fa** [comment]
Sorry to bother you.
I have attached the screenshot above.
Is it the right way to create a different graph?
Thank you

**Comment by przemyslawlis** [comment]
No, you should edit source_create_graph test to change it's default behavior. Look for it in **Tests** tab, and make sure that you have starter content tests visible in tests list filter.

**Comment by sakurasara** [comment]
I tried to create a graph. Can someone guide me? I tried to do a simple graph but its not working.
