### ISSUE TITLE
Form node to save data node

### ISSUE THREAD

**Issue by Abuamany** [campsych/concerto-platform#136]
I use the save data node form, and I have connected the out form node to the node save data, the response node to new data as shown. 

![screenshot from 2017-06-26 16-18-20](https://user-images.githubusercontent.com/16170999/27532640-246c0cda-5a8b-11e7-8657-7868ada24c27.png)

Why data from forms like ages, gender, email can not be saved in the default data table?

**Comment by przemyslawlis** [comment]
When connecting **form** to **save_data** use **submit** port on **form**.
**out** port is leftover from older version you had and is not used anymore. It is removed from latest starter content version.

**Comment by Abuamany** [comment]
We have tried :
![screenshot from 2017-08-02 05-53-34](https://user-images.githubusercontent.com/16170999/28850490-1ca8e99a-7747-11e7-80b3-2bb671efbaac.png)

connecting response to new data with list(value=age,gender), the result as
Error in retFunc(concerto$flow[[flowIndex]]$ports[[as.character(connection$sourcePort_id)]]$value): object 'age' not found
