### ISSUE TITLE
Feedback Node Bugs?

### ISSUE THREAD

**Issue by NatashkaX** [campsych/concerto-platform#137]
For the most part the feedback node works perfectly, but I've encountered two issues that I don't think I quite understand. Could I be using the node incorrectly?

**1) Scores that belong in band 9, incorrectly get feedback of band 1 scores, but band 1 scores get the correct feedback. As far as I'm aware this is only happening to scores that were calculated using an R code node**

![screenshot 4](https://user-images.githubusercontent.com/11052619/27650868-40679176-5c2e-11e7-8ac2-141bacb20dd5.png)

R code:
_total = list()
total$total <- arg1$INF+arg1$NCO+arg1$DISM+arg1$AVM+arg1$NSM+arg1$IMP+arg1$PE+arg1$GRISS
print(total)
return(total)_

This is what I have going on in the feedback node of the 'total' trait:
![screenshot 6](https://user-images.githubusercontent.com/11052619/27651018-d35b87a8-5c2e-11e7-891d-021d49126814.png)

As far as I know, everything works fine with all of the bands but the last one.

**2) Feedback for non-R code node generated scores sometimes goes missing**
For example with this specification below:
![screenshot 8](https://user-images.githubusercontent.com/11052619/27651881-a98a05d2-5c31-11e7-930b-fbddbc50f384.png)
Scores of 6, 7 and 11 work fine and display the correct feedback, but if the person gets scores of 8 or 9, the feedback just doesn't show for this trait.

Let me know what you think!

**Comment by davidstillwell** [comment]
Hi Natasha, can you email me online access details to your test and I'll have a quick look? Given your description, it isn't obvious to me what the issue might be.

**Comment by davidstillwell** [comment]
OK I think I fixed it on your instance. I believe it was treating the min/max values in the feedback node as character, so I added in some as.numeric functions. Please can you check that it works as expected now Natasha - I added in some extra error messages that should help to point out what's going wrong when it doesn't show anything.

If this is indeed the issue, then we'll have to update source_feedback code. For anyone else reading this with the same issue, you need to update this line to add the as.numeric functions I added:

if(as.numeric(t_bound$min_value) <= score && as.numeric(t_bound$max_value) > score) {

**Comment by NatashkaX** [comment]
This is working perfectly now. Thank you very much!
