### ISSUE TITLE
Translate to spanish

### ISSUE THREAD

**Issue by johnfelipe** [campsych/concerto-platform#14]
Hi i want colaborate

**Comment by przemyslawlis** [comment]
Hi johnfelipe!
Great to hear that! You're very welcome to submit a pull request with spanish translation. 
This guide should help you get started with translation: https://github.com/campsych/concerto-platform/wiki/Translating-Concerto-Platform . 
Please let me know if you need any help.

**Comment by chrisgibbons** [comment]
Hey Felipe,

There has been interest to develop Concerto in Spanish with Barcelona
researchers, would you like me to make an introduction so that you can work
with them?

Best wishes,
Chris

 Chris Gibbons PhD. CPsychol.



NIHR Post-Doctoral Research Fellow | Primary Care Unit | Institute of
Public Health |

University of Cambridge School of Clinical Medicine | Fovie Site | CB2 0SR


Psychologist | The Psychometrics Centre| Judge Business School | University
of Cambridge  |17 Mill Lane | CB2 1RX



Skype| drcjgibbons

Web | *http://www.psychometrics.cam.ac.uk/about-us/directory/Chris_Gibbons
<http://www.psychometrics.cam.ac.uk/about-us/directory/Chris_Gibbons>*

**Comment by johnfelipe** [comment]
@chrisgibbons pls share me contact

**Comment by johnfelipe** [comment]
i do this

	sudo nano /var/www/concerto/src/Concerto/PanelBundle/Resources/translations/login.es_ES.yml

	##
	form:
	  legend: Por favor ingrese sus credenciales
	  legend.tooltip: Ingrese su usuario y contraseña
	  field:
		login: Login
		login.tooltip: Por favor ingrese su ID de usuario
		password: Contraseña
		password.tooltip: Por favor entre su contraseña
	  button.login: Log in

	'Bad credentials.': ¡Usuario o contraseña incorrectos!
	'User account is disabled.': Usuario está archivado!

	##
next

	cd /var/www/concerto

	sudo php app/console debug:translation es_ES --only-missing

and show me this error:

`[WARNING] No defined or extracted messages for locale "es_ES"`

**Comment by przemyslawlis** [comment]
If you recently modified translation files and you want to run the command, please make sure you've cleared the cache.
<notextile><pre>php app/console cache:clear</pre></notextile>

It seems like you also need to explicitly enter name of the bundle where you want to debug translations.
<notextile><pre>php app/console debug:translation pt_BR --only-missing ConcertoPanelBundle
php app/console debug:translation pt_BR --only-missing ConcertoTestBundle</pre></notextile>
Translation guide has been updated with above.

**Comment by johnfelipe** [comment]
This is log after that commands

https://gist.github.com/johnfelipe/bd86160b7789e86cf3d0bb3d5d258d11

And is not translated to spanish

![notranslated](https://cloud.githubusercontent.com/assets/428820/16897036/19d9d1a6-4b6b-11e6-821e-ff8699dace20.png)

**Comment by przemyslawlis** [comment]
Looks fine. From what I see you've just added login.es_ES.yml so it tells you that you have many translated strings missing. 

What you need to do is: add rest of the translation files for en_ES and submit pull request. 
If everything will be ok with translation, it's going to be made available as a new language in Concerto Platform

Please let me know if something is unclear.

**Comment by johnfelipe** [comment]
what is command for do pull request?

**Comment by przemyslawlis** [comment]
This should get you started with PR: https://help.github.com/articles/using-pull-requests/

If you don't feel comfortable doing it, you can alternatively send me a zipped package with all translation files in it and I can take care of the rest.

**Comment by johnfelipe** [comment]
but u cant share me commands for to it from myself at begin
Later i do PR with all correct translation, my email is ingenierofelipeurrego@gmail.com

**Comment by przemyslawlis** [comment]
Here's GIT pull request command documentation: https://git-scm.com/docs/git-request-pull
If this is your first time with GIT I suggest you try to do it through GUI (e.g. GitHub's).

**Comment by johnfelipe** [comment]
@przemyslawlis i know how create or send PR, but my question is how test only `login.es_ES.yml`, do u get me?

**Comment by przemyslawlis** [comment]
If you want to change your app locale and see the effect of your translation files live, inside app, you can do it by:

1. Adding new locale to /app/config/config.yml
<notextile><pre>
parameters:
    version: 5.0.beta.2.120
    available_locales:
        en_GB: english
        pl_PL: polski
        en_ES: español
(...)
</pre></notextile>
1. Clear cache
<notextile><pre>
php app/console cache:clear
</pre></notextile>
1. Launch Concerto Platform panel
1. Change locale from within app by selecting new languange from drop-down button in top-right corner 

Fallback language is English. This means that whatever missing translation you have will be displayed in English.

**Comment by johnfelipe** [comment]
Is not working

http://181.136.243.82/admin

is test server, admin, admin is credentials for now

**Comment by johnfelipe** [comment]
This is my installation steps:

https://docs.google.com/document/d/1yRty3f95y1zPwAJBw06oXQ9xsZqpvP0QByE5B0CtC98/edit?usp=sharing

Pls help me to solve translation issue and this issue https://github.com/campsych/concerto-platform/issues/18 to
Stay alert

**Comment by przemyslawlis** [comment]
Sorry, I forgot to add that you should clear production cache.
<notextile><pre>php app/console cache:clear --env=prod</pre></notextile>

**Comment by johnfelipe** [comment]
with that command concerto is down

![concertodown](https://cloud.githubusercontent.com/assets/428820/16897467/21b5fa0a-4b78-11e6-951f-11e897a98bf3.png)

**Comment by przemyslawlis** [comment]
Beside clearing the cache this command also recreates it. If you performed this command as root, then most probably your cache is not readable by your web user which gives us 500 error.

1. Delete whole **app/cache/prod** directory with all it's content. 
1. Refresh web page

**Comment by johnfelipe** [comment]
Then, give me correct command steps, because my installation process is with sudo in multiples parts, because EACCESS error show me several times, please take a look:

https://docs.google.com/document/d/1yRty3f95y1zPwAJBw06oXQ9xsZqpvP0QByE5B0CtC98/edit?usp=sharing

**Comment by przemyslawlis** [comment]
https://github.com/campsych/concerto-platform/wiki/Linux-installation - here you can see which commands requires sudo.

**Comment by johnfelipe** [comment]
i will update installation and put all in /home/felipe directory for not problems with sudo

**Comment by johnfelipe** [comment]
felipe@felipeurrego:~/concerto$ php app/console cache:clear --env=prod


	  [RuntimeException]
	  Unable to write in the "/home/felipe/concerto/app/cache/prod" directory


	cache:clear [--no-warmup] [--no-optional-warmers]

**Comment by johnfelipe** [comment]
I delete it with `sudo rm -rf /home/felipe/concerto/app/cache/prod/`

And have a change but how can put flag of colombia:

![spanishflag](https://cloud.githubusercontent.com/assets/428820/16898062/a98787a4-4b8d-11e6-8f0c-7203f6a7571a.png)

But login page still English

**Comment by przemyslawlis** [comment]
Don't trouble yourself with the flag. I'll add it to your PR when you're done with translation as it needs to be consistent with rest of the flags.

Currently locale setting is sticky across session. When logging out session gets removed and fallback locale is used (en_GB). I'll be probably adding 'login form' locale switching soon.
