### ISSUE TITLE
Home Page is Not Showing

### ISSUE THREAD

**Issue by rby813** [campsych/concerto-platform#140]
I've been following through the Linux setup guide and writing revisions for it as I had a plethora of issues, likely stemming from dependency updates here and there, and I'm on the home stretch but I'm stuck and I can't seem to Google my way out of this one.

When I load up my website, it simply displays the contents of /var/www/vhosts/concerto/web: app.php, app_dev.php, etc
If I append /admin to the url, it simply directs me to a generic "/admin not found on this server" page.
I'm currently running on Ubuntu Server 16.04.02, and have included my apache2.conf and my sites-available config.  If anyone could tell me how I can fix this, I would be very appreciative, and I could finish my wiki revisions to give back.
Thank you for your time.

```
<VirtualHost *:80>
	ServerName jamesconcerto.com
	ServerAlias www.jamesconcerto.com
	ServerAdmin ******@tuta.io
	DocumentRoot /var/www/vhosts/concerto/web
	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
```
```
Mutex file:${APACHE_LOCK_DIR} default
PidFile ${APACHE_PID_FILE}
Timeout 300
KeepAlive On
MaxKeepAliveRequests 100
KeepAliveTimeout 5
User ${APACHE_RUN_USER}
Group ${APACHE_RUN_GROUP}
HostnameLookups Off
ErrorLog ${APACHE_LOG_DIR}/error.log
LogLevel warn
IncludeOptional mods-enabled/*.load
IncludeOptional mods-enabled/*.conf
Include ports.conf

<Directory />
	Options FollowSymLinks
	AllowOverride None
	Require all denied
</Directory>

<Directory /usr/share>
	AllowOverride None
	Require all granted
</Directory>

<Directory /var/www/>
	Options Indexes FollowSymLinks
	AllowOverride None
	Require all granted
</Directory>

<Directory /srv/>
	Options Indexes FollowSymLinks
	AllowOverride None
	Require all granted
</Directory>

<Directory /var/www/vhosts/concerto/web>
	AllowOverride
</Directory>

AccessFileName .htaccess

<FilesMatch "^\.ht">
	Require all denied
</FilesMatch>

LogFormat "%v:%p %h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" vhost_combined
LogFormat "%h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" combined
LogFormat "%h %l %u %t \"%r\" %>s %O" common
LogFormat "%{Referer}i -> %U" referer
LogFormat "%{User-agent}i" agent

IncludeOptional conf-enabled/*.conf
IncludeOptional sites-enabled/*.conf
```

**Comment by przemyslawlis** [comment]
> If I append /admin to the url, it simply directs me to a generic "/admin not found on this server" page.

^ This might indicate that you don't have Apache2 mod **rewrite** enabled. Try doing:
<pre>a2enmod rewrite
service apache2 restart</pre>

> When I load up my website, it simply displays the contents of /var/www/vhosts/concerto/web: app.php, app_dev.php, etc

^ What do you mean by that? Does it show the source code of php files for you?

**Comment by przemyslawlis** [comment]
No response - closing. Feel free to respond and reopen.
