### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by oloabbott** [campsych/concerto-platform#143]
I have succeeded in installing concerto launcher on windows, but when I clicked on run, the browser displayed the image below

![image_1](https://user-images.githubusercontent.com/30015105/28247719-115203e2-69eb-11e7-8b40-e9903426b38f.png)

**Comment by jkrow** [comment]
I am getting the same error on windows 10 64 bit

**Comment by przemyslawlis** [comment]
Duplicate of #144
