### ISSUE TITLE
Not Found

### ISSUE THREAD

**Issue by oloabbott** [campsych/concerto-platform#144]
I have finished the offline installation of the concerto launcher for windows, but when I clicked run the browser showed the error "404 not found". Please what should be done for the user interface to be displayed.

**Comment by przemyslawlis** [comment]
I suggest you try other installation method than Windows Installer for now (e.g. https://github.com/campsych/concerto-platform/wiki/Linux-installation). Windows installer will be retired very soon and replaced with new install method.

**Comment by pabloenlondres** [comment]
#przemyslawlis I tried to download and run Concerto as well on windows offline, and got the same error.  I am running it in my normal profile. When I run it as administrator I can't even download all of the packages.  It's not really very good that you can't use windows to run Concerto and are being asked to run it in Linux. the install instructions are also too complex for people who aren't programmers
