### ISSUE TITLE
present id on test items

### ISSUE THREAD

**Issue by karends** [campsych/concerto-platform#146]
This is a query rather than an issue.  Could you please advise how to present the id on test items to aid testing/trialing please?

**Comment by jin239fa** [comment]
![1234](https://user-images.githubusercontent.com/29307240/29004470-7c0fba4e-7b02-11e7-8be4-e432249e54a2.png)

**Comment by jin239fa** [comment]
![2](https://user-images.githubusercontent.com/29307240/29004473-9763c13c-7b02-11e7-8998-46a6b06a2dfb.png)

**Comment by jin239fa** [comment]
I managed to get the results. Thank you.
However, I have got some questions.
1. It is shown as ggplot. how can i change the graph as standard deviation?
  Do i have to use R code node without create graph node? 
2. I want to convert theta results to percentile 0 %to 100% . Is that possible?

I am looking forward to hearing from you.

Thank you

**Comment by bluebl** [comment]
I managed to solve this. (abrown@ccea.org.uk). I added this piece of R code into the CAT source. title<-question$id  this then displays the item number in the {{title}} slot in the create template definition node > default layout template (copy) . I then moved the {{title}} down a bit in my custom layout template ( adapted from default layout template ). If there is a more graceful way let me know.
