### ISSUE TITLE
Unable to load autocompletion data!

### ISSUE THREAD

**Issue by Deleetdk** [campsych/concerto-platform#147]
I have this issue.

![concerto r completion](https://user-images.githubusercontent.com/6759913/28469299-da49b832-6e03-11e7-9135-3655dcc436cb.png)

But following the on-screen instructions doesn't do anything.

```
emil@remote:/var/www/vhosts/concerto/app$ sudo php console concerto:r:cache
[sudo] password for emil: 
PHP Warning:  Module 'intl' already loaded in Unknown on line 0
Generating R documentation cache. This might take several minutes...
Saved: 0/0 | 0%
R documentation cache generated.
```

I don't think the warning is important here. It's related to me loading the intl twice because docs were unclear where to put the loading command (it goes into `/etc/php/7.0/cli/php.ini` not `/etc/php/7.0/apache2/php.ini`).

The actual tests on the server runs fine, so the R packages must be installed. I installed them on root. Do I need to install them on the server's user too or?

**Comment by przemyslawlis** [comment]
Try to run the command as exactly same user that installed R packages.

**Comment by przemyslawlis** [comment]
No response. Closing.
