### ISSUE TITLE
Problem accessing Admin Page

### ISSUE THREAD

**Issue by junaidia2005** [campsych/concerto-platform#148]
Hi,

I've tried installing Concerto in a linux server by following the instructions from the website.
When I tried to access the admin page http://mydomain/admin, I got the following message...

Not Found
The requested URL /admin was not found on this server.

but when I tried to access http://mydomain, it leads me to http://mydomain/app.php/
and it shows the following page

![image](https://user-images.githubusercontent.com/25382564/28805349-fdcb5fea-769b-11e7-863f-3f9e643f880d.png)

What could be wrong? It seems that just my admin page that is not accessible, otherwise, everything else seems ok. Anybody got the same problem?

Junaidi

**Comment by przemyslawlis** [comment]
Are you running it on Apache2? Do you have Apache2 mod **rewrite** enabled. Try doing:
<pre>a2enmod rewrite
service apache2 restart</pre>

**Comment by junaidia2005** [comment]
Thank you. It works but I have the following error instead.

![image](https://user-images.githubusercontent.com/25382564/28839402-1e4adad6-7726-11e7-932a-54a4e014c6f9.png)

**Comment by przemyslawlis** [comment]
Please paste the contents of your browser console on that page.

**Comment by junaidia2005** [comment]
Hi,

It is as below.

Failed to load resource: the server responded with a status of 404 (Not Found)
show-hint.css Failed to load resource: the server responded with a status of 404 (Not Found)
angular-wizard.css Failed to load resource: the server responded with a status of 404 (Not Found)
jquery-ui.min.css Failed to load resource: the server responded with a status of 404 (Not Found)
jquery.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
jquery.metadata.js Failed to load resource: the server responded with a status of 404 (Not Found)
bootstrap-theme.min.css Failed to load resource: the server responded with a status of 404 (Not Found)
jquery-migrate-1.2.1.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
jquery-ui.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
jquery.mousewheel.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
angular.js Failed to load resource: the server responded with a status of 404 (Not Found)
angular-block-ui.css Failed to load resource: the server responded with a status of 404 (Not Found)
angular-animate.js Failed to load resource: the server responded with a status of 404 (Not Found)
angular-sanitize.js Failed to load resource: the server responded with a status of 404 (Not Found)
ui-grid.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
ui-bootstrap.js Failed to load resource: the server responded with a status of 404 (Not Found)
ui-bootstrap-tpls.js Failed to load resource: the server responded with a status of 404 (Not Found)
angular-block-ui.js Failed to load resource: the server responded with a status of 404 (Not Found)
ckeditor.js Failed to load resource: the server responded with a status of 404 (Not Found)
ng-ckeditor.js Failed to load resource: the server responded with a status of 404 (Not Found)
codemirror.js Failed to load resource: the server responded with a status of 404 (Not Found)
fullscreen.js Failed to load resource: the server responded with a status of 404 (Not Found)
fullscreen.css Failed to load resource: the server responded with a status of 404 (Not Found)
bundles/concertopanel/angularjs/bower_components/angular-ui-grid/ui-grid.min.css?v=5.0.beta.2.186 Failed to load resource: the server responded with a status of 404 (Not Found)
bundles/concertopanel/angularjs/bower_components/codemirror/lib/codemirror.css?v=5.0.beta.2.186 Failed to load resource: the server responded with a status of 404 (Not Found)
javascript.js Failed to load resource: the server responded with a status of 404 (Not Found)
css.js Failed to load resource: the server responded with a status of 404 (Not Found)
sql.js Failed to load resource: the server responded with a status of 404 (Not Found)
angular-file-upload.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
xml.js Failed to load resource: the server responded with a status of 404 (Not Found)
sortable.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
angular-ui-router.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
htmlmixed.js Failed to load resource: the server responded with a status of 404 (Not Found)
r.js Failed to load resource: the server responded with a status of 404 (Not Found)
angular-wizard.js Failed to load resource: the server responded with a status of 404 (Not Found)
ui-codemirror.js Failed to load resource: the server responded with a status of 404 (Not Found)
dom.jsPlumb-1.7.6-min.js Failed to load resource: the server responded with a status of 404 (Not Found)
pdfmake.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
angular-bind-html-compile.js Failed to load resource: the server responded with a status of 404 (Not Found)
csv.js Failed to load resource: the server responded with a status of 404 (Not Found)
angular-breadcrumb.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
ng-context-menu.js Failed to load resource: the server responded with a status of 404 (Not Found)
jquery.metadata.js Failed to load resource: the server responded with a status of 404 (Not Found)
jquery-migrate-1.2.1.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
jquery-ui.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
jquery.mousewheel.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
angular.js Failed to load resource: the server responded with a status of 404 (Not Found)
angular-animate.js Failed to load resource: the server responded with a status of 404 (Not Found)
angular-sanitize.js Failed to load resource: the server responded with a status of 404 (Not Found)
ui-grid.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
ui-bootstrap.js Failed to load resource: the server responded with a status of 404 (Not Found)
ui-bootstrap-tpls.js Failed to load resource: the server responded with a status of 404 (Not Found)
angular-block-ui.js Failed to load resource: the server responded with a status of 404 (Not Found)
ckeditor.js Failed to load resource: the server responded with a status of 404 (Not Found)
ng-ckeditor.js Failed to load resource: the server responded with a status of 404 (Not Found)
codemirror.js Failed to load resource: the server responded with a status of 404 (Not Found)
fullscreen.js Failed to load resource: the server responded with a status of 404 (Not Found)
extended-show-hint.js:10 Uncaught ReferenceError: CodeMirror is not defined
    at extended-show-hint.js:10
    at extended-show-hint.js:11
codemirror-r-completion.js:7 Uncaught ReferenceError: CodeMirror is not defined
    at codemirror-r-completion.js:7
    at codemirror-r-completion.js:8
xml.js Failed to load resource: the server responded with a status of 404 (Not Found)
javascript.js Failed to load resource: the server responded with a status of 404 (Not Found)
css.js Failed to load resource: the server responded with a status of 404 (Not Found)
htmlmixed.js Failed to load resource: the server responded with a status of 404 (Not Found)
r.js Failed to load resource: the server responded with a status of 404 (Not Found)
sql.js Failed to load resource: the server responded with a status of 404 (Not Found)
ui-codemirror.js Failed to load resource: the server responded with a status of 404 (Not Found)
angular-file-upload.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
angular-wizard.js Failed to load resource: the server responded with a status of 404 (Not Found)
sortable.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
angular-ui-router.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
angular-breadcrumb.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
angular-bind-html-compile.js Failed to load resource: the server responded with a status of 404 (Not Found)
dom.jsPlumb-1.7.6-min.js Failed to load resource: the server responded with a status of 404 (Not Found)
ng-context-menu.js Failed to load resource: the server responded with a status of 404 (Not Found)
pdfmake.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
csv.js Failed to load resource: the server responded with a status of 404 (Not Found)
app.js:1 Uncaught ReferenceError: angular is not defined
    at app.js:1
main_controller.js:6 Uncaught TypeError: Cannot read property 'controller' of undefined
    at main_controller.js:6
content_controller.js:20 Uncaught TypeError: Cannot read property 'controller' of undefined
    at content_controller.js:20
header_controller.js:12 Uncaught TypeError: Cannot read property 'controller' of undefined
    at header_controller.js:12
test_wizard_controller.js:484 Uncaught TypeError: Cannot read property 'controller' of undefined
    at test_wizard_controller.js:484
test_wizard_carousel_step_controller.js:20 Uncaught TypeError: Cannot read property 'controller' of undefined
    at test_wizard_carousel_step_controller.js:20
test_controller.js:751 Uncaught TypeError: Cannot read property 'controller' of undefined
    at test_controller.js:751
view_template_controller.js:140 Uncaught TypeError: Cannot read property 'controller' of undefined
    at view_template_controller.js:140
data_table_controller.js:476 Uncaught TypeError: Cannot read property 'controller' of undefined
    at data_table_controller.js:476
user_controller.js:43 Uncaught TypeError: Cannot read property 'controller' of undefined
    at user_controller.js:43
grid_service.js:1 Uncaught TypeError: Cannot read property 'factory' of undefined
    at grid_service.js:1
r_documentation_service.js:3 Uncaught TypeError: Cannot read property 'factory' of undefined
    at r_documentation_service.js:3
base_collection_service.js:1 Uncaught TypeError: Cannot read property 'factory' of undefined
    at base_collection_service.js:1
test_collection_service.js:1 Uncaught TypeError: Cannot read property 'factory' of undefined
    at test_collection_service.js:1
test_wizard_collection_service.js:1 Uncaught TypeError: Cannot read property 'factory' of undefined
    at test_wizard_collection_service.js:1
view_template_collection_service.js:1 Uncaught TypeError: Cannot read property 'factory' of undefined
    at view_template_collection_service.js:1
data_table_collection_service.js:1 Uncaught TypeError: Cannot read property 'factory' of undefined
    at data_table_collection_service.js:1
user_collection_service.js:1 Uncaught TypeError: Cannot read property 'factory' of undefined
    at user_collection_service.js:1
test_wizard_param_service.js:3 Uncaught TypeError: Cannot read property 'service' of undefined
    at test_wizard_param_service.js:3
file_browser_controller.js:116 Uncaught TypeError: Cannot read property 'controller' of undefined
    at file_browser_controller.js:116
ng_thumb_directive.js:4 Uncaught ReferenceError: angular is not defined
    at ng_thumb_directive.js:4
flow_logic_directive.js:2 Uncaught ReferenceError: angular is not defined
    at flow_logic_directive.js:2
wizard_param_definer_directive.js:1 Uncaught ReferenceError: angular is not defined
    at wizard_param_definer_directive.js:1
wizard_param_setter_directive.js:1 Uncaught ReferenceError: angular is not defined
    at wizard_param_setter_directive.js:1
trusted_html.js:1 Uncaught ReferenceError: angular is not defined
    at trusted_html.js:1
logical.js:1 Uncaught ReferenceError: angular is not defined
    at logical.js:1
capitalize.js:1 Uncaught ReferenceError: angular is not defined
    at capitalize.js:1
login:513 Uncaught ReferenceError: $ is not defined
    at login:513
login:1 This page includes a password or credit card input in a non-secure context. A warning has been added to the URL bar. For more information, see https://goo.gl/zmWq3m.
bootstrap.min.css Failed to load resource: the server responded with a status of 404 (Not Found)
ui-grid.min.css Failed to load resource: the server responded with a status of 404 (Not Found)
bootstrap-theme.min.css Failed to load resource: the server responded with a status of 404 (Not Found)
codemirror.css Failed to load resource: the server responded with a status of 404 (Not Found)
angular-wizard.css Failed to load resource: the server responded with a status of 404 (Not Found)
show-hint.css Failed to load resource: the server responded with a status of 404 (Not Found)
jquery-ui.min.css Failed to load resource: the server responded with a status of 404 (Not Found)
angular-block-ui.css Failed to load resource: the server responded with a status of 404 (Not Found)
fullscreen.css Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by junaidia2005** [comment]
Problem solved.
I reinstall bower and it solved the problem.

I've created a test.. but when I run, I got the following message

![image](https://user-images.githubusercontent.com/25382564/31308215-61845f76-aba5-11e7-9c72-02b2c3411755.png)

Do anyone have the same problem?

**Comment by przemyslawlis** [comment]
Most probably you missed this install step about installing js dependencies:

<pre>
cd /var/www/vhosts/concerto/src/Concerto/PanelBundle/Resources/public/angularjs
bower install
cd /var/www/vhosts/concerto/src/Concerto/TestBundle/Resources/public/angularjs
bower install
</pre>

(paths might be different on your installation). Feel free to reopen if that didn't helped.
