### ISSUE TITLE
long time for install installing ggplot2 R package

### ISSUE THREAD

**Issue by Hardianirwanti** [campsych/concerto-platform#150]
Please help, i try install, but when install ggplot2 R package, im waiting for long time and never finish.
please look my picture to see stuck install
![1](https://user-images.githubusercontent.com/31027957/29303700-de8e0844-81b8-11e7-88b9-fb867638acdb.png)

**Comment by przemyslawlis** [comment]
Installing ggplot2 might take over half hour in some cases. Give it some time.
