### ISSUE TITLE
Creating authorized client

### ISSUE THREAD

**Issue by porkchop-jim** [campsych/concerto-platform#151]
I'm trying to get an access token. I'm using the the Concerto AMI that was created on AWS.

I connected the console and I tried these 2 methods.

`php app/console oauth-server:client:create --redirect-uri='aws site' --grant-type=token --grant-type=client_credentials`

`php bin/console oauth-server:client:create --redirect-uri='aws site' --grant-type=token --grant-type=client_credentials`

Then I get this response.

`Could not open input file: app/console`
`Could not open input file: bin/console`

Can anyone help out with this it would be greatly appreciated? Thank you.

**Comment by porkchop-jim** [comment]
Went to the correct directory. Typed this into the console.

`cd /var/www/html/concerto-platform`

Then in that directory I type the recommended method to create a client as following.

`php app/console oauth-server:client:create --redirect-uri='aws site address' --grant-type=token --grant-type=client_credentials`

![screenshot_20170831112538](https://user-images.githubusercontent.com/15966473/29903500-28a5d9b0-8e3f-11e7-9d19-3f0d78fbf32b.png)

**Comment by porkchop-jim** [comment]
Problem solved. Go to the directory as stated. Add "sudo"

`sudo php app/console oauth-server:client:create --redirect-uri='aws site address' --grant-type=token --grant-type=client_credentials`

**Comment by JanowskiMaciej** [comment]
I have got problem with my concerto server (see: https://github.com/campsych/concerto-platform/issues/153). Could you send me a copy of empty default_data_table, please?
