### ISSUE TITLE
Custom Template Not Working

### ISSUE THREAD

**Issue by porkchop-jim** [campsych/concerto-platform#152]
When I make a custom template for the CAT test, I get this error when I run it.

![screenshot_20170910093152](https://user-images.githubusercontent.com/15966473/30245129-0cce0d9c-960b-11e7-868e-9dfa255096d6.png)

I can't seem to display the multiple choice questions. Is this something I'm doing wrong or is it something else?

Thanks for your help.

**Comment by JanowskiMaciej** [comment]
I have got a problem with my concerto server (see: https://github.com/campsych/concerto-platform/issues/153). Could you send me a copy of empty default_data_table, please?

**Comment by przemyslawlis** [comment]
What Concerto version is it on?
Can you please paste contents of last XHR request response body when getting this error?
See: https://github.com/campsych/concerto-platform/wiki/Reporting-Issues#how-to-check-for-server-side-errors-in-chrome

**Comment by przemyslawlis** [comment]
No response. Closing.
