### ISSUE TITLE
No data from forms

### ISSUE THREAD

**Issue by JanowskiMaciej** [campsych/concerto-platform#153]
Concerto v5.0.beta.2.186

I cannot find data from a form node from my tests. Answers from questionnaire nodes are in proper tables but the default_data_table (neither any other) does not collect any new data as age, gender etc. I have tried to use save_data node (suggestion: https://github.com/campsych/concerto-platform/issues/64) with various configurations of 'in' ports, but nothing has helped (similar unsolved problem is here: https://github.com/campsych/concerto-platform/issues/136).
Possible reasons:
I have to use the new_data port but I have changed the default_data_table and by this reason it cannot be used as a default one. – How to restore it? What columns and what types of data are default?
When I use save_data node (input new_data or data_bank ports) I should convert variable to a list (https://github.com/campsych/concerto-platform/wiki/Save-Data-node). – Is it described anywhere in a 'step-by-step' way for newbies who does not know R?

**Comment by Abuamany** [comment]
![screenshot from 2017-09-29 17-06-23](https://user-images.githubusercontent.com/16170999/31011478-9d741aee-a538-11e7-90f3-22960b6702a3.png)

We have success to use save node..... can you import the test
https://github.com/Abuamany/CAT-Assissted/blob/master/Test_Save_node.concerto

using log in : 1  password : abc

**Comment by JanowskiMaciej** [comment]
Thank you for the answer.

I have imported the test, but it does not run. The only reaction is:
_Error encountered. Execution halted._ 
There is nothing in an Error logs window (after debug).
Info from my browser console:

_Loading required package: concerto5
Loading required package: session
Loading required package: jsonlite
Loading required package: methods
Loading required package: RMySQL
Loading required package: DBI
[1] "running test #70..."
[1] "running test #33..."
<simpleError in library(digest): there is no package called ‘digest’>
[1] "responding to server..."
[1] "responded to server"
[1] "updating session..."_

I need additional package I suppose...?

**Comment by Abuamany** [comment]
yap.... the digest package from R not installed.

**Comment by JanowskiMaciej** [comment]
The Test_save_node still does not work.
On the first screen I have written login and password and I have pressed log in button. After that:
Error encountered. Execution halted.
Error logs: NA.
No info in my browser console.

**Comment by JanowskiMaciej** [comment]
Can enybody send me a copy of empty default_data_table, please?

**Comment by przemyslawlis** [comment]
To restore your **default_data_table**, you can import it from 
<pre>./src/Concerto/PanelBundle/Resources/starter_content/DataTable_default_data_table.concerto.json</pre>

**save_date::new_data** port accepts a list variable with key-value pairs for record, e.g.:

<pre>
list(
   name1="val1",
   name2="val2"
)</pre>

**Comment by JanowskiMaciej** [comment]
It's OK now. Thanks.
