### ISSUE TITLE
Long time for install installing ggplot2 R package 

### ISSUE THREAD

**Issue by Dukhayel** [campsych/concerto-platform#154]
I try to install, but when installing ggplot2 R package, I'm waiting for a long time and never finish.
please look my picture to see stuck install.

It is the exact issue as this user reports 
https://github.com/campsych/concerto-platform/issues/150

**Comment by Dukhayel** [comment]
https://github.com/campsych/concerto-platform/issues/150

**Comment by przemyslawlis** [comment]
Duplicate of #150
