### ISSUE TITLE
404 Error after complete installation

### ISSUE THREAD

**Issue by Curifiq** [campsych/concerto-platform#155]
http://52.66.188.123

This is my server link. It is an AWS Ubuntu 16.0.4 server.
After going through all the steps successfully mentioned at https://github.com/campsych/concerto-platform/wiki/Linux-installation , when i try to open http://52.66.188.123/admin it gives me a 404 error.
I have tried installing in /var/www/vhosts/concerto as well /var/www/html/vhosts/concerto
Please help me out

**Comment by przemyslawlis** [comment]
What's your current installation file path?
What's your web server?
Can you paste contents of your web server site config file?

**Comment by Curifiq** [comment]
I have mentioned two file paths I had used. I am using Ubuntu 16.04 on AWS.

**Comment by przemyslawlis** [comment]
But what's the current one you're using?
Also please answer other questions.

**Comment by przemyslawlis** [comment]
You might want to use docker-compose to install Concerto Platform. See **[docker-compose Installation guide](https://github.com/campsych/concerto-platform/wiki/docker-compose-Installation-guide)**.
