### ISSUE TITLE
[Windows Native Installer] Rscript.exe - Entry Point Not Found

### ISSUE THREAD

**Issue by pritesh2312** [campsych/concerto-platform#156]
![image](https://user-images.githubusercontent.com/25382076/31947129-352d6b9e-b8f1-11e7-9f3b-a622369e8a3d.png)

**Comment by przemyslawlis** [comment]
Are you able to run R on your Windows?

**Comment by pritesh2312** [comment]
Yes, I can run both R and RStudio on Windows.

**Comment by przemyslawlis** [comment]
Did Concerto Setup installed R for you? 
Did you have R installed before running Concerto Setup for first time?
Do you have two R versions installed right now?

**Comment by pritesh2312** [comment]
On Oct 30, 2017 13:43, "przemyslawlis" <notifications@github.com> wrote:

Did Concerto Setup installed R for you?

No

Did you have R installed before running Concerto Setup for first time?

Yes

Do you have two R versions installed right now?

Yes, I have R for Windows 3.3.2 and 3.4.2

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/campsych/concerto-platform/issues/156#issuecomment-340371508>,
or mute the thread

**Comment by przemyslawlis** [comment]
Installer, in your case, seems to not handle too well, dual R installation.

I would suggest, you try manual installation method (e.g. https://github.com/campsych/concerto-platform/wiki/Linux-installation) for now.

Offline Windows Installer will be retired in next couple of weeks and replaced with a new way of installing on Windows (or any other OS).

**Comment by pritesh2312** [comment]
Should I uninstall the older version of R and try again?

**Comment by przemyslawlis** [comment]
Yes, you could try that. Uninstall both versions and let Installer install R for you.
