### ISSUE TITLE
Windows 10 installation issue

### ISSUE THREAD

**Issue by gambitwi** [campsych/concerto-platform#157]
The installer hangs trying to install the ggplot2 R package

**Comment by jkrow** [comment]
Determined issue. Had to find true installer from .appref-ms file. Ran true installer as adminstrator and installation completed successfully

**Comment by przemyslawlis** [comment]
It can take several minutes (over half hour in some cases) to complete ggplot2 installation. Closing for now. Feel free to reopen if you still can't progress past it.

**Comment by przemyslawlis** [comment]
Duplicate of #150
