### ISSUE TITLE
Can't copy default template

### ISSUE THREAD

**Issue by MBAllely** [campsych/concerto-platform#158]
Running on AWS/Ubuntu; Concerto v5.0.beta.2.186
--

Instructions in wiki for creating custom templates says "Go to the Templates tab, click to edit the default template, and Copy the default template into a new one (e.g. "My new template")" but there's no default template listed.
![screen shot 2017-11-02 at 11 48 24 am](https://user-images.githubusercontent.com/13214521/32344414-0ade4596-bfc4-11e7-9226-153e4983fa08.png)

**Comment by davidstillwell** [comment]
Click the filter cross next to "Protected" - it will show you the starter content that Concerto comes with.

We recognise that this isn't a good solution so the latest Concerto does away with that Protected filter and has a separate tab for starter content.
