### ISSUE TITLE
if_statement node problem

### ISSUE THREAD

**Issue by JanowskiMaciej** [campsych/concerto-platform#159]
When I use if_statement node, the branch if_true doesn't work.
My form: gender → Female/Male
My if_statement: ifdata == „Male”
Whatever I choose in my form I always get to info that goes out from if_false output (for Female).

![if](https://user-images.githubusercontent.com/29615884/32369771-d1bf6228-c08a-11e7-8731-41528d1cee54.jpg)

It is the same when I use numbers:
Form: Age
If_statement: ifdata>=18 always turns on if_false option.

What should I change?

**Comment by przemyslawlis** [comment]
**response** port in **form** node is R list. When dragging whole response to **ifdata** port of **if_statement**, you need to edit your **if_conditon** to:
`as.numeric(ifdata$age) >= 18`
