### ISSUE TITLE
Can't run the Concerto Platform in Windows

### ISSUE THREAD

**Issue by pucschan** [campsych/concerto-platform#164]
Hi

I have successfully installed Concerto Platform installation in Windows, but the platform does not run properly when I press Run button in Concerto Launcher.
See the captured screen below.
![capture](https://user-images.githubusercontent.com/34759598/34283572-71f6c50e-e707-11e7-8be8-8b306e257f11.jpg)

Does anyone have an idea how to solve this problem?

**Comment by suleymandemir** [comment]
Hi sir,

I wanted to install concerto launcher and my trying had failed. When I was lookking for any solution about this problem, I saw your entry. Could you find any solution and could you help me??? 

I'm so helpless. Thank you for your attention...

**Comment by CGeorganta** [comment]
I had the same problem with you @pucschan . I think that you have to run all setups as admin. Not only the concerto setup, but also R and Wampserver. That was what I did and now it is working. So my suggestion is un-istallating programs and reinstalling them as admin.

@suleymandemir  I don't know where your process stopped. I guess in ggplot2. If you have installed R, open it and paste the phrase [ install.packages("ggplot2") ] without []. Then press enter.

That is what i did...
I hope it will work for you, as it did for me.

**Comment by suleymandemir** [comment]
Hi @CGeorganta 

I installed the ggplot2 via R. Thank you for this suggestion. But I have also a problem like @pucschan 's problem. And I unistalled all program, than I installed all of them as admin but now it's not working. :(

**Comment by CGeorganta** [comment]
Hi again.

Unfortunately, I'm not an IT expert, so I may not have a right answer for this. 
I don't know if it makes any difference, but when R asked my something about URL, I choose UK(Cambridge). 
Furthermore, Concerto installs many programs (R, Wampserver, Node etc), are you sure you run them all setups as admin? 
Note. I also  run its program as admin (not only their setups, but also the program).

I hope it works after these...

**Comment by CGeorganta** [comment]
Last one. I really don't know if it is important. But I change my PC name with one that contains only English characters.

**Comment by liezelkorf** [comment]
I have the same problem - everything installed fine but when I try to run it there is a 404 error. I tried to uninstall and re-install. I ran the setup.exe as administrator. 
Please help!

**Comment by pucschan** [comment]
Hi all

Sorry for being so late to update you.
I reinstall the package again, and it works. I am quite sure I have used admin rule to install the package for the first time.
Really don't know why this issue happens. 

Hope you can install the package successfully.
