### ISSUE TITLE
How can I see the data (data view)

### ISSUE THREAD

**Issue by CGeorganta** [campsych/concerto-platform#166]
Hello,

I am a new user of this platform and I have a problem on something that may be pretty obvious, but... not for me.

I created a CAT in concerto platform. The test runs normally, but I don't know how to see my data.
I created the save_data node, but I don't know how to see these data, or where they are saved.

Thanks in advance!
![flow-concerto platform](https://user-images.githubusercontent.com/34796371/35148044-73252ace-fd19-11e7-8756-2b091ce9bc68.png)

**Comment by sakurasara** [comment]
Hi,

I hope this will help you as I was having the same problem. There might be better answer to this, but this is what I did.

CAT nodes data will be saved at response bank section, you need to select your table. What I did was, copy the default_cat_response_table (at data tables), put a new name to it and use it CAT nodes. All your response data will be in data tables. You don't really need save_data nodes to save your CAT responses. Then connect the score from CAT nodes to INFO nodes, you should be able to display your theta score.

Hope this will help you! Good luck! 

Cheers!
sakurasara

**Comment by CGeorganta** [comment]
Thanks for your answer! 

May I ask you to upload a picture of what you described in order for me to be sure I'm doing everything as you said. If it is possible, of course!

I' m grateful for your response!
Thanks a lot!

**Comment by sakurasara** [comment]
Hello,

My flow looks something like this.
![flow](https://user-images.githubusercontent.com/25417981/35469467-3963156e-0370-11e8-92fb-b3b6dec22a7c.JPG)

At the Data Table section, you can see the responses saved at assigned table. The default table if i'm not mistaken named 'default_cat_responses_table'. You should be able to view the responses at the table.
As you can see from my test flow, I used save_data nodes after I asked the participant to fill up a demographics form.

Hope this help.

**Comment by CGeorganta** [comment]
I really appreciate your answers.

But, let me see if I'm getting it right.
Should I click Data Tables and then make a double click on Default Cat Response Table? 
Should I export this table? And if I have to export it, then how do I open it? Using which program?

One last, but important issue, I haven't upload the test in any website yet. I don't know the way to do so.
Should I? And how could I?

Thanks for your patience so far!

**Comment by arthurcavalcant** [comment]
Hello, any one could explain me step to step how to save and see the data? I tried following your instructions but I think that Concerto's version is different, can anybody help me out?
