### ISSUE TITLE
Test Doesn't open

### ISSUE THREAD

**Issue by athmaoula** [campsych/concerto-platform#168]
When i create a test and i click on run test, the test page display a please wait and never displays the test.

![image](https://user-images.githubusercontent.com/33434336/35279484-1fd2b86c-0045-11e8-8e59-0c8b77192e71.png)
![image](https://user-images.githubusercontent.com/33434336/35279601-6ee97c74-0045-11e8-9597-bcd00acd6843.png)

**Comment by pucschan** [comment]
I encounter the same issue.
I have installed Concerto (v5.0.beta.2.186) on my VM  at AZURE (2vcpu, 4GB memory).
The OS is Ubuntu 16.04.4 LTS (GNU/Linux 4.13.0-1014-azure x86_64).

Does anyone have any idea how to troubleshoot this issue?

**Comment by przemyslawlis** [comment]
Seems like it's installation issue. Would need app logs to identify the source of the problem.
Please check [docker-compose Installation guide](https://github.com/campsych/concerto-platform/wiki/docker-compose-Installation-guide) for simple docker based installation of latest Concerto Platform version.
