### ISSUE TITLE
not create questionnaries v5.0.beta.2.120

### ISSUE THREAD

**Issue by johnfelipe** [campsych/concerto-platform#17]
![nocreate1](https://cloud.githubusercontent.com/assets/428820/16893792/6dfb2504-4b08-11e6-9ffd-3a42bcafa6fc.png)

![nocreate2](https://cloud.githubusercontent.com/assets/428820/16893793/7186232c-4b08-11e6-93a2-65f7db2a2d58.png)

![nocreate3](https://cloud.githubusercontent.com/assets/428820/16893796/74226cb2-4b08-11e6-8d8a-2571f65d9b1b.png)

How solved?

**Comment by davidstillwell** [comment]
Hi John. Do I understand your post correctly? You click on the Add New test button, enter the test details, but then the test isn't created?

If that's the case, would you give me access to your admin panel so I can check it? PM me the details (URL/Username/Password).

**Comment by johnfelipe** [comment]
i reinstall all again, pls tell me what can install with notroot user and what with sudo?

**Comment by przemyslawlis** [comment]
Check updated installation guide at: https://github.com/campsych/concerto-platform/wiki/Linux-installation to see where sudo is required.

**Comment by johnfelipe** [comment]
i reinstall and works now correctly
