### ISSUE TITLE
CAT example doesn't seem to work

### ISSUE THREAD

**Issue by user8493** [campsych/concerto-platform#170]
Hi,

Installed on a Pi. Implemented the CAT tutorial example from the video with all the same values.

For some reason, on correctly responding that 100+100=200, the test takes me to 10+10.

Then on the final screen instead of being presented with: 

_Thank you for taking the test.

Your scores were:

theta: {{theta}}

SEM: {{sem}}_

, I see only:

-0.5

(presumably the "theta" value?)

Something of a novice here, so I may have done something fundamentally very silly.

**Comment by przemyslawlis** [comment]
Since this is based on outdated version, can you try the latest ([docker-compose Installation guide](https://github.com/campsych/concerto-platform/wiki/docker-compose-Installation-guide)) and open new issue if you still have the problem?
