### ISSUE TITLE
Adapting the item parameters using user response data

### ISSUE THREAD

**Issue by nishantpatni** [campsych/concerto-platform#177]
I am going through the documentation on CAT and I am quite new to it. 
I was wondering whether it is possible to Adapt the item parameters using user data. If so then how? Could not really figure this out from any of the tutorials.

**Comment by postview** [comment]
Hi,
What you suggested is conceptually possible, although hasn't yet been implemented on Concerto.
To guide you in the correct direction.
you can use the ltm package in R to compute item parameters and input them into your CAT node.
But for automating it you need to write an R script that imports the json file into R environment, collect responses, compute item parameters and feed them back to the json file. 
I plan to do this for one of my tests, I ll put that as a feature request and provide the required resources, keep an eye for that.
