### ISSUE TITLE
Bower installation failed

### ISSUE THREAD

**Issue by pabloenlondres** [campsych/concerto-platform#178]
I am trying to download Concerto and all packages install successfully except Bower.  Concerto won't run. What am I doing wrong? I am using the windows offline version.
![image](https://user-images.githubusercontent.com/37499388/37869105-aae6fee8-2fa9-11e8-8876-43f67f5f132c.png)

**Comment by postview** [comment]
I suggest you install independently. For this you first need to install git.
For this visit https://git-scm.com/
Once Git is installed Install Node.js
As Bower depends on Node.js
For this visit https://nodejs.org/en/download/
Once done downloading both
open the start menu and search for Git Bash
Open Git Bash and run `npm install -g bower`

**Comment by przemyslawlis** [comment]
Windows Installer is no longer supported.
Please see [docker-compose Installation guide](https://github.com/campsych/concerto-platform/wiki/docker-compose-Installation-guide) for recommended installation method.
