### ISSUE TITLE
Run test questionnaire issue

### ISSUE THREAD

**Issue by johnfelipe** [campsych/concerto-platform#18]
I create with youtube video guide:

![quesntionnaire1](https://cloud.githubusercontent.com/assets/428820/16897213/6b3534e6-4b70-11e6-81f0-f31d61d75d79.png)

But is not run test correctly

http://181.136.243.82/test/f87ef3d1938e094c1290f0644e9f6964

only have a `Please wait...`

**Comment by przemyslawlis** [comment]
You're getting 500 error code on one of XHR. Can you please paste some logs (PHP logs should contain something interesting)?

Optimal work-flow in case of any 500 errors would be to run it in dev mode (which by default can only be run from the same host), e.g.: http://181.136.243.82/app_dev.php/test/f87ef3d1938e094c1290f0644e9f6964 and read framework error report. 
Can you please try to paste dev error report here?

**Comment by johnfelipe** [comment]
Can u please help me with pata for copy logs

**Comment by johnfelipe** [comment]
Can u please help me with path for copy logs..

**Comment by przemyslawlis** [comment]
To check the source of 500 error in your case you would have to (instructions for Chrome browser):

1. Run Chrome
1. Start **'Developer Tools'** (press F12)
1. paste the dev mode URL you want to open inside the browser (http://181.136.243.82/app_dev.php/test/f87ef3d1938e094c1290f0644e9f6964)
1. Go to **'Network'** tab inside 'Developer Tools' and click on **'XHR'** filter
1. There should be only one XHR in your case which returns with 500 error, click on it's name
1. Check response **'Preview'** (you should get parsed HTML response with error description)

As I said earlier dev mode can only be run from localhost. If you want to access it from remote machine modify **web/app_dev.php** file, and comment out lines 16 and 17:

<pre>
//header('HTTP/1.0 403 Forbidden');
//exit('You are not allowed to access this file. Check '.basename(__FILE__).' for more information.');
</pre>

Keep in mind that making dev mode accessible to everyone is considered dangerous as it might output sensitive data.

**Comment by johnfelipe** [comment]
Pls review

http://181.136.243.82/app_dev.php/test/809e475592827bcdccd3f47015da8dcb

and help me to solve this and continue with my tests

**Comment by przemyslawlis** [comment]
Most probably file permission issue. Please remove both directories listed below (with their content):

- app/cache/dev
- app/cache/prod

**Comment by przemyslawlis** [comment]
After doing above, please make sure that app/cache directory is writable for your web user.

**Comment by johnfelipe** [comment]
cd /home/felipe/concerto
	sudo chmod 777 app/cache app/logs

something else commands?

**Comment by przemyslawlis** [comment]
Do chmod recursively:
<pre>sudo chmod -R 777 app/cache app/logs</pre>

**Comment by johnfelipe** [comment]
felipe@felipeurrego:~$ sudo chmod -R 777 app/cache app/logs
	chmod: cannot access ‘app/cache’: No such file or directory
	chmod: cannot access ‘app/logs’: No such file or directory

**Comment by johnfelipe** [comment]
i do this 

	rm -rf /home/felipe/concerto/app/cache/dev/
	sudo rm -rf /home/felipe/concerto/app/cache/prod

**Comment by przemyslawlis** [comment]
Have you checked if the app/cache and app/logs exist?

You're supposed to run the command from: /home/felipe/concerto

**Comment by johnfelipe** [comment]
felipe@felipeurrego:~/concerto/app$ ls -l
	total 172
	-rw-rw-r-- 1 felipe felipe   141 Jul 20 12:56 AppCache.php
	-rw-rw-r-- 1 felipe felipe  1733 Jul 20 12:56 AppKernel.php
	-rw-rw-r-- 1 felipe felipe   267 Jul 20 12:56 autoload.php
	-rw-rw-r-- 1 felipe felipe 98942 Jul 20 13:07 bootstrap.php.cache
	drwxrwxrwx 4 felipe felipe  4096 Jul 20 13:31 cache
	-rw-rw-r-- 1 felipe felipe  3940 Jul 20 13:07 check.php
	drwxrwxr-x 2 felipe felipe  4096 Jul 20 12:58 config
	-rw-rw-r-- 1 felipe felipe   867 Jul 20 12:56 console
	drwxrwxrwx 2 felipe felipe  4096 Jul 20 13:27 logs
	-rw-rw-r-- 1 felipe felipe  1327 Jul 20 12:56 phpunit.xml.dist
	drwxrwxr-x 3 felipe felipe  4096 Jul 20 12:56 Resources
	-rw-rw-r-- 1 felipe felipe 31511 Jul 20 13:07 SymfonyRequirements.php

i run `php app/console cache:clear --env=prod`

	felipe@felipeurrego:~/concerto$ php app/console cache:clear --env=prod


	  [RuntimeException]
	  Unable to write in the "/home/felipe/concerto/app/cache/prod" directory


	cache:clear [--no-warmup] [--no-optional-warmers]

**Comment by johnfelipe** [comment]
felipe@felipeurrego:~/concerto/app/cache$ ls -l
	total 8
	drwxrwxr-x 9 felipe   felipe   4096 Jul 20 13:31 dev
	drwxr-xr-x 8 www-data www-data 4096 Jul 20 13:30 prod

**Comment by przemyslawlis** [comment]
Do the following:

1. Login as root
1. Do:
<pre>chown -R www-data:www-data /home/felipe/concerto</pre>

**Comment by johnfelipe** [comment]
felipe@felipeurrego:~/concerto/app/cache$ sudo su
	root@felipeurrego:/home/felipe/concerto/app/cache# cd /home/felipe/concerto
	root@felipeurrego:/home/felipe/concerto# chown -R www-data:www-data /home/felipe/concerto
	root@felipeurrego:/home/felipe/concerto# sudo service apache2 restart
	 * Restarting web server apache2                                         [ OK ]

still not work

**Comment by johnfelipe** [comment]
http://181.136.243.82/test/809e475592827bcdccd3f47015da8dcb

`Please wait...`

**Comment by przemyslawlis** [comment]
Run it in debug mode and paste response from requests that finished with 500 error, or turn off debug mode restriction so I can check it out myself.

**Comment by johnfelipe** [comment]
done, do it please

http://181.136.243.82/app_dev.php/test/809e475592827bcdccd3f47015da8dcb

**Comment by przemyslawlis** [comment]
Please paste contents of your */home/felipe/concerto/app/config/parameters_nodes.yml* file

**Comment by johnfelipe** [comment]
# This file is auto-generated during the composer install
	parameters:
		nodes:
			-
				id: local
				protocol: http
				ip: 181.136.243.82
				host: localhost
				dir: /
				connection: local
				hash: '101713356618113624382'

**Comment by przemyslawlis** [comment]
Try to replace:
<pre>ip: 181.136.243.82</pre>
With:
<pre>ip: 127.0.0.1</pre>
Please let me know when it's changed.

**Comment by johnfelipe** [comment]
# This file is auto-generated during the composer install
	parameters:
		nodes:
			-
				id: local
				protocol: http
				ip: 127.0.0.1
				host: localhost
				dir: /
				connection: local
				hash: '101713356618113624382'

and `sudo service apache2 restart`

still not work

or do i need `php app/console cache:clear` and `php app/console cache:clear --env=prod`

**Comment by johnfelipe** [comment]
this
http://181.136.243.82/test/809e475592827bcdccd3f47015da8dcb
not work
but this
http://181.136.243.82/app_dev.php/test/809e475592827bcdccd3f47015da8dcb
it work
![work](https://cloud.githubusercontent.com/assets/428820/17000353/c42594f0-4e87-11e6-892b-8a9ed13d6ce6.png)

**Comment by przemyslawlis** [comment]
No need to restart apache.
All you need to do to apply the changes to prod mode is to clear the cache.
You can clear prod cache by manually removing following directory:
<pre>/home/felipe/concerto/app/cache/prod</pre>
or by running:
<pre>php app/console cache:clear --env=prod</pre>
However when you do it with Symfony command it will recreate a cache which will be owned by whatever  user run the command. Your web user is www-data so cache should be owned by www-data. If you run the command with any other user make sure that ownership is correct.

**Comment by johnfelipe** [comment]
then this command is neccesary

	cd /home/felipe/concerto
	sudo chmod -R 777 app/cache app/logs

	sudo su
	chown -R www-data:www-data /home/felipe/concerto
	exit

right?

then how solve this:

	felipe@felipeurrego:~/concerto$ php app/console cache:clear --env=prod          

	  [RuntimeException]
	  Unable to write in the "/home/felipe/concerto/app/cache/prod" directory


	cache:clear [--no-warmup] [--no-optional-warmers]

and with `sudo` this is log:

https://gist.github.com/johnfelipe/941a3f7ca82654fe2bb95a4d04e45281

**Comment by przemyslawlis** [comment]
What do you mean how to solve it?
The command you're trying to run want to write in directory with user *felipe* that doesn't have permission to do so because I assume that the directory and it's contents are owned by *www-data*.
Either change user that runs the command or change directories/files ownership/permissions.

I checked and the page is already working in prod mode, so seems like the cache was removed and recreated.

**Comment by johnfelipe** [comment]
pls guide me or tell me how is best method for `php app/console cache:clear --env=prod` work correctly in my installation

**Comment by przemyslawlis** [comment]
This commands need to be run by user that has write permission on app/cache/prod directory and all its content. 
This command also creates a cache. Cache created by this command needs to be readable by your web user (**www-data**).

This is what you could do in your case:
<pre>sudo php app/console cache:clear --env=prod
sudo chown -R www-data:www-data /home/felipe/concerto</pre>

**Comment by johnfelipe** [comment]
then all this need sudo

	sudo php app/console concerto:setup
	sudo php app/console concerto:r:cache
	sudo php app/console concerto:content:import
	sudo php app/console cache:clear
	sudo php app/console cache:clear --env=prod

Pls edit wiki

**Comment by przemyslawlis** [comment]
It all depends on context. None of the command above requires sudo. It's worth adding to wiki however that some of the commands:
<pre>concerto:setup
cache:clear</pre>
Will create files owned by the user that run the command. If the user is not the same as web user, there will be additional step required to change ownership of newly created files to web user.

**Comment by johnfelipe** [comment]
both command `permission denied`, but all works for me in this moment:

http://181.136.243.82/test/5e9c2979dfd4950c10f51cb566784c90

**Comment by przemyslawlis** [comment]
Wiki updated.
Closing issue. 
Feel free to open new issue if you still have any problems.

**Comment by ibrahimabdulla** [comment]
Please help im also stuck with these issue ! 
deleted app/cache files
