### ISSUE TITLE
/localhost/admin not found 404

### ISSUE THREAD

**Issue by ch-nour** [campsych/concerto-platform#181]
i followed the instruction at https://github.com/campsych/concerto-platform/wiki/Linux-installation 
successfully i've encountered some errors but i bypassed em all,

but when i try to access /localhost/admin it gives me "The requested URL /admin was not found on this server."

Please Help.

**Comment by postview** [comment]
Hi, most likely it seems that Apche server must have not been correctly installed or been configured. For better diagnosis, run a clean install and paste the terminal output here.

**Comment by ch-nour** [comment]
i don't think it is apache s problem because when i navigate into /var/www/concerto... i don't find any file named admin

**Comment by postview** [comment]
Yes you won't find any file named as admin, as there shouldn't be any. From what I could understand it seems to be a hosting issue. Again for better understanding, I would need the terminal output.

**Comment by postview** [comment]
In your case I assume you are trying to access the website from the server itself. So I suggest run localhost:80/admin in your web browser or localhost:8080/admin . The reason you may not be able to access the website could be because of accessing the incorrect port. Other than this my capabilities are limited here.

**Comment by akt45** [comment]
i have the same problem, im using windows and in corneto launcher all is work correcly, but when i run corcento, it say not found in http://localhost:8084/concerto-platform/admin i try to change http://localhost:80/concerto-platform/admin or http://localhost:8080/concerto-platform/admin and it still not found.. what i must change in corcento,, can u help me? thanks before..

**Comment by przemyslawlis** [comment]
Installation issue. See [docker-compose Installation guide](https://github.com/campsych/concerto-platform/wiki/docker-compose-Installation-guide) for new simpler and recommended installation method.
