### ISSUE TITLE
HTML audio player - limit the number of times audio can be played

### ISSUE THREAD

**Issue by uqswalk5** [campsych/concerto-platform#182]
I work in language testing and am using Concerto to develop a test of academic English ability for international students studying engineering in an English medium university. I am including English language **listening proficiency** in this assessment which involves the use of audio files in the assessment. 

I have hidden the player on the test pages and use the "auto play" setting to begin playing the audio automatically as soon as the page is loaded. The problem is this; Concerto has a setting which pops-up a ‘You must answer the question’ message if a test taker clicks on ‘Next’ without first answering the item. This is an important feature when the test is adaptive, as the test taker’s answer provides the difficulty parameter needed to select the next test item. However, the pop up also refreshes the page, and that causes the audio to play again! 
 
I want to keep the pop-up, but NOT allow the audio to play again. I have looked for a solution to this problem but cannot find an HTML audio player which allows me to control the number of times the audio can play. Anyone making language tests which involve testing listening ability will want to limit the number of times that a test taker can listen to the recorded audio (once only or twice only) so there must be a way of doing this. Do you have any suggestions?

Stephen

**Comment by przemyslawlis** [comment]
One of possible solution would be to not autoplay your audio, but play it only if it wasn't played before. 
You could have a array in javascript of audios already played, and check at the page load if the audio is already in the array, if it isn't - play it, if it is - don't do anything.
