### ISSUE TITLE
How to make multiple copies of an assessment with different names

### ISSUE THREAD

**Issue by uqswalk5** [campsych/concerto-platform#183]
I am building a CAT of English language ability. I need to pilot all the test items in 5 linear tests with shared anchor items in each test in order to calculate difficulty parameters for all test items.  I have built a working prototype linear test in concerto and now want to make 4 complete copies but with each copy having a different name. I will then use the copies to substitute different items to make up 5 complete linear tests to use in the piloting process. Is there an easy way to copy an entire test and then save it with a different name? I have tried exporting the test but have realised that when it is imported back into Concerto (with a different name) it replaces the original!

Stephen

**Comment by postview** [comment]
So you are on the right track. While exporting the experiment, export them as text files. Once exported you will see them as a JSON file. Open that in a text editor now search for the experiment name. You will find that in quotes besides the variable "name". Similarly you will find the experiment name also besides variable "sourcetestname". Don't change that. Just the "name" variable to something else. And then upload it back. So now you should have a second test.

**Comment by przemyslawlis** [comment]
In latest version (see [docker-compose Installation guide](https://github.com/campsych/concerto-platform/wiki/docker-compose-Installation-guide) for installation instructions), you can set names of imported objects before import.
