### ISSUE TITLE
Start Session Node

### ISSUE THREAD

**Issue by sakurasara** [campsych/concerto-platform#184]
Hi,
I'm a little confused with start session. I want my test taker to be able to resume the test and the test should be public registration. 

I hope someone can help me solve session node problem. I'm using Concerto v5.0.beta.2.186. 
This what I did :
1) Session - Session bank (default), Resume session (tick), resume time limit (0)
2) Authorization - Type (none chosen)
3) Registration - Enabled (untick)
4) Presentation - remain as default)
5) Connect Session Node with CAT node

a) Connect new session with IN from CAT
When run test : Error encountered. Execution halted.
error message : Error in .local(conn, statement, ...): could not run statement: Incorrect integer value: '' for column 'user_id' at row 1

b) Connect success with IN from CAT
When run test : Error encountered. Execution halted.
error message : Error in .local(conn, statement, ...): could not run statement: Incorrect integer value: '' for column 'user_id' at row 1

Both have same error. I followed issues#106. How can I resolve this?  @przemyslawlis  @NatashkaX 

I don't know how should I do to make the test resumable. Thanks

**Comment by przemyslawlis** [comment]
Since this is based on outdated version of both platform and starter content, can you try latest version ([docker-compose Installation guide](https://github.com/campsych/concerto-platform/wiki/docker-compose-Installation-guide)) and open a new issue request if you still have an issue?
