### ISSUE TITLE
feedback in CAT test

### ISSUE THREAD

**Issue by albamrt** [campsych/concerto-platform#185]
Hi, I am creating a language CAT test and in the end I would like it to return some feedback to the user. What I would like the test to print is the level of the person. For example: A1, for values of theta in [-3, -2); A2 for theta in [-2, -1), B1 for theta in [-1, 0), ... 

I am trying to use the feedback node but it does not print anything, it just shows a "continue" button. I think maybe my error would be that in the trait name to enter to the feedback node I have entered the CB_group from the item bank and this is not the correct thing to enter?

I enclose the flow from my test:
![imagen](https://user-images.githubusercontent.com/38278345/40373344-fdd689d2-5de6-11e8-8ef5-a63024db11ad.png)

**Comment by postview** [comment]
Hi don't use the feedback node. Rather use the info node. A detailed description is provided in video https://youtu.be/boFAkQcaoag The later part of the video provide a way to display the theta and SEM value obtained from that participant.

**Comment by albamrt** [comment]
I tried this in the beggining but as I don't want to print theta, but a transformation, I have tried using a R_code node before the info node. There, I have created a list:
results <- list()
And then created there the variable category:
results$category <- cut(arg1$theta, c(-3, -2, -1, 0, 1, 2, 3),  labels = c("A1", "A2", "B1", "B2", "C1", "C2"))
But then I don't know how to access and print the variable in the info node.

I've tried to follow https://github.com/campsych/concerto-platform/issues/107 but in the end it does not say how he solved it.

**Comment by albamrt** [comment]
I have finally been able to do it by changing the R code to:
result <- list(category = paste(cut(arg1$theta, c(-3,-2,-1,0,1,2,3), 
                labels = c("A1","A2","B1","B2","C1","C2"))))

And then printing the variable in the info node as:
Your level is:
{{category}}
