### ISSUE TITLE
No Default Files Present

### ISSUE THREAD

**Issue by Curifiq** [campsych/concerto-platform#187]
### Concerto Platform version
Latest. Installed Yesterday.

### Expected behavior
If I go through tutorial videos on your website, there are some default files and functions present.

### Actual behavior
In my Concerto server there are no default files. What to do?

**Comment by przemyslawlis** [comment]
What files and functions do you mean exactly?

**Comment by przemyslawlis** [comment]
See **Tips** section on how to install starter content from [AMI Installation Guide](https://github.com/campsych/concerto-platform/wiki/Concerto-Platform-AMI-launch-guide#tips).

AMI installation is no longer supported method of installing Concerto. Please see [docker-compose Installation Guide](https://github.com/campsych/concerto-platform/wiki/docker-compose-Installation-guide) for recommended method for installing latest version (including starter content).
