### ISSUE TITLE
Error at Docker Install

### ISSUE THREAD

**Issue by dagors** [campsych/concerto-platform#188]
### Concerto Platform version
I assume it's the latest version, I followed the steps that are in:
https://github.com/campsych/concerto-platform/wiki/docker-compose-Installation-guide

### Expected behavior
Complete the installation and perform tests

### Actual behavior
Error executing
docker-compose up --build -d
I get the following error
![imagen](https://user-images.githubusercontent.com/39383393/41262229-e5393350-6d9c-11e8-90ea-85ec4fe70f45.png)

### Steps to reproduce the issue
Clean installation of Debian 9 on Virtualbox
apt-get install docker
apt-get install docker-compose
apt-get install git
git clone https://github.com/campsych/concerto-platform /home/concerto
cd /home/concerto/docker-compose
docker-compose up --build -d

**Comment by bkielczewski** [comment]
This may happen when Docker running on the system is too old. Please make sure you've followed install guide on Docker [https://docs.docker.com/install/linux/docker-ce/debian/#install-docker-ce-1 <https://docs.docker.com/install/linux/docker-ce/debian/#install-docker-ce-1>]. Especially the part about adding custom repositories from Docker. Debian repositories that come with the system most likely contain some old version.

Best,
b.

**Comment by dagors** [comment]
I already updated Docker's version to Docker-CE stable, but I still get the same error.
![imagen](https://user-images.githubusercontent.com/39383393/41310145-eaf7f00a-6e3d-11e8-9b43-6aafc3278374.png)

**Comment by przemyslawlis** [comment]
What's your docker-compose version?

**Comment by dagors** [comment]
docker-compose ver.: 1.8.0-2

**Comment by bkielczewski** [comment]
That’s like 2016…  Please read the docs to get more recent one  -> https://docs.docker.com/compose/install/#install-compose <https://docs.docker.com/compose/install/#install-compose>
@Przemek: I think that should go to the wiki.

Best,
b.

**Comment by dagors** [comment]
Try installing it using
curl -L https://github.com/docker/compose/releases/download/1.21.2/docker-compose-$(uname-s)-$(uname -m) -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose

but he presented me with another error.

Remove docker-compose and install it with pip then it worked.

Thank you
