### ISSUE TITLE
Sample Concerto unavailable (broken link)

### ISSUE THREAD

**Issue by scottflowers** [campsych/concerto-platform#190]
### Concerto Platform version
unknown

### Expected behavior
view Discover Your Team Role sample Concerto

### Actual behavior
502 Bad Gateway Error

### Steps to reproduce the issue
Follow 'See Concerto In Action'/ 'Discover Your Team Role' link on https://www.psychometrics.cam.ac.uk/newconcerto

**Comment by przemyslawlis** [comment]
Thanks. It's back up again.
