### ISSUE TITLE
How do you back a concerto server up?

### ISSUE THREAD

**Issue by smcgrat** [campsych/concerto-platform#191]
Hi,

Not an issue as such.

How do you back a concerto server up? 

I have one deployed as per https://github.com/campsych/concerto-platform/wiki/docker-compose-Installation-guide and am doing a regular `mysqldump` of the database. Is that enough? So if I where to destroy the containers conerto is currently running in and spin new ones up, then import the database dump would all the same tests and users, etc, be on the new deployment?

Many thanks in advance.

Sean

**Comment by przemyslawlis** [comment]
Yes, that is correct. Database dump contain data of tests, templates, data tables, users, etc.
