### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by alydia** [campsych/concerto-platform#193]
We tried to install Concerto on windows 10, but it fails with the error message as shown below.
We have followed the installation guide from this link: https://github.com/campsych/concerto-platform/wiki/docker-compose-Installation-guide 

Would you kindly help us with this issue?

![1](https://user-images.githubusercontent.com/42195677/44014965-2aa3f43a-9f01-11e8-87bd-197239b94680.png)

**Comment by przemyslawlis** [comment]
Can you please paste output of both commands below?
`docker version`
`docker info`

**Comment by alydia** [comment]
**docker version**
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:05:28 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.24)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:23:19 2018
  OS/Arch:          windows/amd64
  Experimental:     false

**docker info**
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 18.06.0-ce
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 16299 (16299.15.amd64fre.rs3_release.170928-1534)
Operating System: Windows 10 Education Version 1709 (OS Build 16299.371)
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 7.425GiB
Name: NBK201500000469
ID: IJ7Z:ZHYB:AS2P:2LZV:TX6S:SVKT:REMP:USWP:S2BN:BZXV:63WY:GN5Q
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 34
 System Time: 2018-08-14T12:26:41.6592693+08:00
 EventsListeners: 2
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by przemyslawlis** [comment]
Is this reproducible all the time?
Can you try to stop any running containers from this docker-compose, remove them and their images and try to redownload everything one more time?

E.g. by going to ./docker-compose directory and doing:
<pre>docker-compose down
docker system prune -a --volumes
docker-compose up --build -d</pre>
**Make sure you know what does the last command do before you run it!**

**Comment by bkielczewski** [comment]
Is the docker set to run Linux containers or has it been switched to use Windows containers?

You can find more info here -> https://docs.docker.com/docker-for-windows/#explore-the-application

Search for “Switching between windows and Linux containers”

**Comment by alydia** [comment]
Thank you for the solution!
I have switched to linux and run this docker-compose up --build -d

However it ended up with an error message.
Would you kindly advise how to proceed from here?

Thank you.

![capture](https://user-images.githubusercontent.com/42195677/47078041-f710b600-d234-11e8-9d57-7baf1c8454f6.PNG)

**Comment by alydia** [comment]
Thank you @bkielczewskk! The localhost:8080 solution works wonder :)
