### ISSUE TITLE
Concerto installation error in the last step

### ISSUE THREAD

**Issue by diediamil** [campsych/concerto-platform#195]
### Concerto Platform version
I assume it's the lastest version because I followed the isntructions from the most recent guide.

### Expected behavior
Complete the installation

### Actual behavior
![image](https://user-images.githubusercontent.com/42700243/44620555-9dc08200-a896-11e8-9316-73d6e337fa0e.png)

### Steps to reproduce the issue
(It is running in Raspbian)
Install docker (v1.13 or newer)
Install docker-compose (v1.21 or newer)
Install git
git clone https://github.com/campsych/concerto-platform /concerto
cd /concerto/docker-compose
docker-compose up --build -d

**Comment by przemyslawlis** [comment]
Can you please paste output of both commands below?
`docker version`
`docker info`

**Comment by diediamil** [comment]
**docker version:**

Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:30:52 2018
 OS/Arch:           linux/arm
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:26:37 2018
  OS/Arch:          linux/arm
  Experimental:     false

**docker info**

Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.14.62-v7+
Operating System: Raspbian GNU/Linux 9 (stretch)
OSType: linux
Architecture: armv7l
CPUs: 4
Total Memory: 923.2MiB
Name: ddmpi
ID: EKMH:SXTY:P3LM:I4IC:CWDE:RO5Z:LUKD:AULC:ZLHW:PDZT:6KO7:QEIB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support

**Comment by przemyslawlis** [comment]
ARM architecture is not supported in current docker-compose file.
