### ISSUE TITLE
Center align multiple choice response options

### ISSUE THREAD

**Issue by jakekraska** [campsych/concerto-platform#196]
### Concerto Platform version
v5.0.beta.7.2

### Expected behavior
Centre the multiple choice response options

### Actual behavior
Left aligned

### Steps to reproduce the issue
Any sort of editing to "linear_test_content" template that I make does not seem to produce changes once running the test

### Further details
I have four response options for a linear test. I want them to be presented horizontally, and in the middle of the page, centred from the {{paragraph}} and {{question}} elements. Most of the methods of centering text and/or elements from https://www.w3schools.com/css/css_align.asp do not appear to work. Need advice on whether I need to place css code underneath which of the following:
- `.linear-test-response-table `
- `.linear-test-response-table td`
- `.linear-test-response-section-horizontal`
- `.linear-test-response-section-vertical`
- `.linear-test-response-group`
- `.linear-test-response-label-cell p`
- `.linear-test-response-button-cell`

I thought it would be "linear-test-response-table" as this seems to be the element that produces the actual output of the response text on the page, but either text align or using margins doesnt seem to work.

**Comment by przemyslawlis** [comment]
Look at the 
`<div>` 
element sorrounding 
`<table>` 
element in **linear_test_content** template. 
One of the solution would be to use CSS:
`float: left;` 
to position it horizontally. See https://www.w3schools.com/css/css_float.asp
