### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by lfausto** [campsych/concerto-platform#199]
### Concerto Platform version
Using docker-compose installation instructions in an Ubuntu VM on AWS

### Expected behavior
Able to access via http after the steps

### Actual behavior
It does not work, and after the docker-compose build command, it says the address in already in use. Tried to kill the process and rerun the installation steps, but the same error was thrown. Also tried to netstat, but there was only the session which was not working.

### Steps to reproduce the issue
![error](https://user-images.githubusercontent.com/43553920/45977338-a932d480-c01f-11e8-8e4d-49685d4cdb08.png)

**Comment by kazexd** [comment]
@lfausto 
do you have a local mysql in that vm listen to 3306?
i have met the same problem as yours.
the project wants to use the docker version mysql. ( i guess )
finally i can run that command by a stupid way( delete the mysql in local)
and after deleted, i have found that i can keep my local mysql... LOL

in the docker-compose folder, there is a file docker-compose.yml.
please change the port and run the command again, and you should run correctly.

**Comment by bkielczewski** [comment]
Yes, you always can try to change the port in docker-compose.yml if unable to free up existing ports on your system.
