### ISSUE TITLE
responsive design for run test?

### ISSUE THREAD

**Issue by johnfelipe** [campsych/concerto-platform#20]

**Comment by przemyslawlis** [comment]
Can you please be more specific what the issue is about?
Have you encountered any problems with default_layout template display on some screens?

**Comment by johnfelipe** [comment]
when i run test havent responsive design?

**Comment by przemyslawlis** [comment]
I might look into default_template CSS and add some device specific rules. Is there anything in particular that you think needs immediate attention?

**Comment by johnfelipe** [comment]
only will be great responsivator test page

**Comment by przemyslawlis** [comment]
On TODO. Closing.
