### ISSUE TITLE
R Error Message in Error Log

### ISSUE THREAD

**Issue by aboukhary** [campsych/concerto-platform#201]
v5.0.beta.2.171

One of the tests which has no errors generated the following R code error:

Error in if (!is.null(response$response) || response$isTimeout == "1") {: missing value where TRUE/FALSE needed

Can anyone help determining how this eeror message is generated so that we can work on resolving it?

**Comment by bkielczewski** [comment]
The evaluation of condition resulted in an NA. The if conditional must have either a TRUE or FALSE result. Probably something like response$isTimeout does not exist, so check docs of the extenstion you're using (guessing httr). This is OR condition meaning you would only see this error if the first condition was false and not for any other cases.

Note we don't provide support here in learning R language.
