### ISSUE TITLE
Failed to Save Template Updates

### ISSUE THREAD

**Issue by aboukhary** [campsych/concerto-platform#204]
I have a fresh installation of Concerto Docker Image v5.0.beta.7.4

I am making changes to templates, but the operation fails. I also noticed that small changes pass while updates with large amount of data is rejected!

The console shows the following message: Failed to load resource: the server responded with a status of 500 (Internal Server Error)

XHR failed loading: POST "http://mydomain.com/admin/ViewTemplate/22/save".
(anonymous) @ angular.js:11756
m @ angular.js:11517
g @ angular.js:11227
(anonymous) @ angular.js:15961
$eval @ angular.js:17229
$digest @ angular.js:17045
$apply @ angular.js:17337
(anonymous) @ angular.js:25023
dispatch @ jquery.js:4435
r.handle @ jquery.js:4121

I receive the message: Operation failed. Validate your data and try again.

It seems that I have some problem with access rights.

**Comment by przemyslawlis** [comment]
Check the source of response error status 500, by following guide here:
https://github.com/campsych/concerto-platform/wiki/Reporting-Issues#how-to-check-for-server-side-errors-in-chrome

Please paste your error description here.

**Comment by przemyslawlis** [comment]
No response. Closing.
Feel free to post your error description here and I'll reopen.
