### ISSUE TITLE
API requests issues

### ISSUE THREAD

**Issue by mounirlahsini** [campsych/concerto-platform#205]
### Concerto Platform version
I'm currently using the latest 
concerto platform version and Postman for API programming 
### Expected behavior
trying to get an json object after using an the API request
### Actual behavior
but i get this error 
Your test name | JSONError: Unexpected token '<' at 1:1 <!DOCTYPE html> ^
### Steps to reproduce the issue
GET http://localhost/admin#/api/data/requests
in Postman and following the Api request documentation

**Comment by bkielczewski** [comment]
The URL you're making the request to is clearly wrong. http://localhost/api/data/{table} not 
http://localhost/admin#/api/data/requests
