### ISSUE TITLE
Arabic or Hebrew Support in Concerto

### ISSUE THREAD

**Issue by aboukhary** [campsych/concerto-platform#206]
The new concerto doesn't seem to support Arabic/special characters. 

The receive the following error when Arabic characters are used:

`An exception occurred while executing 'INSERT INTO Table (id, question, order_index, response_options, trait) VALUES (?, ?, ?, ?, ?),(?, ?, ?, ?, ?),(?, ?, ?, ?, ?)' with params ["1", "
\u0627\u0646\u062a\u0627\u0646\u0627\u0633\u0627\u0633\u0627 \u0633\u0627\u0646\u0627\u0633\u0646\u0627\u0633 \u0633\u0627\u0646\u0627\u0633\u0646<\/p>\n", "1", "{\"response_type\":\"multiple_choice\",\"correct_answer\":\"\",\"response_options\":[{\"value\":\"tilt_back\",\"label\":\"Tilt your head back\",\"points\":\"0\"},{\"value\":\"tilt_forwards\",\"label\":\"Tilt your head forwards\",\"points\":\"0.5\"},{\"value\":\"tilt_forwards_pinch\",\"label\":\"Tilt your head forwards and pinch your nose\",\"points\":\"1\"}]}", "first_aid", "2", "

In first aid, ABC stands for what?<\/p>\n", "2", "{\"response_type\":\"multiple_choice\",\"correct_answer\":\"\",\"response_options\":[{\"value\":\"airway_breathing_circulation\",\"label\":\"Airway, breathing, circulation\",\"points\":\"1\"},{\"value\":\"alcoholic_beverage_control\",\"label\":\"Alcoholic Beverage Control\",\"points\":\"0\"}]}", "first_aid", "3", "

In CPR, how many chest compressions per minute should be performed?<\/p>\n", "3", "{\"response_type\":\"open_text\",\"correct_answer\":\"100\",\"response_options\":[]}", "first_aid"]: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'Table (id, question, order_index, response_options, trait) VALUES ('1', '

ا' at line 1`

Can you help solve the problem?

**Comment by aboukhary** [comment]
I found the bug .. It is not about the Arabic characters. It is about the restricted mySQL word "order". The import fails when a restricted word is used without quotation. 
I wonder if anybody else faced this bug?

**Comment by bkielczewski** [comment]
It's the characteristics of the SQL database that if you use keywords as names of the fields they need to be escaped. Better just not use them.
