### ISSUE TITLE
cannot able to access Concerto Platform administration panel by going to: http://localhost/admin

### ISSUE THREAD

**Issue by hassankhan345** [campsych/concerto-platform#207]
Successfully build the concerto platform on Windows 7, but cannot able to access admin panel by going to http://localhost/admin.
ERROR is : This site can’t be reached
                   localhost refused to connect

And when i try to run it through DOCKER TERMINAL, it gives me "
wait-for-it.sh: waiting 300 seconds for database:3306
wait-for-it.sh: timeout occurred after waiting 300 seconds for database:3306"

**Comment by bkielczewski** [comment]
The database is not starting or is not reachable for some reason. You should examine what do the logs say, i.e. via docker-compose logs.
