### ISSUE TITLE
Error while installing concerto on centos server

### ISSUE THREAD

**Issue by stevemakinitezy** [campsych/concerto-platform#208]
### Concerto Platform version
https://github.com/campsych/concerto-platform

### Expected behavior
docker-compose up --build -d while running this command build should take

### Actual behavior
Getting an error
Step 5/14 : COPY . /usr/src/concerto/
Error removing intermediate container 308a082da027: container 308a082da02794d186d572ee883cbb30d2149eaf2da30607dd8296ddf76f1e8f: driver "overlay2" failed to remove root filesystem: remove /var/lib/docker/overlay2/c0a4f20ad070d7a7877bb80f81270697cc3dc615661140f3e821d2d09479da0f/merged: device or resource busy

Step 6/14 : COPY build/php.ini /usr/local/etc/php/php.ini
ERROR: Service 'web' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder344547331/build/php.ini: no such file or directory

### Steps to reproduce the issue
Install docker, docker compose ,Install git
Start up Concerto Platform docker-compose:

cd /concerto/docker-compose
docker-compose up --build -d
while running this command getting the error.

**Comment by bkielczewski** [comment]
Since this is more like Docker vs CentOS issue, googling could help. For example: https://www.bountysource.com/issues/33241128-unable-to-remove-a-stopped-container-device-or-resource-busy
