### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by donnekgit** [campsych/concerto-platform#209]
This is not an "issue" so much as some feedback after poking about in Concerto for a couple of hours.  This is a really interesting project, and I'd love to see it develop.  I'm running it on a new Ubuntu 18.04 install, using Google Chrome 70 as the browser.

(1) Accessing Concerto.
I installed Concerto using the following steps:
```
sudo apt-get install docker
sudo apt-get install docker-compose
git clone https://github.com/campsych/concerto-platform /concerto
cd /concerto/docker-compose
sudo usermod -aG docker myuser
sudo service docker start
docker-compose up --build -d
sudo service apache2 stop
```

Then I went to http://localhost/admin to login with admin/admin.  Stopping my existing Apache2 install was necessary (hence the last line above), because editing `docker-compose.yml` to adjust the ports entry to:
```
      ports:
        - "8080:8080"
```
before composing didn't work - I got no admin interface at `localhost:8080`.  I also found that even getting it at `localhost` was only possible if cache was cleared.  Some guidance on running Concerto alongside an existing server would be useful - I'm not really up to speed on Docker and how to configure that.

(2) Interface.
The workflow interface is very attractive, but the label on the green buttons when you dive into it should perhaps read `Save` instead of `Change`.  If I save without changing entries for any of the fields, strictly speaking I'm not changing anything.

Clicking outside the field entry forms dismisses them.  This should perhaps be disabled, so that you have to actually save each form.  Some forms go 4 levels deep, and if you click `Change` for the first 3, but accidentally click outside the 4th (perhaps because it's shorter onscreen), you lose all the changes made in the other 3.

(3) Form node.
My main interest is whether Concerto can be used for social psychology questionnaires, and I've assumed that the form node is the one for that.  I had some odd behaviour when adjusting the gender entry.  I added entries for `transgender`, `binary`, `other`, and `prefer not to say`.  Deleting the existing `none` entry also deleted `transgender`, and produced two  `prefer not to say`s.  Deleting and re-entering all of them worked.

Adding further questions also worked well, but there seems to be no way to adjust order.  For instance, if I want to move `email` above `gender`, is that possible?  Perhaps by adjusting something in the source, but how do you do that?  The same point applies to adding a single-line field to allow the user to enter a specific gender if they selected the previous drop-down entry `Other (please specify)`.

(4) Questionnaire node.
I'm assuming that if I have a set of form questions that then move into a set of related `often`, `sometimes`, `rarely`, `never` questions I just add a questionnaire node after the form node.  But can the questionnaire node currently deal with repeating these over two related segments in each question, eg:
`Being nasty or rude to family and friends: Before the event (often, sometimes, rarely, never), After the event (often, sometimes, rarely, never)`
or is it necessary to do this in two questions:
```
Being nasty or rude to family and friends before the event (often, sometimes, rarely, never)
Being nasty or rude to family and friends after the event (often, sometimes, rarely, never)
```

Again, very promising software!

**Comment by bkielczewski** [comment]
Thanks for your feedback. About installation issue - the port mapping to get it listen on 8080 should be:

ports:
        - "8080:80"

You could learn more about Docker and Docker Compose from their documentation. Some knowledge is always necessary to fix environment-specific problems.
