### ISSUE TITLE
How to capture the value of theta and the SEM to each item answered

### ISSUE THREAD

**Issue by ghnunes** [campsych/concerto-platform#210]
### Concerto Platform version: v5.0.beta.7.4

Hello, is there any way to capture the value of theta and the SEM with each test response item? I was able to capture these values ​​only at the end of the test. Thanks in advance.

**Comment by davidstillwell** [comment]
The cat table in the data tables tab stores the theta and SEM after each time the user answers a question. Is it OK to download from there?
