### ISSUE TITLE
Installation issue on Windows 10 Home using docker toolbox

### ISSUE THREAD

**Issue by coreankim** [campsych/concerto-platform#211]
### Concerto Platform version
Latest version, on Windows 10 Home using docker toolbox

### Expected behavior
Proper installation

### Actual behavior
Almost everything else is installed, but when I type in docker-compose up --build -d, it produces an OCI runtime error:

Cannot start service concerto: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/c/concerto/docker-compose/concerto/nginx/nginx.conf\\\" to rootfs \\\"/mnt/sda1/var/lib/docker/overlay2/e973408c4164c862843c93d556ce3ca26f28945b64ef44f626d489011f78fb05/merged\\\" at \\\"/mnt/sda1/var/lib/docker/overlay2/e973408c4164c862843c93d556ce3ca26f28945b64ef44f626d489011f78fb05/merged/etc/nginx/nginx.conf\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

### Steps to reproduce the issue
Installing on the docker powershell

**Comment by alpersahin2** [comment]
Hello Coreankim. It seems like you are successful in getting over all the problems encountered while installing Concerto. 

I am getting "readlink /var/lib/docker/overlay2: invalid argument" error message after I type  "docker-compose up --build -d" command to Git Bash. Concerto was mostly installed. I saw steps done on screen. This error message came out in the last step I guess and the installation was terminated. 

Have you experienced such a problem so far?

**Comment by bkielczewski** [comment]
For this sort of issues it's good to google around, because it's related to docker/docker-compose. I.e. see the comments in https://github.com/docker/for-mac/issues/1667 for 
"readlink /var/lib/docker/overlay2: invalid argument"
