### ISSUE TITLE
Error encountered. Execution halted" error while running a test a test with more than 4 questions in the questionnaire node

### ISSUE THREAD

**Issue by salmasarah** [campsych/concerto-platform#214]
### Concerto Platform version

v5.0.beta.7.4

### Expected behavior
Tests complete successfully with more than 5 questions.

### Actual behavior
I've created a test with 5-item questionnaire with 4 response options for each item . Previously when I was working with a similar test with 4-item question option, it was working. After adding another additional question (a 5th one), I am getting an error message. This error is displaying in the Test's logs:
Error in rbind(deparse.level, ...): numbers of columns of arguments do not match

Here is the error message from the JavaScript console when I run the test in debug mode:

[1] "SELECT id,  AS question,  AS trait,  AS reversed_score FROM  WHERE  = '' ORDER BY  ASC"
[1] "[2019-02-04 19:31:56.507653]:"
<simpleError in .local(conn, statement, ...): could not run statement: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AS question,  AS trait,  AS reversed_score FROM  WHERE  = '' ORDER BY  ASC' at line 1>
[1] "[2019-02-04 19:31:56.508106]:"
[1] "stopping session..."
[1] "[2019-02-04 19:31:56.508288]:"
[1] "status: 3"
[1] "[2019-02-04 19:31:56.508568]:"
[1] "updating session..."
[1] "[2019-02-04 19:31:56.512054]:"
[1] "responding to server..."
[1] "[2019-02-04 19:31:56.523878]:"
[1] "responded to server"

### Steps to reproduce the issue
The error occurs no matter how many times we retry it when we try to add more than 4 questions.

**Comment by davidstillwell** [comment]
It's most likely something wrong with the new question response options. Can you save your questionnaire item bank as csv and post it here so we can see it?

**Comment by salmasarah** [comment]
Here I am posting my item bank with 5 elements in the questionnaire node. Uploading a word file as csv was not allowed.

[Demo_test.docx](https://github.com/campsych/concerto-platform/files/2845684/Demo_test.docx)

**Comment by salmasarah** [comment]
Hi, 
I am again following up on the issue I have mentioned earlier (not being able to add more than 4 elements in the item bank of questionnaire node). Here is a screenshot about how my test should look like:
![image](https://user-images.githubusercontent.com/47091403/53362887-31880f00-3909-11e9-9829-58598f448ca3.png)
In my previous comment I have uploaded how my data table is looking. 
Thanks!

**Comment by przemyslawlis** [comment]
Closing this issue, as problematic questionnaire node above is no longer part of latest Concerto version, and as a result it's no longer supported.
