### ISSUE TITLE
Concerto issues on Ubuntu 18.04

### ISSUE THREAD

**Issue by monicobr** [campsych/concerto-platform#215]
### Concerto Platform version
Successfully tagged campsych/concerto-platform:latest

### Expected behavior
Concerto plataform works

### Actual behavior
Concerto plataform doesn't work

### Steps to reproduce the issue

Docker version 18.09.1, build 4c52b90
docker-compose version 1.23.2, build 1110ad01

Installation procedure of Concerto

Successfully tagged campsych/concerto-platform:latest
Starting database                ... error

ERROR: for database  Cannot start service database: driver failed programming external connectivity on endpoint database (44ebaf7a376e2aee39a22dd254682bca46189ffe371a21790f308ea9a7f46570): Error starting userland proxyRecreating dc8cca21a375_concerto ... error

ERROR: for concerto  Cannot start service concerto: driver failed programming external connectivity on endpoint concerto (e9bc92d72bf51e2d336d4ceeade5057076f141d39f8cffad9af2c2502679cb0d): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use

**Comment by bkielczewski** [comment]
It tells you something is already using port 80 and it cannot listen on it. You could change the port Concerto is using to a different one, i.e. 8080. Port mappings are in concerto-docker.yml file. Alternatively, identify what has taken port 80 and shut it down.
