### ISSUE TITLE
How can I generate a test weblink?

### ISSUE THREAD

**Issue by ChrisT448** [campsych/concerto-platform#216]
Hi, I am new to concerto platform. I have created a test and want to generate a weblink so that participants can run the test on their computers through it (like this one: https://planning.e-psychometrics.com/test/cat-demo). How can I generate such a weblink?
Thanks in advance!

**Comment by bkielczewski** [comment]
This is something that requires knowledge about hosting public web applications and domain name service. It's not related to Concerto itself. I'd recommend seeking advice from IT professional, i.e. from a hosting company of your choice.
