### ISSUE TITLE
Using Bootstrap classes in Concerto

### ISSUE THREAD

**Issue by meg110** [campsych/concerto-platform#223]
Using concerto v5.0.beta.7.4

I've read that Bootstrap (and other libraries) are built-in to Concerto and can be used for styling, but am unable to figure out how to do so. 
Could someone please give the steps needed to use Bootstrap within Concerto?

**Comment by przemyslawlis** [comment]
Bootstrap is not available 'out of the box' in Concerto templates context.
You would have to load it yourself in the template where you plan to use it.
