### ISSUE TITLE
Linux Installation

### ISSUE THREAD

**Issue by aboukhary** [campsych/concerto-platform#228]
I am trying to install the latest image of concerto using the standard linux procedure and prefer to use a static installation - and avoid docker. 

The process seems to fail at the last stage with the command 
R CMD INSTALL concerto5

Output
`Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'dbEscapeStrings'
Note: no visible binding for '<<-' assignment to 'dbSendStatement'
Note: no visible binding for '<<-' assignment to 'SOURCE_PROCESS'
Note: no visible binding for '<<-' assignment to 'SOURCE_SERVER'
Note: no visible binding for '<<-' assignment to 'RESPONSE_VIEW_TEMPLATE'
Note: no visible binding for '<<-' assignment to 'RESPONSE_FINISHED'
Note: no visible binding for '<<-' assignment to 'RESPONSE_SUBMIT'
Note: no visible binding for '<<-' assignment to 'RESPONSE_STOP'
Note: no visible binding for '<<-' assignment to 'RESPONSE_STOPPED'
Note: no visible binding for '<<-' assignment to 'RESPONSE_VIEW_FINAL_TEMPLATE'
Note: no visible binding for '<<-' assignment to 'RESPONSE_KEEPALIVE_CHECKIN'
Note: no visible binding for '<<-' assignment to 'RESPONSE_UNRESUMABLE'
Note: no visible binding for '<<-' assignment to 'RESPONSE_WORKER'
Note: no visible binding for '<<-' assignment to 'RESPONSE_ERROR'
Note: no visible binding for '<<-' assignment to 'STATUS_RUNNING'
Note: no visible binding for '<<-' assignment to 'STATUS_STOPPED'
Note: no visible binding for '<<-' assignment to 'STATUS_FINALIZED'
Note: no visible binding for '<<-' assignment to 'STATUS_ERROR'
Note: no visible binding for '<<-' assignment to 'RUNNER_PERSISTENT'
Note: no visible binding for '<<-' assignment to 'RUNNER_SERIALIZED'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
`

Any suggestions on what went wrong?

**Comment by przemyslawlis** [comment]
Can you please paste your OS info and R version?

**Comment by aboukhary** [comment]
I am using Debian 9.4 and R version 3.3.3

**Comment by przemyslawlis** [comment]
Can you please paste full output containing reported failure message? Output above doesn't contain any error and can be ignored.

**Comment by aboukhary** [comment]
`* installing to library ‘/usr/local/lib/R/site-library’
* installing *source* package ‘concerto5’ ...
** R
** byte-compile and prepare package for lazy loading
Note: no visible binding for '<<-' assignment to 'dbEscapeStrings'
Note: no visible binding for '<<-' assignment to 'dbSendStatement'
Note: no visible binding for '<<-' assignment to 'SOURCE_PROCESS'
Note: no visible binding for '<<-' assignment to 'SOURCE_SERVER'
Note: no visible binding for '<<-' assignment to 'RESPONSE_VIEW_TEMPLATE'
Note: no visible binding for '<<-' assignment to 'RESPONSE_FINISHED'
Note: no visible binding for '<<-' assignment to 'RESPONSE_SUBMIT'
Note: no visible binding for '<<-' assignment to 'RESPONSE_STOP'
Note: no visible binding for '<<-' assignment to 'RESPONSE_STOPPED'
Note: no visible binding for '<<-' assignment to 'RESPONSE_VIEW_FINAL_TEMPLATE'
Note: no visible binding for '<<-' assignment to 'RESPONSE_KEEPALIVE_CHECKIN'
Note: no visible binding for '<<-' assignment to 'RESPONSE_UNRESUMABLE'
Note: no visible binding for '<<-' assignment to 'RESPONSE_WORKER'
Note: no visible binding for '<<-' assignment to 'RESPONSE_ERROR'
Note: no visible binding for '<<-' assignment to 'STATUS_RUNNING'
Note: no visible binding for '<<-' assignment to 'STATUS_STOPPED'
Note: no visible binding for '<<-' assignment to 'STATUS_FINALIZED'
Note: no visible binding for '<<-' assignment to 'STATUS_ERROR'
Note: no visible binding for '<<-' assignment to 'RUNNER_PERSISTENT'
Note: no visible binding for '<<-' assignment to 'RUNNER_SERIALIZED'
Note: no visible binding for '<<-' assignment to 'RUNNER_CHECKPOINT'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
Note: no visible binding for '<<-' assignment to 'concerto'
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (concerto5)`

**Comment by przemyslawlis** [comment]
This output indicates that the package installation have been completed successfully. Closing.
