### ISSUE TITLE
Starter Content Problem

### ISSUE THREAD

**Issue by aboukhary** [campsych/concerto-platform#229]
### Concerto Platform version
v5.0.beta.10.1
### Expected behavior
I made a docker image installation in the standard way. The starter content was supposed to be included, such as feedback, save data, questionnaire node, etc. 

### Actual behavior
The system seems to be missing the starter content. 
![image](https://user-images.githubusercontent.com/17113039/58570542-7426f380-8238-11e9-8381-f8b10e6a5a39.png)

**Comment by przemyslawlis** [comment]
Nodes you mentioned are no longer part of new starter content (which you can see on your screenshot).
Everything what mentioned nodes did can be done in new starter content. Documentation will follow soon.

**Comment by aboukhary** [comment]
I am not yet able to use the new starter content until the documentation is provided. 

Can you advise on how we can import the old starter content to the new beta.10 release?

or alternatively:

Can you advise on how to make an installation from an old release like beta.7?

The easier option is definitely preferred.
