### ISSUE TITLE
Manual Installation

### ISSUE THREAD

**Issue by aboukhary** [campsych/concerto-platform#230]
I am trying to install a static image of concerto on Linux debian version 9.7 

I managed to build concerto5 package successfully. 

Now it seems that there is a small problem with console file. 

The command 

` php bin/console concerto:setup`

Generates the following error:

`PHP Warning:  require(/var/www/vhosts/app/concerto/bin/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/vhosts/app/concerto/bin/console on line 15
PHP Fatal error:  require(): Failed opening required '/var/www/vhosts/app/concerto/bin/../vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/vhosts/app/concerto/bin/console on line 15`

Anyone could help with that?

**Comment by przemyslawlis** [comment]
For all manual installation steps check: 
https://github.com/campsych/concerto-platform/blob/master/.travis.yml
https://github.com/campsych/concerto-platform/blob/master/Dockerfile

Your error is shown because you didn't run:
`compose install`
