### ISSUE TITLE
Backward Compatibility 

### ISSUE THREAD

**Issue by aboukhary** [campsych/concerto-platform#231]
Regarding backward compatibility, I wonder if you could provide a short guide on how an installation could be made of an earlier release such as concerto5.0.beta.7 or concerto5.0.beta.8 using your docker installation. 

I also wonder if there you have particular recommendation to bring old content from concerto5.0.beta.7 to the latest release concerto5.0.beta.10.1. 

The reason for this question is that I have a lot of content that needs to be used urgently, but I dont have the time or resources to rebuild everything on the new platform. 

Please advise urgently.

**Comment by cvelozo** [comment]
My understanding is that Concerto 5.0 beta 10 is at a relatively early stage of complete re-programming.  You'll notice that beta 10.1 does not have many of the options as does the beta 7.0 for example polyCAT.

**Comment by przemyslawlis** [comment]
You can checkout appropriate branch (e.g. 5.0.beta.8) and you should have `./docker-compose/docker-compose.yml' file in your source which you can use to start it up.
