### ISSUE TITLE
Concerto tutorial for the latest version v5

### ISSUE THREAD

**Issue by Jibinpg** [campsych/concerto-platform#233]
### Concerto Platform version
Conserto v5 beta 

### Issue
I have installed Concerto v5 beta version in Ubuntu 16.04 and tried with creating sample CAT test as per the examples. But, all the wiki pages has shown create_template_definition as the first node. It has been written in issue #224 that the tutorial is outdated. `create_template_definition` is no longer part of starter.

No other docs or videos are there to start with Concerto. It is difficult to find a start thread for new Concerto user as the video tutorials are outdated and the wiki pages are incomplete. 

Please help me to start with Concerto.
Thanks ion advance

**Comment by eriam** [comment]
Hello @Jibinpg 

In the changelog.yml I found the following mention:"merged questionnaire with linear test" !

That should help you get started !

Cheers

**Comment by tony-krnl** [comment]
Could some or all of the sample tests from [this page](https://discovermyprofile.com/tag/Concerto) be put somewhere in an importable form?

Same for the design examples [here](https://concertoplatform.com/features). That would be tremendously helpful!

**Comment by vesspopov** [comment]
Hi all, thanks for the feedback and sorry that it has taken us a while to update the documentation. We are working on it, and there are many tutorials already available and up to date for 5.0.x. Regarding tony-bcl's request, we're very keen on having importable tests, but the ones on discovermyprofile are proprietary and the design examples on our website are just CSS examples (not in themselves concerto tests). We will continue to encourage Concerto users to open source their tests and share them as nodes for the rest of the community to work with. Thanks.
