### ISSUE TITLE
Duplicate test start nodes

### ISSUE THREAD

**Issue by meg110** [campsych/concerto-platform#234]
### Concerto Platform version
v5.0.beta.7.4

### Expected behavior
One 'test start' node and one 'test end' node per survey instrument.

### Actual behavior
Survey instrument is duplicating 'test start' and 'test end' nodes; unable to delete the duplicates. When the test is run, it will choose a different/duplicate 'test start' node rather than using the original one (which in most cases has been customized for the specific instrument (thus breaking the test). 
![UNSTABLE node](https://user-images.githubusercontent.com/49766499/58806016-40a2eb00-85e3-11e9-835f-788dcccc5751.png)

### Steps to reproduce the issue
Don't know how to reproduce it, as we don't know what is causing the issue. Screenshot attached to show additional start and end nodes.

**Comment by zrfrere** [comment]
To add to this post, I found that this behavior can be created when using the "Copy" button on a test that utilizes the above test as a subtest.  

The result is an overall duplication of each of the test nodes of the subtest such as the one above (including the start and end nodes, which the user cannot remove in the GUI).

**Comment by przemyslawlis** [comment]
>To add to this post, I found that this behavior can be created when using the "Copy" button on a test that utilizes the above test as a subtest.

That is correct observation. This bug is fixed since: a9593c74a3b4538b70176ae5372b2a5a4021263d
