### ISSUE TITLE
Docker Installation of Previous Releases Keeps Restarting

### ISSUE THREAD

**Issue by aboukhary** [campsych/concerto-platform#235]
### Concerto Platform version
concerto5.0.beta.8 and concerto5.0.beta.7 

### Expected behavior
The docker image for both releases doesn't work properly. 

### Actual behavior
The server keep restarting. 
When the log command is used 
`docker logs --tail 50 --follow --timestamps concerto`
Docker log file shows the following error:
`2019-06-04T00:43:46.804373224Z concerto setup (dev)
2019-06-04T00:43:46.804857748Z updating database...
2019-06-04T00:43:46.861081297Z
2019-06-04T00:43:46.862080250Z In AbstractMySQLDriver.php line 103:
2019-06-04T00:43:46.862434707Z
2019-06-04T00:43:46.862731635Z   An exception occured in driver: SQLSTATE[HY000] [2002] Connection refused
2019-06-04T00:43:46.863030752Z
2019-06-04T00:43:46.863272140Z
2019-06-04T00:43:46.863750529Z In PDOConnection.php line 47:
2019-06-04T00:43:46.864045993Z
2019-06-04T00:43:46.864367244Z   SQLSTATE[HY000] [2002] Connection refused
2019-06-04T00:43:46.864634509Z
2019-06-04T00:43:46.864848962Z
2019-06-04T00:43:46.865302630Z In PDOConnection.php line 43:
2019-06-04T00:43:46.865575656Z
2019-06-04T00:43:46.865831643Z   SQLSTATE[HY000] [2002] Connection refused
2019-06-04T00:43:46.866094710Z
2019-06-04T00:43:46.866294898Z
2019-06-04T00:43:46.866662965Z concerto:setup [--admin-pass ADMIN-PASS] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>
2019-06-04T00:43:46.866913606Z
`

### Steps to reproduce the issue
Try to install beta.8 or beta.7; yet the docker image of beta.9 and beta.10 is working fine.

**Comment by SandeepNadella** [comment]
Could setup beta 9 and beta 10 but they have this https://github.com/campsych/concerto-platform/issues/240 issue. So trying to setup beta 7 and check but I keep getting this error. Any known workaround?

➜  concerto-platform git:(5.0.beta.7) ✗ docker-compose -f docker-compose/docker-compose.yml up
Creating network "docker-compose_default" with the default driver
Creating concerto ... done
Creating database ... done
Attaching to database, concerto
concerto    | wait-for-it.sh: waiting 300 seconds for database:3306
database    | 2019-06-30T04:49:11.941326Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
database    | 2019-06-30T04:49:11.941371Z 0 [Warning] 'NO_AUTO_CREATE_USER' sql mode was not set.
database    | 2019-06-30T04:49:11.946507Z 0 [Note] mysqld (mysqld 5.7.26) starting as process 1 ...
database    | 2019-06-30T04:49:11.953199Z 0 [Note] InnoDB: PUNCH HOLE support available
database    | 2019-06-30T04:49:11.953234Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
database    | 2019-06-30T04:49:11.953238Z 0 [Note] InnoDB: Uses event mutexes
database    | 2019-06-30T04:49:11.953240Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
database    | 2019-06-30T04:49:11.953242Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
database    | 2019-06-30T04:49:11.953244Z 0 [Note] InnoDB: Using Linux native AIO
database    | 2019-06-30T04:49:11.953634Z 0 [Note] InnoDB: Number of pools: 1
database    | 2019-06-30T04:49:11.953874Z 0 [Note] InnoDB: Using CPU crc32 instructions
database    | 2019-06-30T04:49:11.954981Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
database    | 2019-06-30T04:49:11.961674Z 0 [Note] InnoDB: Completed initialization of buffer pool
database    | 2019-06-30T04:49:11.963581Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
database    | 2019-06-30T04:49:12.000362Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
database    | 2019-06-30T04:49:12.013550Z 0 [Note] InnoDB: Log scan progressed past the checkpoint lsn 12364221
database    | 2019-06-30T04:49:12.013590Z 0 [Note] InnoDB: Doing recovery: scanned up to log sequence number 12364230
database    | 2019-06-30T04:49:12.013595Z 0 [Note] InnoDB: Database was not shutdown normally!
database    | 2019-06-30T04:49:12.013598Z 0 [Note] InnoDB: Starting crash recovery.
database    | 2019-06-30T04:49:12.295818Z 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
database    | 2019-06-30T04:49:12.295920Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
database    | 2019-06-30T04:49:12.297904Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
database    | 2019-06-30T04:49:12.371927Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
database    | 2019-06-30T04:49:12.375145Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
database    | 2019-06-30T04:49:12.375192Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
database    | 2019-06-30T04:49:12.375633Z 0 [Note] InnoDB: Waiting for purge to start
database    | 2019-06-30T04:49:12.426274Z 0 [Note] InnoDB: 5.7.26 started; log sequence number 12364230
database    | 2019-06-30T04:49:12.426919Z 0 [Note] Plugin 'FEDERATED' is disabled.
database    | 2019-06-30T04:49:12.428032Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
database    | 2019-06-30T04:49:12.462755Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
database    | 2019-06-30T04:49:12.470154Z 0 [Warning] CA certificate ca.pem is self signed.
database    | 2019-06-30T04:49:12.471436Z 0 [Note] InnoDB: Buffer pool(s) load completed at 190630  5:49:12
database    | 2019-06-30T04:49:12.471944Z 0 [Note] Server hostname (bind-address): '*'; port: 3306
database    | 2019-06-30T04:49:12.471998Z 0 [Note] IPv6 is available.
database    | 2019-06-30T04:49:12.472007Z 0 [Note]   - '::' resolves to '::';
database    | 2019-06-30T04:49:12.472017Z 0 [Note] Server socket created on IP: '::'.
database    | 2019-06-30T04:49:12.473731Z 0 [Warning] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
database    | 2019-06-30T04:49:12.632728Z 0 [Note] Event Scheduler: Loaded 0 events
database    | 2019-06-30T04:49:12.632977Z 0 [Note] mysqld: ready for connections.
database    | Version: '5.7.26'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
database    | 2019-06-30T04:49:13.085276Z 2 [Note] Got an error reading communication packets
concerto    | wait-for-it.sh: database:3306 is available after 2 seconds
concerto    | concerto setup (dev)
concerto    | updating database...
concerto    |
concerto    | In AbstractMySQLDriver.php line 93:
concerto    |
concerto    |   An exception occurred in driver: SQLSTATE[HY000] [2002] No such file or dir
concerto    |   ectory
concerto    |
concerto    |
concerto    | In PDOConnection.php line 31:
concerto    |
concerto    |   SQLSTATE[HY000] [2002] No such file or directory
concerto    |
concerto    |
concerto    | In PDOConnection.php line 27:
concerto    |
concerto    |   SQLSTATE[HY000] [2002] No such file or directory
concerto    |
concerto    |
concerto    | concerto:setup [--admin-pass ADMIN-PASS] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>
concerto    |
database    | 2019-06-30T04:49:16.837331Z 3 [Note] Got an error reading communication packets
concerto    | concerto setup (dev)
concerto    | updating database...
concerto    |
concerto    | In AbstractMySQLDriver.php line 93:
concerto    |
concerto    |   An exception occurred in driver: SQLSTATE[HY000] [2002] No such file or dir
concerto    |   ectory
concerto    |
concerto    |
concerto    | In PDOConnection.php line 31:
concerto    |
concerto    |   SQLSTATE[HY000] [2002] No such file or directory
concerto    |
concerto    |
concerto    | In PDOConnection.php line 27:
concerto    |
concerto    |   SQLSTATE[HY000] [2002] No such file or directory
concerto    |
concerto    |
concerto    | concerto:setup [--admin-pass ADMIN-PASS] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>
concerto    |
concerto exited with code 1
