### ISSUE TITLE
File upload failed! uploading JSON files into Concerto

### ISSUE THREAD

**Issue by zrfrere** [campsych/concerto-platform#236]
### Concerto Platform version
v5.0.beta.7.4

### Expected behavior
Upload a Concerto test from a JSON file into Concerto

### Actual behavior
File upload failed! is displayed on to the User. 

### Steps to reproduce the issue
This issue seems to be displayed with JSONs of larger size.  These JSONs have not been modified.  JSON files can be exported out of Concerto to a desktop computer then immediately uploaded and receive this error.  These JSON files are of Concerto tests, which run without any issue.

**Comment by aboukhary** [comment]
Try to look at the php.ini parameters: upload_max_filesize  and post_max_size.

**Comment by zrfrere** [comment]
This worked for me thanks
