### ISSUE TITLE
Why is Template Definition Node Missing from my Test Flow? I can not find key node for my flowchart

### ISSUE THREAD

**Issue by kingstarr** [campsych/concerto-platform#237]
### Concerto Platform version
 v5.0.beta.10.1

### Expected behavior
Test Flow should include template definition, questionnaire node et al.

### Actual behavior
Some nodes are missing: template definition node, questionaire node et al.
 v5.0.beta.10.1's Test Flow now include a few new nodes like dataManipulation node, nestedPageHtml node, showPage node, translationDictionary node etc

### Steps to reproduce the issue
Install Concerto  v5.0.beta.10.1

**Comment by cvelozo** [comment]
My understanding is that beta 10.1 is at the early stages of a complete re-programming of Concerto-platform.

**Comment by kingstarr** [comment]
Kindly tell me, how do I find and install the stable version?

**Comment by aboukhary** [comment]
Having installed all 7,8,9 and 10 releases in a single week, I believe that version 7 is the most stable and complete version. 

It also seems that the team is working hard to bring version 10 content online as soon as they can. I have seen a lot of added components over the week, which suggests that version 10 components will be completed soon. Yet, I think that there will be some bugs to be fixed as my initial test suggests. 

So, my personal recommendation is version 7.

**Comment by przemyslawlis** [comment]
`create_template_definition` node is no longer part of starter content in latest version. Whatever you did earlier using this node, can now be made using `nestedPageHtml` with more flexibility.
