### ISSUE TITLE
Concerto install on Windows

### ISSUE THREAD

**Issue by j-pillon** [campsych/concerto-platform#24]
Hi,

I just see a tutorial and an installer for Windows is for 6 days, but here's my feedback anyway. Indeed, some constraints are taken into account due to the technical architecture of my compagny. I have to use a development station with admin rights but without internet connection and an internet station without admin rights.

My platforms:

1) Dev station
**No internet connection** :-(
**Admin rights**
OS : Windows 7 sp1
Apache HTTP: 2.4.18 x64 (from [](http://www.apachelounge.com)) + mod_rewrite enabled
PHP: 5.6.5 x64  (from [](http://windows.php.net)) + json, ctype, ACPU (because Symfony look for it) extensions enabled (no POSIX for Windows), date.timezone set
MySQL: 5.7.11 x64 (from[]( http://dev.mysql.com))
R: 3.3.1 (x64/x86) + rjson 0.2.15, RMySQL 0.10.9, DBI 0.4.1, session 1.0.3, catR 3.8, digest 0.6.9, ggplot2 2.1.0 (from https://mirror.ibcp.fr/pub/CRAN/index.html and https://mirror.ibcp.fr/pub/CRAN/bin/windows/contrib/3.3/)
Web browser: Mozilla Firefox 45 ESR / Google Chrome 52

2) Internet station
**Internet connection** (necessarily)
**No admin rights** (so many portable apps)
OS: Windows 7 sp1
PHP: 5.6.23 (XAMPP version - no install package needed in my case) (from https://sourceforge.net/projects/xampp/files/XAMPP%20Windows/5.6.23/)
R: 3.3.1 (x64/x86) + rjson 0.2.15, RMySQL 0.10.9, DBI 0.4.1, session 1.0.3, catR 3.8, digest 0.6.9, ggplot2 2.1.0 (from https://mirror.ibcp.fr/pub/CRAN/index.html and https://mirror.ibcp.fr/pub/CRAN/bin/windows/contrib/3.3/)
Git: 2.9.2 (x64) (from https://git-scm.com/download/win)
Node+NPM: 6.3.1 (x64) (from http://nodejs.org/dist/lastest-v6.x/)

Before concerto install on internet station:
	- If not, set Environment variables for Git (<install_path_git>\cmd), PHP (<install_path_xampp>\php), R (<install_path_R>\bin), Node.js/NPM/Bower (<install_path_node>\)
	
	
Concerto downloading package on internet station (follow the steps of Linux tutorial) :
(*) no changes from Linux tutorial

1) Cloning git repository (*):
`git clone https://github.com/campsych/concerto-platform.git`

2) Set up your vhost (* on dev station)

3) Edit configuration files (* with infos from dev station)

4) Install PHP dependencies
- install composer
download lastest composer.phar  (https://getcomposer.org/download/ "Manual download" parts) and copy it in "concerto-platform" root folder
- install PHP dependencies (*)
```
cd <path_to_concerto-platform>
php -dmemory_limit=1G composer.phar install --prefer-source --no-interaction
```

5) Install JS dependencies
- install NPM (already done)
- install bower
```
npm install -g bower
mklink nodejs.exe node.exe
```
- install js dependencies
```
cd <path_to_concerto-platform>\src\Concerto\PanelBundle\Resources\public\angularjs
bower install
cd <path_to_concerto-platform>\src\Concerto\TestBundle\Resources\public\angularjs
bower install
```

5b) Public resources mirroring (i'm a beginner in synfony framework but it seems the folders "\src\...\PanelBundle\...\public" and "\src\...\TestBundle\...\public" are respecttivly linked to "\web\bundles\concertopanel" and "\web\bundles\concertotest")
```
ren "<path_to_concerto-platform>\web\bundles\concertopanel" concertopanel.bak
ren "<path_to_concerto-platform>\web\bundles\concertotest" concertotest.bak
mklink /J "<path_to_concerto-platform>\web\bundles\concertopanel" "<path_to_concerto-platform>\src\Concerto\PanelBundle\Resources\public"
mklink /J "<path_to_concerto-platform>\web\bundles\concertotest" "<path_to_concerto-platform>\src\Concerto\TestBundle\Resources\public"
```

6) Install Concerto R package
```
cd "<path_to_concerto-platform>\src\Concerto\TestBundle\Resources\R"
R CMD INSTALL concerto5
```

6b) Copy to dev station
- Copy "concerto-platform" folder to dev station (renamed "concerto")
- create "concerto" db et dbuser on MySQL following informations written in configuration files

Concerto final install on dev station (follow the steps of Linux tutorial) :

7) Check Symfony requirements (PHP framework) (*)
run check script and perform any recommended actions (e.g. ext ACPU)
`php "<path_to_concerto-platform>\app\check.php"`

8) Final Concerto setup:
```
cd "<path_to_concerto-platform>"
php app/console concerto:setup
```

```
md "<path_to_concerto-platform>\src\Concerto\PanelBundle\Resources\public\rcache"
php app/console concerto:r:cache
```
This action was very long on my dev station (over 1 hour). So default TimeOut (3600s) produce an error.
I fix-it editing "<path_to_concerto-platform>\src\Concerto\PanelBundle\Command\GenerateRDocumentationCommand.php"
- line 35 :
instead of
```
$process->setTimeout(3600);
```
write
```
$process->setTimeout(7200);
```
also, rscript on Windows don't need --no-readlines commands.
- line 24 :
instead of
```
$p = "\"" . $this->getContainer()->GetParameter('test_runner_settings')['rscript_exec'] . "\" --no-save --no-restore --quiet --no-readlines \"" . $script_path . "\"";
```
write
```
$p = "\"" . $this->getContainer()->GetParameter('test_runner_settings')['rscript_exec'] . "\" --no-save --no-restore --quiet \"" . $script_path . "\"";
```

- install starter content
`php app/console concerto:content:import`

Concerto 5 is a powerfull promising software.  I hope this help. Sorry for my bad english.

Some bugs follow in new issues.

**Comment by przemyslawlis** [comment]
Hi j-pillon. Many thanks for your feedback. 
I've disabled time limit for 'generate R documentation' command and removed unnecessary --no-readline options in Rscript calls in 98ed74d579c91637231b646c83c31fa025a0ad3c
