### ISSUE TITLE
Error in value[[3L]](cond) : Error executing test logic

### ISSUE THREAD

**Issue by hpvala** [campsych/concerto-platform#241]
### Concerto Platform version

v5.0.beta.2.160

### Steps to reproduce the issue
[1] "listened to server"
<simpleError in if (f(RANGE[1]) < 0 & f(RANGE[2]) < 0) res <- RANGE[1] else {    if (f(RANGE[1]) > 0 & f(RANGE[2]) > 0)         res <- RANGE[2]    else res <- uniroot(f, RANGE)$root}: missing value where TRUE/FALSE needed>
[1] "responding to server..."
[1] "responded to server"
[1] "updating session..."
Error in value[[3L]](cond) : Error executing test logic.
Calls: tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
In addition: Warning message:
Closing open result sets 
Execution halted

**Comment by hpvala** [comment]
![screenshot-13 55 10 229-2019 07 03-20-00-07](https://user-images.githubusercontent.com/31769995/60600107-2d935e80-9dcd-11e9-8147-7081462f7b76.png)

**Comment by przemyslawlis** [comment]
Closing this issue report as it's based on old beta release.
