### ISSUE TITLE
Play audio files

### ISSUE THREAD

**Issue by jakekraska** [campsych/concerto-platform#242]
### Concerto Platform version

5.0.beta.11.1

### Expected behavior

Ability to play audio files in linear test

### Actual behavior

Audio controls do not appear using default Concerto settings when test is ran

### Steps to reproduce the issue

- Create new test
- add linearTest
- use default item template "test"
- delete default items
- add question with audio HTML

```
<audio controls="">
<source src="/bundles/concertopanel/files/gcSounds/gc_4.mp3" type="audio/mpeg" />
Your browser does not support the audio element.
</audio>
```

- audio controls appears and works in question editing screen
- when test ran audio controls do not appear or work

**Comment by przemyslawlis** [comment]
Fixed in 536ec988309f9b9705f153067340a99657d6dd70.
