### ISSUE TITLE
Finding and returning an existing user in V5.0.beta.10

### ISSUE THREAD

**Issue by zrfrere** [campsych/concerto-platform#243]
### Concerto Platform version
V5.0.beta.10

### Expected behavior
When using _createUser, if a user already exists the user object is assigned an R object that represents the users with a given login

### Actual behavior
When _createUser finds an existing user, a NULL object is returned for the user

### Steps to reproduce the issue
This happens every-time an existing user is found since there is an assignment of user to NULL on line 71.  However, there is no additional assignment of user inside the conditional where a user already exists so user is always NULL when a user already exists.

**Comment by przemyslawlis** [comment]
This is intentional behavior. Node's purpose is to create a new user and result of node is newly created user. 

To get an existing user you shouldn't use **createUser** node.

Can you please describe your use case?

**Comment by zrfrere** [comment]
To me this seemed like the node to use since the node has two branching outputs for creating a new user or having an existing user.  I want to use this node to find an existing user if the user is not found then create the user.  Either way, I would like the user to be returned to me if they exist already or if they were just created.  


Is there a more appropriate node to use?  I'm using a URL parameter of the login to look up the given user.  I wanted to try to use the Concerto source material over creating my own node to grab the user.

**Comment by przemyslawlis** [comment]
Generic *dataManipulation* node would be more suitable for the task of getting a user with specified *login*.
