### ISSUE TITLE
Updating Linear Response Test

### ISSUE THREAD

**Issue by zrfrere** [campsych/concerto-platform#244]
### Concerto Platform version
V5.0.beta.10

#### Expected behavior
When updating the values using a linear response node, the response value is updated to whatever the new response that a user provides when retaking a given linear response question.  Also, the time taken should reflect the time taken for the repeated question

### Actual behavior
When updating the values when retaking a linear response node, a floating point value is inserted into the response value section.  This floating point value appears to be the time taken for the retake of the question in the linear response node.  Also, the time taken is unchanged, which doesn't seem correct since the time taken for the new response goes unrecorded.

### Steps to reproduce the issue
This happens every-time a linear response is updated.  

I noticed in the code to save information for linear response items that the update sql command uses {{response}} not {{responseValue}}, which is used in the correctly functioning INSERT command for a linear response.

**Comment by przemyslawlis** [comment]
Closing this issue, because it's based on old beta release and unsupported "linearTest" node.
