### ISSUE TITLE
Bug with "Delete all" causes table to truncate instead of deleting rows

### ISSUE THREAD

**Issue by ananttuli** [campsych/concerto-platform#245]
### Concerto Platform version
v5.0.beta.10.1

### Expected behavior
Clicking the "Delete all" button for a data table in the Administration panel should remove all rows, and any new rows inserted after that should have the ID of (last inserted id + 1)

### Actual behavior
**"Delete All"**

When the "Delete All" button for a data table is clicked in the Administration Panel, instead of merely deleting all the rows in the table, it **truncates** the table, which restarts the "ID" counter for that table from 1 (the beginning) instead of auto incrementing the ID from last inserted row.

This unwanted behavior has resulted in overwritten (appended) responses on the CATResponse table since the same session ID's are being re-generated and then re-used for different test takers, after the sessions table was cleared using "Delete all".

E.g. If we click "Delete all" for the sessions table, and have someone attempt the test after this, the session id assigned to them would be "1", and any other tables that reference the row with session_id = "1" will be assumed to be linked to the new session, and therefore be attributed to the new (wrong) user.

Even the confirmation dialog that pops upon clicking "Delete all" asks "Are you sure you want to remove selected rows?", and mentions nothing about the table being truncated.

![delete_all_warning_message](https://user-images.githubusercontent.com/5217930/61939704-2f6cce00-afd7-11e9-8368-c116b58cc96a.png)

**Also, "Delete checked"** - Works as expected
When one clicks on "Delete checked", it performs according to expectations and just deletes the row, then inserts the next inserted ID as (last inserted ID + 1)

### Steps to reproduce the issue
1. Create a new data table through the administration panel
2. Insert 3 rows, the ID's would range from 1 - 3
3. Click "Delete All" after 3 records have been inserted

![delete_all_id_3](https://user-images.githubusercontent.com/5217930/61936629-7c997180-afd0-11e9-9cf2-789c076bbc67.png)

4. Click "Add row"

5. Observe that the ID restarts count from "1" instead of "4"
![after_delete_all](https://user-images.githubusercontent.com/5217930/61936766-b66a7800-afd0-11e9-9086-096637cf6150.png)

**Comment by przemyslawlis** [comment]
Changed in 7d7e39420f8fdf8ddaa2af4ca4cde1211f8ae1df.
