### ISSUE TITLE
Test not found error

### ISSUE THREAD

**Issue by shashwatsinha28** [campsych/concerto-platform#247]
### Concerto Platform version
v5.0.beta.13.1
### Expected behavior
I have deployed concerto on an amazon EC2 instance as per the instructions in the quickstart guide at: https://github.com/campsych/concerto-platform/wiki/quickstart-guide. The sample tests located in the starter content should run. 

### Actual behavior
The instance is running in my amazon EC2 server, and I am able to create a test but none of the items in the starter content are running. When I run any test, the message displayed is "test not found". Is there any way to download the starter content repository and integrate it so that I can view the starter samples?
### Steps to reproduce the issue
This happens every time I try to run a starter kit test on my domain: 18.130.52.209.

**Comment by przemyslawlis** [comment]
Which tests exactly are you trying to run from starter content?
Starter content doesn't contain any runnable tests out of the box. It contains nodes that you can use to build your runnable tests.
