### ISSUE TITLE
concerto-platform:5.0.beta.7-for concerto  Cannot start service concerto: OCI runtime create failed

### ISSUE THREAD

**Issue by eremiter** [campsych/concerto-platform#249]
### Concerto Platform version
concerto-platform:5.0.beta.7

### Expected behavior
docker-compose

### Actual behavior
ERROR: for concerto  Cannot start service concerto: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"rootfs_linux.go:58: mounting \\\"/root/concerto/concerto/nginx/nginx.conf\\\" to rootfs \\\"/var/lib/docker/overlay2/8dc4368ad1a85edd2a92edb16b931595fd8abc7ae581a95e3214e53759ae6450/merged\\\" at \\\"/var/lib/docker/overlay2/8dc4368ad1a85edd2a92edb16b931595fd8abc7ae581a95e3214e53759ae6450/merged/etc/nginx/nginx.conf\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

**Comment by przemyslawlis** [comment]
Have you modified docker-compose.yml file in any way? 
Do you have the same issue on latest stable release of Concerto?
