### ISSUE TITLE
Unknown database 'concerto'

### ISSUE THREAD

**Issue by yaozeyang90** [campsych/concerto-platform#251]
### Concerto Platform version
concerto-platform:5.0.beta.7.4

### Expected behavior
start concerto in docker

### Actual behavior
concerto logs
```
In PDOConnection.php line 43:,
                                                      ,
  SQLSTATE[HY000] [1049] Unknown database 'concerto'  ,
```

mysql logs:

~~~
2019-08-27T01:55:58.575517Z 32 [Note] Got an error reading communication packets,
2019-08-27T02:34:08.149102Z 39 [Note] Unknown database 'concerto'        
~~~                                            
### Steps to reproduce the issue
install concerto with docker-compose

**Comment by przemyslawlis** [comment]
Do you have the same problem trying to run latest stable version (5.0.10 at the time of writing)? Can you try it out?
Have you modified your docker-compose.yml file? Can you paste it?
