### ISSUE TITLE
Linear Test Populate From Data Table Fails

### ISSUE THREAD

**Issue by zrfrere** [campsych/concerto-platform#252]
### Concerto Platform version
5.0.0

### Expected behavior
Inside linear test, we are able to populate the questions to display using information contained in a copy of linearTestItems

### Actual behavior
The SQL query of the table fails causing an error and the failure of linear test

### Steps to reproduce the issue
This happens every time I've tried populating a linear test using a linearTestItems data table

After a little investigation, it appears that the SQL query uses a parameter {{correctColumn}} as correct which the default data table does not have this column and the linear test wizard does not generate a JSON containing this field.  This doesn't make sense to me why this would be designed like this.

**Comment by przemyslawlis** [comment]
Can you please attach your 'copy of linearTestItems' mentioned?
Also can you describe exact steps to reproduce the issue?

**Comment by zrfrere** [comment]
[Test_test.concerto.json.gz](https://github.com/campsych/concerto-platform/files/3584522/Test_test.concerto.json.gz)
[DataTable_linearTestItems_peg.concerto.json.gz](https://github.com/campsych/concerto-platform/files/3584526/DataTable_linearTestItems_peg.concerto.json.gz)

I've included two files.  The first is an extremely simple linear test.  The second is the data table that I wish to display in the linear test. 

Again, the linear test fails to ever display, which I believe is due to an incorrect SQL call inside of LinearTest in the Starter content.

Please look at the code inside the Initialization step of the Linear Test here:
getItems = function(itemBankType, itemBankItems, itemBankTable, order){
  items = NULL
  if(itemBankType == "table") {
    tableMap = fromJSON(itemBankTable)
    table = tableMap$table
    questionColumn = tableMap$columns$question
    responseOptionsColumn = tableMap$columns$responseOptions
    orderIndexColumn = tableMap$columns$orderIndex
    traitColumn = tableMap$columns$trait
    correctColumn = tableMap$columns$correct
    items = concerto.table.query(
      "
SELECT 
id, 
{{questionColumn}} AS question, 
{{responseOptionsColumn}} AS responseOptions,
{{orderIndexColumn}} AS orderIndex,
{{traitColumn}} AS trait,
**{{correctColumn}} AS correct**
FROM {{table}} 
ORDER BY {{orderIndexColumn}}
", 

The test wizard only generates a JSON without a correct Column here:
{"table":"linearTestItems_peg","columns":{"id":"id","question":"question","responseOptions":"responseOptions","orderIndex":"orderIndex","trait":"trait"}}

This leads to a consistent Error as seen when you run the test here:
"SELECT \nid, \nquestion AS question, \nresponseOptions AS responseOptions,\norderIndex AS orderIndex,\ntrait AS trait,\n AS correct\nFROM linearTestItems_peg \nORDER BY orderIndex"
[1] "[2019-09-06 15:46:21.56268]:"
<simpleError in .local(conn, statement, ...): could not run statement: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AS correct
FROM linearTestItems_peg 
ORDER BY orderIndex' at line 7>

Again, I believe that the issue is in the Initialization step since I can add a correct column to the data table and add an extra column to the JSON generated by linear test wizard and I can get the program to run. 

JSON that works with data table with added "correct" column here:
{"table":"linearTestItems_peg","columns":{"id":"id","question":"question","responseOptions":"responseOptions","orderIndex":"orderIndex","trait":"trait", "correct":"correct"}}

**Comment by przemyslawlis** [comment]
Thanks @zrfrere.
I've reproduced your issue and fixed it in 224a0893aaa9a310f07941c842e655e5ba88fb76.
