### ISSUE TITLE
Node Duplication Issues

### ISSUE THREAD

**Issue by zrfrere** [campsych/concerto-platform#253]
### Concerto Platform version
5.0.0

### Expected behavior
The GUI does not create any nodes that the test creator does not specifically request

### Actual behavior
When using the GUI, nodes get duplicated when going in and out of the GUI to view the test nodes

### Steps to reproduce the issue
If I create a new test, there are duplicate start and end nodes already.  When I add a test node such as linear test, then I go back to the main test screen then back into the specific test the node duplicates itself.

**Comment by zrfrere** [comment]
This behavior stopped after taking down Concerto, restarting Docker, and recreating another instance of Concerto

**Comment by zrfrere** [comment]
This issue is continuing to pop-up in unexpected ways.  Additionally, the nodes appear to avoid duplication you hit save.

**Comment by przemyslawlis** [comment]
Thanks @zrfrere. 
Reproduced on Firefox 69.

**Comment by przemyslawlis** [comment]
Should be fixed by: 08e121cc8be7a4fc77e6a84c466dc088cfc56827
Commit will be part of v5.0.2 release later this week.
