### ISSUE TITLE
Concerto CAT Node Tutorial Oudated

### ISSUE THREAD

**Issue by shashwatsinha28** [campsych/concerto-platform#254]
### Concerto Platform version

5.0.0
### Expected behavior
The tutorial given in the wiki page is outdated. The item entry table should contain four columns according to it, a, b, c and d for four item parameters.

### Actual behavior
The item entry table actually contains 9 item parameter columns with no mention of what each parameter stands for.

Please provide appropriate guidelines through a written/video tutorial.

**Comment by vesspopov** [comment]
Hello, the existing CAT Node Tutorial is in the 'support for older versions' page available [here](https://github.com/campsych/concerto-platform/wiki/Support-for-older-versions). There is no equivalent tutorial for v5.0.0 and beyond yet, but we are working on it. Thanks for your patience.
