### ISSUE TITLE
Checkbox only displays [[field.label]]

### ISSUE THREAD

**Issue by zrfrere** [campsych/concerto-platform#256]
### Concerto Platform version
V5.0.2

### Expected behavior
The checkbox displays the label contained in the field

### Actual behavior
The checkbox renders [[field.label]] in the HTML

### Steps to reproduce the issue
This issue occurs every time I create a new form node with a checkbox element

**Comment by przemyslawlis** [comment]
Thanks  @zrfrere. 
Fixed in 5018d74d3fd72347e3ce7369b18393038ac88682.
