### ISSUE TITLE
Can't identify user_id of session for original responses after resume session

### ISSUE THREAD

**Issue by jakekraska** [campsych/concerto-platform#257]
### Concerto Platform version

5.0.0

### Expected behavior

Be able to match session_id from response table with user_id in session table after resuming session

### Actual behavior

session_id increments in the session table upon resume of session but does not increment the session_id of rows in the response table from session prior to "resume"

### Steps to reproduce the issue

Logged into test using user_id 188 ("test2"). Provided session id66 by Concerto and completed 2 items. Closed window.

**User Table Before Resume**
```
id,login,password,enabled
187,test1,password,1
188,test2,password,1
189,test3,password,1
```

**Session Table Before Resume**
```
id,internal_id,test_id,user_id,startedTime,updateTime,finished
12,68,32,188,23/09/2019,22:40,23/09/2019,22:40,0
```

**Response Table Before Resume**
```
id,item_id,response,timeTaken,session_id,score,trait
326,4,b,5.850222111,i68,1,math
327,5,c,5.352845907,i68,1,math
```

Re-opened test, upon which the test requests login details. Once input fields are completed, the test auto resumes at item 3. Complete 2 more items and then check the session and response data tables.

**User Table After Resume**
```
id,login,password,enabled
187,test1,password,1
188,test2,password,1
189,test3,password,1
```

**Session Table After Resume**
```
id,internal_id,test_id,user_id,startedTime,updateTime,finished
12,69,32,188,23/09/2019,22:40,23/09/2019,22:42,0
```

**Response Table After Resume**
```
id,item_id,response,timeTaken,session_id,score,trait
326,4,b,5.850222111,i68,1,math
327,5,c,5.352845907,i68,1,math
328,6,d,5.754787922,i69,1,math
329,7,c,5.110322952,i69,1,math
```

The problem is that the session_id of items completed in the previous session now no longer are associated with a user_id in the session table. 

I am wondering if it would be perhaps better to either create a new session row in the sessions data table (i.e. id = 13 in this example) rather than amending the existing session (i.e. id = 12 in this example)? Or alternatively to update the session_id of the responses (i.e. id = 326 and id = 327 in this example) in the response table?

This is less of a problem for small data sets but if there are thousands of participants completing hundreds of items I am anticipating having to work out some kind of manual method of matching responses to users.

**Comment by przemyslawlis** [comment]
Each launch of the test creates internal Concerto session.
To use session resuming, you need higher level sessions that can spawn across multiple internal Concerto session and keep track of session state.
You can do this by using "startSession" node. Looking at your session table above, I see you already use it. So far so good

However looking at your response table I see that it references internal session (prefixed with "i"). That means you haven't passed your session to assessment/CAT/linearTest node. You can do that by exposing "session" input in your test node and pass "session" output of "startSession" node.

That should solve your problem.
