### ISSUE TITLE
Issues with Pain Mannequin displaying

### ISSUE THREAD

**Issue by zrfrere** [campsych/concerto-platform#259]
### Concerto Platform version
v5.0.2

### Expected behavior
The pain mannequin displays on the screen, which can then be used interactively

### Actual behavior
The pain mannequin does not appear.  The question and front/back labels appear.

### Steps to reproduce the issue
I've found that running linearTest using the Test template gives this result.  To be perfectly honest, I'm not quite sure how the pain mannequin works in the new version.

Here is the test I'm attempting to run:
[Test.concerto_mannequin.json.gz](https://github.com/campsych/concerto-platform/files/3654212/Test.concerto_mannequin.json.gz)

**Comment by przemyslawlis** [comment]
Fixed in 15806da4a183eaab545515c88a1bd047fa494ded which is included in v5.0.3 release.
