### ISSUE TITLE
Adding a paragraph to Linear Tests to describe response options

### ISSUE THREAD

**Issue by zrfrere** [campsych/concerto-platform#260]
### Concerto Platform version
v5.0.2

### Expected behavior
Being able to add a paragraph to the top of LinearTest to describe all questions on the page similar to the Questionnaire node

### Actual behavior
You cannot add a paragraph to describe the options that you wish to choose similar to Questionnaire nodes in the older version of Concerto 

### Steps to reproduce the issue
An issue is that I cannot have a response option that has no option to click since users must respond to all questions.

**Comment by przemyslawlis** [comment]
In current Concerto version `linearTest` and `CAT` nodes were merged into single `assessment` node and can do both linear and adaptive test.

This node contains `instructions` input port that does exactly what you need.
