### ISSUE TITLE
504 Error returned while running test

### ISSUE THREAD

**Issue by Loknath1** [campsych/concerto-platform#262]
### Concerto Platform version

v5.1.0 

### Expected behavior
Test should run.

### Actual behavior
"Server problem encountered. Execution halted." message shown and 504 error code comes for 'http://localhost:88/test/aa299bd59ad6e0e0e1bf564e346477592fee2e1e/start_session/%5B%5D'

### Steps to reproduce the issue
1. created a test and added a CAT node to it and running the created test.

Addition Details:
Request URL:http://localhost:88/test/aa299bd59ad6e0e0e1bf564e346477592fee2e1e/start_session/%5B%5D
Request method:POST
Remote address:127.0.0.1:88
Status code:
504
Version:HTTP/1.1
Referrer Policy:no-referrer-when-downgrade

**Comment by przemyslawlis** [comment]
There's no stable 5.1.0 release.
Please use stable release. See:
https://github.com/campsych/concerto-platform/wiki/quickstart-guide
https://github.com/campsych/concerto-platform/wiki/deployment-guide
