### ISSUE TITLE
Data table value not being passed from wizard to underlying test correctly 

### ISSUE THREAD

**Issue by ananttuli-elipse-uq** [campsych/concerto-platform#263]
### Concerto Platform version
5.0.2

### Context

E.g. Let 
* main test -> X
* sub-test of X -> Y

#### In X (Flowchart type test)
A wizard test for Y has been added in X. One of the values configurable in the wizard is of type "Data table".

#### In Y (Flowchart type test)
An input parameter has been added which accepts data table value which was passed from the wizard for this test.
A `createUser` starter node is added and the `userBankTable` input port for this node uses Y's input parameter's value.

### Expected behavior
The `createUser` starter content node should be able to use Y's input parameter as an input for the input port `userBankTable`

### Actual behavior
Error encountered.

```[1] "[2019-10-16 05:29:57.734778]:"
<simpleError: lexical error: invalid char in json text.
                                                custom_users_table
                     (right here) ------^
>
```

Looks like values of type "Data table" specified in wizard is not being passed properly to underlying tests and sub-tests / being mis-handled by the `createUser` node.

### Steps to reproduce the issue
1. Create a test Y
1.1 Add input parameter "users_table" for Y 
1.2 Add a `createUser` starter content node.
1.2 Add input port `userBankTable` in this node and read the value Y's input parameter i.e. "users_table"

2. Create a wizard test for Y ("Y_wizard_test")
2.1 Make "users_table" as a test wizard param of type "Data table"

3. Create a test X
3.1 Add "Y_wizard_test" as a node
3.1 Configure the wizard by selecting a data table from dropdown

4. Run/Debug test X (error should be encountered)

**Comment by przemyslawlis** [comment]
`userBankTable ` field input parameter in `createUser` node is actually of `Data table column map`, not `Data table` map. That's why you are having error pasted.

You can check it out in `createUser` wizard.
