### ISSUE TITLE
Passing Concerto Global Variables

### ISSUE THREAD

**Issue by zrfrere** [campsych/concerto-platform#264]
### Concerto Platform version
V5.0.2

### Expected behavior
Using Get we can retrieve global variables inside sub-tests

### Actual behavior
We are unable to Get global variables inside sub-tests

### Steps to reproduce the issue
Create a test that goes inside a larger test where in the higher-level test we set a global variable.  This global variable can be accessed using the Get node.  The Get node is unable to access the global variable inside the sub-test.

**Comment by przemyslawlis** [comment]
You get/set global variables by using:

```
c.set(name, value, global=T)
c.get(name, global=T)
```

... or, starting from v5.0.11 release, by using **get** and **set** nodes and setting their input parameter **global** to anything that evaluates to logical true in R.
