### ISSUE TITLE
Run simple test but only "please wait"

### ISSUE THREAD

**Issue by schuang0122** [campsych/concerto-platform#265]
### Concerto Platform version
v5.1.0
### Expected behavior
I only follow the guide to create a test containing tests start -> show page -> tests end, try to show "Hello world".
### Actual behavior
Run tests only shows "Please wait ..." for a long time.
### Steps to reproduce the issue
I am a beginner of coding and using concerto, so that I really need some simple tutorial for current version. The version of guide video in tutorial now is quite different from the current one. It's hard for me to follow it step by step. Thank you.

**Comment by przemyslawlis** [comment]
v5.1.0 doesn't have stable release yet. Please use stable version. See [Quickstart guide](https://github.com/campsych/concerto-platform/wiki/quickstart-guide) for more info.
