### ISSUE TITLE
How to change route login

### ISSUE THREAD

**Issue by dwisatrio** [campsych/concerto-platform#267]
### Concerto Platform version 5.0.7

I tried to change the direct link login, where the current link (assessment.test.com/login) I want to change to (assessment.test.com/desk). But it does not change the location of direct but still to login, it only changes the naming of routes. anyone can help me?

**Comment by przemyslawlis** [comment]
Rename login action annotation in **src/Concerto/PanelBundle/Controller/PanelController.php** from:
`* @Route("/login", name="login")`
to
`* @Route("/desk", name="login")`
