### ISSUE TITLE
Can't Run Test Server problem encountered. Execution halted

### ISSUE THREAD

**Issue by dwisatrio** [campsych/concerto-platform#268]
### Concerto Platform version 5.0.7

i cant run after installin, all package and all step done but i try run test error " Server problem encountered. Execution halted. ", can help me for resolved this issue ?

**Comment by eriam** [comment]
Hello 

Can you make sure you have the socket extension !

Regards

**Comment by przemyslawlis** [comment]
Have you checked [Quickstart Guide](https://github.com/campsych/concerto-platform/wiki/quickstart-guide)?
Which installation method have you used?

Please paste your application logs around the time of failed request. See [Reporting Issues](https://github.com/campsych/concerto-platform/wiki/Reporting-Issues#application-logs) for more info.
