### ISSUE TITLE
Something wrong with rewrite?

### ISSUE THREAD

**Issue by lelmarir** [campsych/concerto-platform#27]
Hi,
i've created a docker image for Concerto: https://hub.docker.com/r/lelmarir/docker-concerto/, 
but i get this url: http://192.168.99.100:8081/app.php/admin#/tests

is the "app.php" part supposed to be there or should it be "http://192.168.99.100:8081/admin#/tests" ?
This is becouse when i run a test it invoke "http://192.168.99.100:8081/test/196845ab0f57adda1643aa9ea4999cfb/session/start/%5B%5D" that yeld a "404 Not Found".
Instead "http://192.168.99.100:8081/app.php/test/196845ab0f57adda1643aa9ea4999cfb/session/start/%5B%5D" at least give "Oops! An Error Occurred The server returned a "405 Method Not Allowed".", that IMO is more encouraging

How can i fix this? Is a configuration problem?

**Comment by przemyslawlis** [comment]
Configuration problem. This might help you out: http://symfony.com/doc/current/cookbook/configuration/web_server_configuration.html

**Comment by tangi75** [comment]
The "AllowOverride All" directive in the site .conf file may be missing.
