### ISSUE TITLE
GGplot2

### ISSUE THREAD

**Issue by DavidCGon** [campsych/concerto-platform#271]
Hello.

I was trying to use ggplot2 with Concerto but gives me an error. 
So how I can make a plot on eval?
Because the error says me that aes is not a function but on ggplot2 documentation package it is a function.

https://ggplot2.tidyverse.org/reference/aes.html

Thanks a lot.

**Comment by przemyslawlis** [comment]
Current Concerto version doesn't use/require/install ggplot2.
You need to make sure that you have it installed properly and loaded in your test logic to use it.
