### ISSUE TITLE
Please, bring back questionnare node

### ISSUE THREAD

**Issue by cguilherme00** [campsych/concerto-platform#272]
### Concerto Platform version
5.0.10

### Expected behavior
Show up response options in likert scale format.
I noted that likert scale format was a node called questionnaire in early versions. Could you please put it in plans do come back? 

### Actual behavior
Just display options under the question, not quite suited for likert style questionnaires.

**Comment by rolfmblindgren** [comment]
I think  the proper solution in version 5 would be to create a response template.  Which would be very welcome.

**Comment by aboukhary** [comment]
We have been using concerto for few years and we are not able to upgrade because the questionnaire node is no longer available. 
It will be really great if concerto development team considers adding it back.

**Comment by rolfmblindgren** [comment]
the questionnaire node appears  now to be the assessment node. «Likert» should be made a response option. Looking at the templates for the other response options, it seems like just making one would not be all that difficult.

**Comment by rolfmblindgren** [comment]
However, the manual process of creating a 200-item questionnaire would be laborious at best.

Yes, I want the questionnaire node back.

Thank you.

**Comment by przemyslawlis** [comment]
As @rolfmblindgren rightly pointed out, questionnaire node can be made by creating new test template for assessment node.

>However, the manual process of creating a 200-item questionnaire would be laborious at best.

That's true unfortunately.

I'll address both of the issues above in one of the upcoming releases.
