### ISSUE TITLE
cannot login 

### ISSUE THREAD

**Issue by statue22** [campsych/concerto-platform#273]
### Concerto Platform version
v5.0.10

### Expected behavior
log in

### Actual behavior
I followed quickstart guide -- Installation on Amazon EC2
and created http://localhost/admin (like: http://x.x.xx.xx/admin with x being numbers, but cannot login with default login "admin" and password "admin"

error message:
Wrong login or password!

What's up?

**Comment by cguilherme00** [comment]
Then you launch the cloud formation stack you are required to provide two passwords, one for concerto admin and another for database. You need to use the exact same password provided there:
![image](https://user-images.githubusercontent.com/4997599/75361179-acc22f00-5895-11ea-8809-a89a6197dffc.png)
