### ISSUE TITLE
Manual Import Help

### ISSUE THREAD

**Issue by aboukhary** [campsych/concerto-platform#274]
### Concerto Platform version
I am trying to trigger a manual update of concerto starter concent

### Actual behavior
The command 
`/var/www/vhosts/concerto# php bin/console concerto:content:import --env=prod --sc
`
Results in the following:

`copying files...
files copied successfully
importing content...
source path used:
.
instructions used:
[]
importing export.concerto.yml...
importing export.concerto.yml failed!
content importing failed!
validate.table.name.unique`

Can you please help to run this command without an error?

**Comment by przemyslawlis** [comment]
Looks like importing your file would result in creating new Concerto data table, but your database already contains table with that name.
