### ISSUE TITLE
External connect Mysql

### ISSUE THREAD

**Issue by frjoao** [campsych/concerto-platform#277]
### Concerto Platform version
10
### Expected behavior

Connect with third-party data visualization tools

### Actual behavior

MySQL is not exposed outside the docker

### Steps to reproduce the issue

We did the installation following the AWS walkthrough. But we saw that Docker's MySQL is not exposed, we need to connect this data with a dashboard visualization tool

**Comment by bkielczewski** [comment]
Hi. That's on purpose. Exposing things by default is bad. You can expose it yourself if you need to.

Add:

    ports:
      - 3306:3306

To your `docker-compose.yml` somewhere under `services: database:`. 

See [Docker Compose docs](https://docs.docker.com/compose/compose-file/compose-file-v2/#ports) for more information.
