### ISSUE TITLE
"Require Response" not working

### ISSUE THREAD

**Issue by cguilherme00** [campsych/concerto-platform#279]
### Concerto Platform version
5.0.12

### Expected behavior

"Require Response" field on Assessment->Responses wizard is not working as it should.

### Actual behavior
Either with the option checked or not, the test allows the user to skip pages without responses.

### Steps to reproduce the issue
Create a new Assessment test.
Go to Assessment->Responses wizard -> `require response` and check that option.
Run the created test and note that it lets you pass through without responding.

**Comment by przemyslawlis** [comment]
I'm unable to reproduce it.
Is your installation based on stable releases or from master/5.0-dev branch?
Can you try create clean Concerto instance from stable release (e.g. docker 5.0 image tag) and see if you still have this problem?

**Comment by cguilherme00** [comment]
As I found out later, I may have imported some older version test and screwed up the code. After a new install it started working as expected. Thank you for the response.
