### ISSUE TITLE
How to publish my test online ?

### ISSUE THREAD

**Issue by DANIEL-VELASCO** [campsych/concerto-platform#280]
Hello Everyone,

I´ve just successfully created a test on concerto v5.0.11 on my computer which is accessible from local host (example: http://localhost/test/1d69ec259ce3f7de373854564967a25dee345d85). I´ve got a basic question: How can i publish it so that anybody can access it online ?

Thanks a lot

**Comment by bkielczewski** [comment]
Like with any web application - you need a server (a computer that is turned on 24/7 with a good network connection). Then you need Concerto installed there. This will make it available on server's public ip address. For most scenarios you'd additionally need to buy a domain name and a TLS certificate. That's so the people won't use the ip address but a friendly name and all the data from your respondents will reach the server encrypted.

One possible way to achieve most of the above is described in the [Quickstart Guide](https://github.com/campsych/concerto-platform/wiki/quickstart-guide) in Amazon EC2 section. Provided you decide to go with AWS cloud account, the CloudFormation template there should automate installing Concerto for you leaving you only with purchasing a domain name and pointing it to the server.

**Comment by DANIEL-VELASCO** [comment]
Thank you so much @bkielczewski.
