### ISSUE TITLE
Right Click Not Woking to Create a Node in Test Flow

### ISSUE THREAD

**Issue by vamcumn** [campsych/concerto-platform#283]
### Concerto Platform version
5.0.12

### Expected behavior
Right click in Test Flow -> Create Node -> New Selected Node

### Actual behavior
When we click on the node in the drop down list..nothing happens...(Checked on Edge and Chrome)

### Steps to reproduce the issue
New Test -> Test Flow -> Right Click to Add Node

**Comment by przemyslawlis** [comment]
Can you please provide output of your browser console? 
See this for more info:
https://github.com/campsych/concerto-platform/wiki/Reporting-Issues#how-to-check-for-client-side-errors-in-chrome
