### ISSUE TITLE
Question: Keep time counting when test closed with resume session.

### ISSUE THREAD

**Issue by viboen** [campsych/concerto-platform#284]
### Concerto Platform version
v5.0.11 - Installed on Amazon EC2

Hello concerto team, 
Is it possible to 'continue' test on background even when the user close the test ?

Meaning: 

I have a test with resume session and user authentication.
Each question should take 20sec and if the user close the test the 20secs keep counting.
After 20secs the question would be marked as wrong and in case user comes back he is sent to next question.

I was wondering if the submit test API could help.
Any help would be very much appreciated.

test flowchart for reference
![image](https://user-images.githubusercontent.com/3730834/79251657-d5f34a80-7e56-11ea-90b6-abb13f9ff247.png)

**Comment by przemyslawlis** [comment]
That's currently only possible in "assessment" node for total test time (through "Test Time Limit Type" setting). It's not possible for individual item type for now.

I've already added that to TODO. I'm going to close this issue report, but will update it with a comment when this is implemented.
