### ISSUE TITLE
Direct install with PostgreSQL database

### ISSUE THREAD

**Issue by j-pillon** [campsych/concerto-platform#285]
### Concerto Platform version
5.0.12

### Expected behavior
PostgreSQL database schema generation and inital data initialization with command line :
`php ./bin/console concerto:setup`

### Actual behavior
This error occurs:
`In AbstractPostgreSQLDriver.php line 66:`
`[Doctrine\DBAL\Exception\TableExistsException]`
`An exception occurred while executing 'CREATE INDEX hash_idx ON SamlToken (hash)':`
`SQLSTATE[42P07]: Duplicate table: 7 ERREUR:  la relation « hash_idx » existe déjà`
(« hash_idx » relation already exists)
[concerto-pgsql-database-init-error.txt](https://github.com/campsych/concerto-platform/files/4509243/concerto-pgsql-database-init-error.txt)

### Steps to reproduce the issue
Server environment
OS : Windows 10 Family 1909
Database : PostgreSQL 12.2 x64
Web server : Apache HTTPD 2.4.43 x64 with PHP 7.4.5 x64 nts running through FastCGI (with extensions for PostgreSQL aka pdo_pgsql & pgsql)
R interpreter : 3.6.3 (with library for PostgreSQL aka RPostgreSQL)

1. Install environment
2. Create "concerto" and "concerto_test" databases and users
3. Modify "parameters.yml"
4. Follow "Deployment Guide/Direct installation" until database schema generation and inital data initialization

Please find attached the "parameters.yml" configuration file and the complete error message (with verbose option).

[concerto-pgsql-database-init-error.txt](https://github.com/campsych/concerto-platform/files/4509250/concerto-pgsql-database-init-error.txt)

[parameters.yml.txt](https://github.com/campsych/concerto-platform/files/4509252/parameters.yml.txt)

**Comment by j-pillon** [comment]
Hi,

I found the problem: the tables 'samltoken' and 'testsession' have indexes with the same name. And PostreSQL dislike... Just rename the index of one of the two tables with Doctrine code. 

I modify line 10 in _./src/Concerto/APIBundle/Entity/SamlToken.php_;
` * @ORM\Table(indexes={@ORM\Index(name="at_hash_idx", columns={"hash"})})`

**Comment by przemyslawlis** [comment]
Thanks for this. 
SamlToken table index is renamed in 0cf30dcd00c82069dd2f7edfc20494ed995bf915.
