### ISSUE TITLE
v5.0.3 'Can go back" button not functioning in linear tests

### ISSUE THREAD

**Issue by uqswalk5** [campsych/concerto-platform#288]
### Concerto Platform version 
v5.0.3

### Expected behavior
In a single Linear test containing 30 test items, setting the number of items per page to 5 and checking the "Can go back" option inserts "Next" and "Back" buttons at the bottom of each page to allow user to move freely forwards and backwards within a test.

### Actual behavior
The "Next" buttons function as expected, moving the user to the next page. **However, the "Back" button does not return the user to the previous page as expected.** Developer tools show no errors and running in de-bug mode also shows no error.

### Steps to reproduce the issue

To be sure that this was not something we had introduced, we created a new linear test with the 3 pre-built simple items (10+10, 100+100, 1000+1000). Set number of items per page to 1. Selected "Can go back" check box option. Ran test. The "Next" buttons function as expected, moving the user to the next page. **However, the "Back" button does not return the user to the previous page as expected.** It does nothing at all when pressed. Developer tools record nothing when the button is pressed.

If this is a bug with v5.0.3 and it has been rectified in a later or current release, are our tests built in v5.0.3 compatible with the current release? Can we re-deploy the latest release and export/import existing test into the newer release?

Thank you

**Comment by vesspopov** [comment]
Thanks for reporting - this was fixed with 5.0.4

**Comment by sspartzz257** [comment]
Vess,

Thank you as I am now able to work with this sense the fix.  I am however struggling to save student sessions so if they exist on their browser they can log in and resume the test. I have been playing around in the concerto environment and I can not figure the correct node and porting structure to make this happen.  Do you have any examples of what that may look like for me to use to create my test?

Best,
Ben
________________________________

**Comment by vesspopov** [comment]
Sorry can you explain what you mean by "exist on their browser"?

There's the option to make session resumable in the startSession node. 

Or if by 'on their browser' you mean something URL-related, then maybe this tutorial can help - you could get URL param by adding it as a test input, then use form or eval node to check if this param is valid, and branch your test flow accordingly: https://github.com/campsych/concerto-platform/wiki/Pass-URL-Parameter-As-Test-Variable

**Comment by sspartzz257** [comment]
I actually think that detail is less important to the question and I apologize for the confusion.  I guess my question is more around the node and port structure to save and make the session resumable.

Best,
Ben
________________________________

**Comment by vesspopov** [comment]
Ticking resumable in start session node gives you various options:





*From:* sspartzz257 <notifications@github.com>
*Sent:* 16 July 2020 17:11
*To:* campsych/concerto-platform <concerto-platform@noreply.github.com>
*Cc:* Vess Popov <vp288@cam.ac.uk>; State change <
state_change@noreply.github.com>
*Subject:* Re: [campsych/concerto-platform] v5.0.3 'Can go back" button not
functioning in linear tests (#288)



I actually think that detail is less important to the question and I
apologize for the confusion. I guess my question is more around the node
and port structure to save and make the session resumable.

Best,
Ben
________________________________

**Comment by sspartzz257** [comment]
Yes, I understand that but what connections in ports do I need to make to other nodes to make the session resumable?  Do I need to do the following in a linear pattern:

-Place the start session node at the beginning of the test
-Then connect the create user node to startsession node
-Then add the form node for my user login page
-the save data node
-then the authenticate user node
-Then I split off to connect to either a display page node that displays authentication failed or the user begins the assessment.
-then the test ends

What port connections do I need to make across these nodes to solve this problem or do I need to change the linear order of these nodes.

I can provide a picture of these as well if that would help you understand my issue.  Any insights you can provide would be much appreciated.

Best,
Ben

________________________________

**Comment by vesspopov** [comment]
Hi Ben,



Have you tried this already? Does it work?



If it doesn’t please send a picture of your test flow.


Thanks,
Vess



*From:* sspartzz257 <notifications@github.com>
*Sent:* 16 July 2020 17:50
*To:* campsych/concerto-platform <concerto-platform@noreply.github.com>
*Cc:* Vess Popov <vp288@cam.ac.uk>; State change <
state_change@noreply.github.com>
*Subject:* Re: [campsych/concerto-platform] v5.0.3 'Can go back" button not
functioning in linear tests (#288)



Yes, I understand that but what connections in ports do I need to make to
other nodes to make the session resumable? Do I need to do the following in
a linear pattern:

-Place the start session node at the beginning of the test
-Then connect the create user node to startsession node
-Then add the form node for my user login page
-the save data node
-then the authenticate user node
-Then I split off to connect to either a display page node that displays
authentication failed or the user begins the assessment.
-then the test ends

What port connections do I need to make across these nodes to solve this
problem or do I need to change the linear order of these nodes.

I can provide a picture of these as well if that would help you understand
my issue. Any insights you can provide would be much appreciated.

Best,
Ben

________________________________

**Comment by sspartzz257** [comment]
Vess,

This node alignment is not working currently.  I have attached an image of an example node structure that I envision we may follow for you to view and provide feedback on.  I am mainly looking to understand how the node structure and port connections to save data for users to make the session resumable.
________________________________
