### ISSUE TITLE
Can't add options in form

### ISSUE THREAD

**Issue by mr-incomplete** [campsych/concerto-platform#290]
### Concerto Platform version
v5.0.8
![Screenshot 2020-05-18 at 11 50 33](https://user-images.githubusercontent.com/64110694/82205033-ce174200-98fd-11ea-90df-396df5039325.png)

### Expected behavior
I want to create a form with a dropdown menu so I use the 'form node' and use 'select' as the type. When I try to add the options, I repeatedly click 'add new element' but no element is added (as can be seen in the screenshot above)
### Actual behavior
Should add element so I can input options.

**Comment by vesspopov** [comment]
Hello, do you have any message in your browser console when you try to do this? It is most likely a temporary UX issue with the library that these buttons come from. Please try refreshing the page and trying again.
