### ISSUE TITLE
The page is unavaible

### ISSUE THREAD

**Issue by mrmevlut** [campsych/concerto-platform#297]
`docker-compose up -d`

Creating network "docker-compose_default" with the default driver
Creating database ... done
Creating concerto ... done

but:  localhost:8080 did not work. "This page is unavailable"

The reason it is 8080:
https://github.com/campsych/concerto-platform/issues/296

**Comment by bkielczewski** [comment]
What exactly do you type into the browser window?

**Comment by mrmevlut** [comment]
I actually have one server. I type as IPadress:8080.

**Comment by przemyslawlis** [comment]
Please paste output from following command two commands:
`docker ps`
`docker logs -f concerto`

**Comment by mrmevlut** [comment]
`docker ps`
CONTAINER ID        IMAGE                               COMMAND                  CREATED             STATUS                     PORTS                            NAMES
e239372e3b6b        campsych/concerto-platform:master   "/bin/sh -c 'printen…"   24 minutes ago      Up 4 minutes (unhealthy)   9000/tcp, 0.0.0.0:8080->80/tcp   concerto
5e5176393dec        mysql:5.7                           "docker-entrypoint.s…"   24 minutes ago      Up 24 minutes              3306/tcp, 33060/tcp              database

`docker logs -f concerto`
wait-for-it.sh: waiting 300 seconds for localhost:3306
wait-for-it.sh: timeout occurred after waiting 300 seconds for localhost:3306
wait-for-it.sh: waiting 300 seconds for localhost:3306
wait-for-it.sh: timeout occurred after waiting 300 seconds for localhost:3306
wait-for-it.sh: waiting 300 seconds for localhost:3306
wait-for-it.sh: timeout occurred after waiting 300 seconds for localhost:3306
wait-for-it.sh: waiting 300 seconds for localhost:3306
wait-for-it.sh: timeout occurred after waiting 300 seconds for localhost:3306
wait-for-it.sh: waiting 300 seconds for localhost:3306
wait-for-it.sh: timeout occurred after waiting 300 seconds for localhost:3306

**Comment by przemyslawlis** [comment]
Seems like you have set your database host to localhost. Unless you have a database server on **concerto** container, it shouldn't be set to localhost.
Revert database host to **database** container in your docker-compose.yml:
`DB_HOST=database`
and restart **concerto** container:
`docker-compose up --build --force-recreate -d concerto`.
Give it couple of minutes after restart before retrying.

If above doesn't help, please paste your full docker-compose.yml contents.

**Comment by mrmevlut** [comment]
It is work. Thank you very much.
