### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by mrmevlut** [campsych/concerto-platform#298]
Hello

when i try to login

Oops! An Error Occurred
The server returned a "500Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

I get an error.

**Comment by mrmevlut** [comment]
last prod.log


{"@timestamp":"2020-08-08T13:55:34.942579+00:00","@source":"vps-071f3689","@fields":{"channel":"request","level":200,"ctxt_route":"login_check","ctxt_route_parameters":{"_route":"login_check"},"ctxt_request_uri":"https://concerto.lemasy.co/admin/login_check","ctxt_method":"POST"},"@message":"Matched route \"login_check\".","@tags":["request"],"@type":"concerto"}
{"@timestamp":"2020-08-08T13:55:34.946974+00:00","@source":"vps-071f3689","@fields":{"channel":"request","level":500,"ctxt_exception":{"class":"Doctrine\\DBAL\\Exception\\ConnectionException","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused","code":0,"file":"/home/ubuntu/concerto-platform/concerto-platform-5.0.15/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:93","trace":["/home/ubuntu/concerto-platform/concerto-platform-5.0.15/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:169","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:155","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php:28","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:356","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:889","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php:889","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php:178","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/src/Concerto/PanelBundle/Repository/AdministrationSettingRepository.php:15","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/src/Concerto/PanelBundle/Service/AdministrationService.php:206","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/src/Concerto/PanelBundle/Service/AdministrationService.php:230","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/src/Concerto/PanelBundle/Service/AdministrationService.php:240","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/src/Concerto/PanelBundle/Service/AdministrationService.php:262","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/src/Concerto/PanelBundle/Service/AdministrationService.php:255","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/src/Concerto/PanelBundle/EventSubscriber/AuthenticationSubscriber.php:34","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:212","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:44","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Authentication/AuthenticationProviderManager.php:107","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/UsernamePasswordFormAuthenticationListener.php:100","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/AbstractAuthenticationListener.php:140","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall.php:111","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall.php:84","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/vendor/symfony/symfony/src/Symfony/Bundle/SecurityBundle/EventListener/FirewallListener.php:48","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:212","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:44","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:127","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:68","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:200","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/web/app.php:24"],"previous":{"class":"Doctrine\\DBAL\\Driver\\PDOException","message":"SQLSTATE[HY000] [2002] Connection refused","code":2002,"file":"/home/ubuntu/concerto-platform/concerto-platform-5.0.15/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31","trace":["/home/ubuntu/concerto-platform/concerto-platform-5.0.15/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php:22","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:356","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:889","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php:889","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php:178","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/src/Concerto/PanelBundle/Repository/AdministrationSettingRepository.php:15","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/src/Concerto/PanelBundle/Service/AdministrationService.php:206","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/src/Concerto/PanelBundle/Service/AdministrationService.php:230","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/src/Concerto/PanelBundle/Service/AdministrationService.php:240","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/src/Concerto/PanelBundle/Service/AdministrationService.php:262","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/src/Concerto/PanelBundle/Service/AdministrationService.php:255","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/src/Concerto/PanelBundle/EventSubscriber/AuthenticationSubscriber.php:34","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:212","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:44","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Authentication/AuthenticationProviderManager.php:107","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/UsernamePasswordFormAuthenticationListener.php:100","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/AbstractAuthenticationListener.php:140","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall.php:111","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall.php:84","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/vendor/symfony/symfony/src/Symfony/Bundle/SecurityBundle/EventListener/FirewallListener.php:48","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:212","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:44","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:127","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:68","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:200","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/web/app.php:24"],"previous":{"class":"PDOException","message":"SQLSTATE[HY000] [2002] Connection refused","code":2002,"file":"/home/ubuntu/concerto-platform/concerto-platform-5.0.15/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27","trace":["/home/ubuntu/concerto-platform/concerto-platform-5.0.15/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php:22","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:356","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:889","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php:889","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php:178","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/src/Concerto/PanelBundle/Repository/AdministrationSettingRepository.php:15","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/src/Concerto/PanelBundle/Service/AdministrationService.php:206","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/src/Concerto/PanelBundle/Service/AdministrationService.php:230","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/src/Concerto/PanelBundle/Service/AdministrationService.php:240","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/src/Concerto/PanelBundle/Service/AdministrationService.php:262","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/src/Concerto/PanelBundle/Service/AdministrationService.php:255","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/src/Concerto/PanelBundle/EventSubscriber/AuthenticationSubscriber.php:34","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:212","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:44","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Authentication/AuthenticationProviderManager.php:107","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/UsernamePasswordFormAuthenticationListener.php:100","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/AbstractAuthenticationListener.php:140","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall.php:111","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall.php:84","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/vendor/symfony/symfony/src/Symfony/Bundle/SecurityBundle/EventListener/FirewallListener.php:48","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:212","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:44","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:127","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:68","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:200","/home/ubuntu/concerto-platform/concerto-platform-5.0.15/web/app.php:24"]}}}},"@message":"Uncaught PHP Exception Doctrine\\DBAL\\Exception\\ConnectionException: \"An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused\" at /home/ubuntu/concerto-platform/concerto-platform-5.0.15/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 93","@tags":["request"],"@type":"concerto"}

**Comment by bkielczewski** [comment]
Hi. Well, it tells you `SQLSTATE[HY000] [2002] Connection refused`. So make sure your database is running and accessible.
Are you using docker-compose to deploy both Concerto and database?

**Comment by mrmevlut** [comment]
Okay thanks. Let me take a look at the database.
