### ISSUE TITLE
Getting Theta to Display on Current Version of Concerto

### ISSUE THREAD

**Issue by Simon2718** [campsych/concerto-platform#299]
Can someone please advise me as to how to get theta to display at the conclusion of a CAT test?

I have read all the relevant documentation I can find, but as others have noted, the documentation and tutorials are outdated (e.g., the Info node no longer exists). So as a new user, I am lost. I have tried to figure out what might have changed from version to version, but so far, I am not having success.

I am trying to test/demo the platform for my organization, so we can consider Concerto for exam delivery. Please help.

**Comment by vesspopov** [comment]
Hi Simon, sorry you're having trouble. There are two tutorials that can help you here, and the fact that the nodes have changed between versions doesn't impact this issue at all. Variables from R are called out with curly brackets. Have a look at:

1. passing variables between nodes - https://github.com/campsych/concerto-platform/wiki/Pass-Test-Variables-Between-Nodes
2. showing feedback - https://github.com/campsych/concerto-platform/blob/master/wiki/Adding%20Feedback.pdf

Theta is an output port of the assessment node, so all you need to do is expose it, pass it to where you want to show it and then call it out with {{curly brackets}}. So if you want to show 'Your theta score is X', then add a showPage node to the end of your flowchart, add a dynamic input port to that node and call it 'theta'. Then drag the theta output port from your assessment node to the theta input port of your showPage node. Then, in the content of the showPage node, write 'Your theta score is {{theta}}.' 

Hope that helps, thanks.
