### ISSUE TITLE
concerto v4 to concerto v5. 

### ISSUE THREAD

**Issue by AnguloB** [campsych/concerto-platform#30]
Hi, 
I am trying to update my concerto v4 to concerto v5. I am not sure if I should use "Linux Installation guide" as if I were installing a new software, or I should use "Linux update guide" instead. 

Thank you in advance, 

A.

**Comment by przemyslawlis** [comment]
Hi AnguloB,
Unfortunately Concerto v4 can't be automatically upgraded to v5.
You need to make a clean installation of v5, but you should easily transfer your test over to v5, by creating code type test and just pasting your test logic code.
See this for more info about recreating v4 tests in v5: https://github.com/campsych/concerto-platform/wiki/Importing-Concerto-Platform-v4-tests-into-v5

Closing this issue. Feel free to open new one if you encounter any problems while trying to recreate your test.
