### ISSUE TITLE
502 Error

### ISSUE THREAD

**Issue by mrmevlut** [campsych/concerto-platform#301]
Hello

I did the configuration as on the symphony page, but when I enter it with the URL, I get 502 error. If I type <IP>/8080, I can access the site?

Thank you

**Comment by bkielczewski** [comment]
Hi. That certainly needs some clarification on what have you been configuring exactly, where and what do you hope to achieve by that?

Anyway, the port part of the url is separated by a colon, so somehostname:8080

**Comment by mrmevlut** [comment]
hello 

server {
                 server_name https://someHostname.com
                root /home/ubuntu/concerto-platform/web;

                location / {
        # try to serve file directly, fallback to app.php
        # replace app.php with app_dev.php in dev
        try_files $uri /app.php$is_args$args;
        #proxy_pass http://<IP>:8080;
        #proxy_pass http://localhost:8080;
    } 


When I type the URL, the browser returns a 502 error. I can access with IP address right now, but I want to access with domain. If I enable proxy_pass localhost line, I access with domain, but after logging in, the browser redirects to localhost: 8080 and gives the page not found error.
this is nginx configuration.

**Comment by mrmevlut** [comment]
proxy_pass http: // localhost: 8080; If I set it as, I can access it with the URL, but when entering admin, the browser redirects to localhost: 8080

**Comment by bkielczewski** [comment]
For nginx proxy to wherever I would use:

    location / {
        proxy_pass http://localhost:8080;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;
    }

Remove `root /home/ubuntu/concerto-platform/web;` makes no sense. Nothing of nginx proxy config is Concerto-specific.

Also, make sure `CONCERTO_PLATFORM_URL` in your `docker-compose.yml` is either `/` or you can give it an absolute url you plan to access Concerto with.

**Comment by mrmevlut** [comment]
thank you Mr. Kielczewski. It is work!
