### ISSUE TITLE
Timer Weird Behavior

### ISSUE THREAD

**Issue by aboukhary** [campsych/concerto-platform#302]
### Concerto Platform version
v5.0.beta.7.5

### Expected behavior
We expected the linear test timer to count down normally and when the timer is out the section is completed and the following section is started. 

### Actual behavior
The timer doesn't behave normally. 
When the test is left for a few minutes, for example 4 or 5 minutes, the timer is randomly changed so for example if I had 5:00 minutes left, we would get 7:00 minutes left or only 2:00 minutes or sometimes a section completed message.

I have tried to tune PHP and MySQL cache, buffers, timers but the problem seems to persist. 

Can you provide any help with this issue?

**Comment by vesspopov** [comment]
Hello, you are using a very old and beta version of Concerto. Can you please try using the latest version (currently 5.0.15) which offers a choice between client-side or server-side timers? Thanks. Broadly speaking, Concerto doesn't have a concept of a 'section' other than how that is defined in the specific test. You can set a time limit for the whole test or time limit per item, so the unusual behaviour may be to do with a test-specific mix-up with these values. For example if you had an item with 2 minutes limit and then an item with a 5 minutes limit, and a total test time limit of 10 minutes, it would be normal for the timer to jump from 2" to 5" to 3".
