### ISSUE TITLE
"timeout occurred after waiting 300 seconds for database:3306" after reboot server

### ISSUE THREAD

**Issue by mrmevlut** [campsych/concerto-platform#305]
Hello.

When I restart the server, although mysql and nginx are running, I do docker-compose up -d every time to access concerto or I get a 502 error.

thank you

**Comment by mrmevlut** [comment]
update

the error is  "timeout occurred after waiting 300 seconds for database:3306" after ubuntu reboot

**Comment by mrmevlut** [comment]
update

the error is "timeout occurred after waiting 300 seconds for database:3306" after ubuntu reboot

**Comment by bkielczewski** [comment]
There are multiple ways on a Linux system to make it run things at startup or even with Docker.

For example, you could change restart policy in your `docker-compose.yml` from `on-failure` to `unless-stopped`. Both for database and concerto. This makes them run every time Docker daemon is restarted (i.e. after server restart).

**Comment by mrmevlut** [comment]
Thank you very much it's done!
