### ISSUE TITLE
Info node not existing in v5.0.15

### ISSUE THREAD

**Issue by eilcode** [campsych/concerto-platform#306]
### Concerto Platform version
v5.0.15

### Expected behavior
info node exists

### Actual behavior
info node doesn't exist

In case, the info node disappeared on purpose, it would be good to mention it in the wiki:
https://github.com/campsych/concerto-platform/wiki/Info-node

**Comment by vesspopov** [comment]
Hi there, the info node disappeared a few years ago. It is replaced by the showPage node which allows you to show any HTML.

The link you shared is a sub-page from the old documentation (pre 5.0.1.) which is clearly labelled at the top as being OUTDATED and relating only to older versions: https://github.com/campsych/concerto-platform/wiki/Support-for-older-versions

Thanks. I will see if we can reorganise the location of pages to include some further indication of such pages being outdated.

**Comment by eilcode** [comment]
Thanks for the answer!
Especially when using the search box, it is totally unclear whether you will end up on old content or not.
I can recommend **readthedocs** which can be connected to the github repo and which supports multiple documentation versions. If you take this into consideration, I might support the documentation.
