### ISSUE TITLE
Save Error Validation failed Someone updated object. Your current loaded version is not the current one. Please refresh.

### ISSUE THREAD

**Issue by aboukhary** [campsych/concerto-platform#307]
### Concerto Platform version
v5.0.17

### Actual behavior
I have a fresh manual installation of Concerto. It seems that some security setting is not set properly. I can't save a test flow after editing it. I receive the validation error message:
"Someone updated object. Your current loaded version is not the current one. Please refresh."

The installation commands are as follows
`git clone https://github.com/campsych/concerto-platform.git /var/www/html/concerto-platform
curl -s http://getcomposer.org/installer | php
php -dmemory_limit=1G composer.phar install --no-interaction
npm i bower -g
cd /var/www/html/concerto-platform/src/Concerto/PanelBundle/Resources/public/angularjs && bower install --allow-root
cd /var/www/html/concerto-platform/src/Concerto/TestBundle/Resources/public/angularjs && bower install --allow-root

cd /var/www/html/concerto-platform/
php ./bin/console concerto:r:cache

nano /var/www/html/concerto-platform/app/config/parameters.yml

php ./bin/console concerto:setup --env=prod --admin-pass=Admin-Password
php ./bin/console concerto:content:import --sc

nano /etc/apache2/apache2.conf
nano /etc/apache2/sites-available/000-default.conf
a2dissite 000-default.conf
a2ensite 000-default.conf
/etc/init.d/apache2 restart
a2enmod rewrite
 systemctl restart apache2

It also seems that the security problem generates the following error message in the test runner:
<simpleError in setwd(concerto$workingDir): cannot change working directory>

![image](https://user-images.githubusercontent.com/17113039/92961333-5b634100-f46f-11ea-9f9a-614eee7aaac7.png)

### Steps to reproduce the issue
I have a fresh manual installation of Concerto. It seems that some access rights are not set properly.

**Comment by aboukhary** [comment]
I have tried to set the access right to be as follows (with no success):

chown www-data:www-data /var/www/html/concerto-platform/src/Concerto/TestBundle/Resources 
chown -R www-data:www-data /var/www/html/concerto-platform/src/Concerto/PanelBundle/Resources/public
chown www-data:www-data /var/www/html/concerto-platform/src/Concerto/TestBundle/Resources/R/fifo 
chown -R www-data:www-data /var/www/html/concerto-platform/var/cache 
chown -R www-data:www-data /var/www/html/concerto-platform/var/logs 
chown -R www-data:www-data /var/www/html/concerto-platform/var/sessions 
chown -R www-data:www-data /var/www/html/concerto-platform/var/git 
chown -R www-data:www-data /var/www/html/concerto-platform/src/Concerto/PanelBundle/Resources/import 
chown -R www-data:www-data /var/www/html/concerto-platform/src/Concerto/PanelBundle/Resources/export 
chown www-data:www-data /var/www/html/concerto-platform/app/config/jwt/private.pem 
chown www-data:www-data /var/www/html/concerto-platform/app/config/jwt/public.pem
chwon www-data:www-data /var/www/html/concerto-platform/web

**Comment by vesspopov** [comment]
Hi there, according to changelog this is fixed in 5.0.17. https://github.com/campsych/concerto-platform/blob/master/CHANGELOG.md 

This version is in development and has not been tagged yet, so you should not experience it anymore once released.
