### ISSUE TITLE
New installation on AWS EC2 - getting error on saving test template

### ISSUE THREAD

**Issue by anksphenomenon** [campsych/concerto-platform#310]
### Concerto Platform version

v5.0.16
### Expected behavior

while creating a new test I should be able to save it.

### Actual behavior

I get the error: Operation failed. Validate your data and try again.

### Steps to reproduce the issue

1. install Concerto on AWS with instructions given here: https://github.com/campsych/concerto-platform/wiki/quickstart-guide  - specifically, this section: "With a domain name and TLS certificate". 

2. login as admin 
3. go to Tests -> add new -> create a sample test and press "Save"
![Screen Shot 2020-10-11 at 11 37 16 PM](https://user-images.githubusercontent.com/3687804/95713133-e1afa600-0c1a-11eb-84fe-5e495b11d28c.png)
![Screen Shot 2020-10-11 at 11 38 03 PM](https://user-images.githubusercontent.com/3687804/95713127-df4d4c00-0c1a-11eb-9b93-744d2976930a.png)
![Screen Shot 2020-10-11 at 11 37 44 PM](https://user-images.githubusercontent.com/3687804/95713131-e1170f80-0c1a-11eb-8a8f-f35a7d557cf3.png)

**Comment by bkielczewski** [comment]
Thanks for reporting. It would be helpful if you've logged in to the instance (with ssh using the key you've created) and send us the output of:

    cd /home/concerto
    docker-compose ps
    docker-compose logs

**Comment by anksphenomenon** [comment]
here is the output for docker-compos ps:

###
$ docker-compose ps
  Name                Command                  State                        Ports                  
---------------------------------------------------------------------------------------------------
certbot    /bin/sh -c trap exit TERM; ...   Up             443/tcp, 80/tcp                         
concerto   /bin/sh -c printenv | sed  ...   Up (healthy)   80/tcp, 9000/tcp                        
database   docker-entrypoint.sh mysqld      Up             3306/tcp, 33060/tcp                     
nginx      /docker-entrypoint.sh /bin ...   Up             0.0.0.0:443->443/tcp, 0.0.0.0:80->80/tcp
###

the logs file is too big to paste here, should I just upload it here or is there a safe safe to share the file with you?

**Comment by anksphenomenon** [comment]
I checked the log file, feels like it is safe to upload here, but let me know if you'd like the file in another way..
[docker_logs.txt](https://github.com/campsych/concerto-platform/files/5368529/docker_logs.txt)

**Comment by bkielczewski** [comment]
Thanks. It seems to be about timezone you've selected during deployment. It should be in the format expected by [tz database](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) and PST clearly isn't.

Go to CloudFormation on your AWS, update stack using current template, change the timezone, after few minutes you can verify the correct timezone would appear in docker-compose.yml. By then it should have been restarted automatically.

Another matter is that this error should be recoverable by just letting database access layer to use UTC timezone by default. However, this needs investigation and is not very relevant to your case (you probably need different timezone anyway).

**Comment by anksphenomenon** [comment]
thanks, this worked. closing this ticket, I appreciate the quick help!
