### ISSUE TITLE
Refreshing git status failed

### ISSUE THREAD

**Issue by snaeil** [campsych/concerto-platform#311]
### Concerto Platform version
v5.0.16

### Expected behavior
Following the [Wiki article](https://github.com/campsych/concerto-platform/wiki/Administration) it should be possible to connect to a github repository for exporting the concerto instance.

### Actual behavior

Trying to connect the concerto instance with a empty github repository results in following error:

![Screenshot from 2020-10-12 18-15-37](https://user-images.githubusercontent.com/52743746/95768897-546e5f00-0cb7-11eb-9cce-1732bbb65e53.png)

### Steps to reproduce the issue

1. Launch concerto v5.0.16 via docker-compose.
2. Create empty github repository.
3. In concerto, go to `Administration` and to `Content`.
4. Enter Repo URL and github credentials (**no error yet!**).
5. Create a new FlowTest and save.
6. Go back to `Administration` and `Content` --> Error appears.

**Comment by przemyslawlis** [comment]
Thanks for reporting.
This is fixed in 184c710ed5f321d824d4d0d55d99273ab8f26df2, which will be included in 5.0.17 release.

**Comment by snaeil** [comment]
@przemyslawlis Tested this with the latest 5.0.17 version but it doesn't seem to work.
Will we have to wait until 5.0.17 has a release?

**Comment by snaeil** [comment]
@przemyslawlis Tested this with the latest 5.0.17 version but it doesn't seem to work either.
