### ISSUE TITLE
Can't connect git repo to concerto

### ISSUE THREAD

**Issue by snaeil** [campsych/concerto-platform#313]
### Concerto Platform version
v.5.0.17
v.5.0.18

### Expected behavior
Entering git URL and credentials let's connect github repo and concerto.
This is mentioned to be fixed (see issue #311).

### Actual behavior
Same behaviour as decribed in issue #311 

### Steps to reproduce the issue
1. Create empty git repo
2. Go to concerto and enter credentials and git repo URL (tried it with ssh, https)
3. Wait some time and after refreshing the error `Refreshing git status failed` appears.

Is it something I did wrong? Does the repo e.g. have to have some content before?
Or does the URL have to have a special format?

Sorry but I'm stuck here.

**Comment by minh12345678** [comment]
Same problem here

**Comment by vesspopov** [comment]
Hi both, sorry you've had issues here. Can you please try this on latest version and let us know if you still have trouble. There were several improvements to git integration post-5.0.19. Thanks.
