### ISSUE TITLE
Landing page should directly open the first page of a test

### ISSUE THREAD

**Issue by anksphenomenon** [campsych/concerto-platform#316]
### Actual behavior

the user sees a dropdown of all the tests.

### Steps to reproduce the issue
just open Eklavya.io, you will see the dropdown. I am looking for the landing page to behave like described in the expected behavior section.

**Comment by vesspopov** [comment]
Hello, from 5.0.19 onwards, you can go to Administration -> Settings -> choose a 'home test' from the dropdown. That test will then launch and replace the usual 'available tests' page shown for your Concerto instance. If you upgrade to the latest version this should be straightforward. Thanks.
