### ISSUE TITLE
Installing concerto 5 at AMI

### ISSUE THREAD

**Issue by Abuamany** [campsych/concerto-platform#32]
I have successfully installed concerto 5 to AMI server , but I did not find a complete list of nodes , I attach the following on-screen display . Could I be given the advice to be able to deliver a complete list of nodes.  Thank you for your attention and assistance.  

![screenshot from 2016-08-21 22-14-17](https://cloud.githubusercontent.com/assets/16170999/17838063/e972b3da-67ed-11e6-8150-027f5c3036ba.png)

**Comment by davidstillwell** [comment]
At the bottom of the Linux Installation Guide is a heading about starter content. It looks to me like you didn't import starter content. Check it out at the bottom here: https://github.com/campsych/concerto-platform/wiki/Linux-installation

Please let me know if this fixes it

**Comment by Abuamany** [comment]
Thanks David I will try tomorrow.

**Comment by Abuamany** [comment]
Hi David, I've managed to install concerto 5 in AWS .
Thanks for the help and the support.

Sincerely yours,
Heru Wiryanto
