### ISSUE TITLE
Question on details for API request documentation

### ISSUE THREAD

**Issue by snaeil** [campsych/concerto-platform#320]
I have some questions regarding the API requests which seem not to be documented in the [wiki](https://github.com/campsych/concerto-platform/wiki/API-Requests):

1. Can the status code (e.g. 200) be modified for request's responses? (e.g. if a bad input was given)
2. Is it correct that the session expiration time can be found in the file `parameters_test_runner.yml`?
3. Will all resources be freed for an expired API session?
4. Is it necessary to do a keep alive request if I do a submit request before expiration?

It would be great if anyone has answers to these questions.
Best regards

**Comment by bkielczewski** [comment]
I'll leave it to my colleague to confirm, but 1) no, it's doesn't logically validate your input it's more like silly table access/storage thing; 2) yes; 3) yes; 4) no.

**Comment by przemyslawlis** [comment]
That's correct.

**Comment by snaeil** [comment]
Thanks for the fast replies!
