### ISSUE TITLE
Delete nodes still exist when trying to delete

### ISSUE THREAD

**Issue by snaeil** [campsych/concerto-platform#327]
### Concerto Platform version
5.0.20

### Expected behavior
Within a test, when I delete a node, I expect it to be gone completely.

### Actual behavior
The node is not deleted but only "hidden".

### Steps to reproduce the issue
1. Right click on a node and delete it
2. Got to tab "Administration"
3. Export content
4. Check out `export.concerto.yml` and find nodes still existing

**Comment by przemyslawlis** [comment]
There's no such concept in Concerto as hidden node. Nodes are permanently removed on delete action.
Maybe you're seeing some other node in your export.concerto.yml file?

**Comment by snaeil** [comment]
My bad, I have been wrong. Sorry!
