### ISSUE TITLE
Cannot log in Concerto on AWS

### ISSUE THREAD

**Issue by lshchnk** [campsych/concerto-platform#330]

**Comment by bkielczewski** [comment]
Does your password contain any special characters, like $ for instance?

**Comment by lshchnk** [comment]
> Does your password contain any special characters, like $ for instance?
Yes it does

**Comment by bkielczewski** [comment]
Yeah, so there was a problem with escaping '$' in the strings of CloudFormation template, something we have on the TODO to check what we can do about it. 

For now I would suggest just deleting the stack, and recreate it, just use the password w/o special chars, especially the dreaded $. 

It's that, or you need to ssh to the machine and look up the actual password which was used. It's in `/home/concerto/docker-compose.yml`, this will be `CONCERTO_PASSWORD=xxx` line.

**Comment by lshchnk** [comment]
> Yeah, so there was a problem with escaping '$' in the strings of CloudFormation template, something we have on the TODO to check what we can do about it.
> 
> For now I would suggest just deleting the stack, and recreate it, just use the password w/o special chars, especially the dreaded $.
> 
> It's that, or you need to ssh to the machine and look up the actual password which was used. It's in `/home/concerto/docker-compose.yml`, this will be `CONCERTO_PASSWORD=xxx` line.

It works. Thank you!
