### ISSUE TITLE
Fail to launch cloudformation stack instances to AWS

### ISSUE THREAD

**Issue by mkrasmus** [campsych/concerto-platform#332]
### Concerto Platform version
5

### Expected behavior
Cloudformation templates setup with login to admin

### Actual behavior
Cloudformation stack with TLS fails to get up and rolls back, self terminates.
Cloudformation stack basic with EC2 provides a running instance, however the http://${PublicIp}/admin goes straight 
to 

`Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.`

### Steps to reproduce the issue
Following either step in the wiki for quick deployment/installation using EC2.

**Comment by bkielczewski** [comment]
Thanks for the report, I'll check if the templates are still valid. Sometimes things change.

**Comment by bkielczewski** [comment]
I've tested the ones we are providing with the source code and they seem to be working [https://github.com/campsych/concerto-platform/tree/master/deploy/cf]. 

I've noticed though the ones in quickstart guide linked to the copies in our S3 bucket, which seemed to be quite old, so perhaps that was it. I've updated them. 

Please delete your cf stacks and recreate them again. Sorry for the trouble caused.
