### ISSUE TITLE
How can import to my local instance all this examples?

### ISSUE THREAD

**Issue by johnfelipe** [campsych/concerto-platform#334]
My question is 
Is possible import

https://discovermyprofile.com/tests

For begin a good teacheble process and knowledge concerto workflow?

**Comment by johnfelipe** [comment]
Can u share that resources and how import to my instance?

**Comment by johnfelipe** [comment]
Anyone?

**Comment by bkielczewski** [comment]
These website you are you referring is not Concerto-related. Is a separate web app with tests. It some cases it links to certain Concerto tests. These are created by individual researchers for the purpose of their research and are not a part of Concerto distribution.

From Concerto point of view we try to improve documentation or the examples, time permitting. We also offer courses and consultancy. Visit https://www.psychometrics.cam.ac.uk/ should you wish to learn more or get in contact.

**Comment by johnfelipe** [comment]
Can u share resources of concerto
Tnks

**Comment by johnfelipe** [comment]
Pls share all test for learn with already done examples ..
