### ISSUE TITLE
Amazon EC2 Error

### ISSUE THREAD

**Issue by x360539** [campsych/concerto-platform#335]
Hi all,

I am attempting an installation of Concerto on Amazon EC2. I am following the Quickstart Guide:

https://github.com/campsych/concerto-platform/wiki/quickstart-guide

I successfully created a key pair. However, when I click the "Launch ec2-basic CloudFormation Stack" and attempt to create the stack, I get the following error:

![AWS Error](https://user-images.githubusercontent.com/4870642/126051044-ad972310-e873-4473-a1ba-54d5fed4167b.png)

Does anyone know why this is happening? Maybe the Amazon S3 URL has changed?

Thanks for any help you can provide.

**Comment by bkielczewski** [comment]
Hi, that's probably my bad (not setting up public permissions after update), so sorry, try again.

**Comment by x360539** [comment]
Thanks! It's working now.
