### ISSUE TITLE
Response Checking Parameter

### ISSUE THREAD

**Issue by 29029** [campsych/concerto-platform#34]
Has anyone ever created a test parameter that gives immediate feedback regarding whether a response is correct/incorrect? If not, could you outline the steps that would be required to build such a parameter?

**Comment by davidstillwell** [comment]
Hi Kate - we don't have an existing node that does that. It will require some coding, but you could edit the linear_test node though fairly easily (copy it and give it a new name first though). If you check the R code for source_linear_test you'll see where it displays the item and then after that you'll see where it works out whether the answer is correct or not. If it's correct/incorrect you just need to add in another "show template" piece of code that displays a well done / bad luck message.

**Comment by davidstillwell** [comment]
(we are having a discussion via Email)
