### ISSUE TITLE
R: Package ‘session’ was removed from the CRAN repository.

### ISSUE THREAD

**Issue by pablopoo** [campsych/concerto-platform#346]
Hi, 
the R package sessions was removed yesterday,14-06-22, from the CRAN repository, so can´t be compiled. Please evaluate the impact on the platform functionality.
https://cran.r-project.org/package=session

### Concerto Platform version
5.0.26

### Expected behavior
Package installed

### Actual behavior
Warning message:
package ‘session’ is not available for this version of R

### Steps to reproduce the issue
Build the docker container.

**Comment by przemyslawlis** [comment]
Should be fixed in 8d98a3071269ff1774898f79fcee80d7cc3efce0
