### ISSUE TITLE
UTF-8 Turkish character Problem

### ISSUE THREAD

**Issue by rumiexile** [campsych/concerto-platform#35]
Editor screens works well on Turkish but Test application shows charachers broken. Could you please check your compatibility about it?

Also import function from a CSV seems incompatible with utf-8 coding. just imports blank parts. 

Keep up good work.

**Comment by przemyslawlis** [comment]
Is your R installation able to display Turkish characters? Can you check it out?
Could you please attach example CSV file that you have issues with so I can check it out?
Thank you!

**Comment by rumiexile** [comment]
My work is on Amazon. Is it possible to customise R installation there? Sorry I have no programming expertise.

**Comment by przemyslawlis** [comment]
Sure it is. You can log in to your instance through SSH and check out your R. 

How did you install Concerto? Did you use Amazon AMI or did you manually install it? What kind of OS are you using?

Can you please share a URL of your test so I can see the issue live?
Is it possible for you to export your full test and send it to me, so I can recreate it locally?
And please send me your CSV file so I can check it out.

**Comment by rumiexile** [comment]
could you please send me a contact e-mail so I can provide you  details.

I've installedi it using Amazon AMI. Using default settings in the guide. 

Kind Regards.

**Comment by przemyslawlis** [comment]
Please send it to przemek@concertoplatform.com .
I'm going to try to recreate your problem by launching a new instance on Amazon from the AMI.

**Comment by przemyslawlis** [comment]
Many thanks rumiexile!
Fixed in 46cde5ccc150b48432fabc8ea033274ab6d66b93 .
