### ISSUE TITLE
How to ask for a choice between two options ?

### ISSUE THREAD

**Issue by tangi75** [campsych/concerto-platform#39]
Hi, I'm implementing a MBTI-like test using the questionnaire node and I facing a few issue (I create a separate github Issue for each).

To two split each question in two parts, one to appear on the left hand of the radio buttons, one to appear on the right hand? Is there a more cutomizable node to do that or should I try to implement my own node? In the latter case, Is it possible to get hints on how to achieve that (I know the documentation is still to be written)?

**Comment by davidstillwell** [comment]
We don't have a node for ipsative testing so far, although I need one myself so eventually one will come. In the mean time you can try editing the questionnaire node. Start by copying the source_questionnaire node, and then you can edit the code for it. It's not simple though I must admit.

**Comment by tangi75** [comment]
OK, thank you David.

**Comment by tangi75** [comment]
Hello David,

Here is a tutorial on how to create an ipsative questionnaire 👍 

[Custom-node-creation-part-1.md.txt](https://github.com/campsych/concerto-platform/files/558253/Custom-node-creation-part-1.md.txt)

I tried to create a pull request on the wiki repo (having added this new file on a new branch) but I obviously don't have the required rights to do so.

**Comment by aboukhary** [comment]
I followed the tutorial, but there is a bug with display. The html code looks ok, but it is always rendered with the last two columns as merged. Do anyone else experience this? 
![image](https://cloud.githubusercontent.com/assets/17113039/20283792/1e0122f4-aac3-11e6-9995-002899648065.png)

**Comment by aboukhary** [comment]
I followed the tutorial above, but thers seem to be a bug related to how html is rendered. The last two columns are merged in all browsers. I checked the html code but I couldn't find any problem. 

![image](https://cloud.githubusercontent.com/assets/17113039/20283836/50c32fb6-aac3-11e6-91af-90416a6032c3.png)

**Comment by tangi75** [comment]
I didn't include the layout changes as it was not the purpose of the tutorial but you'd have to insert this in line 231 of the layout (within .questionnaireResponseCell) :
    border-right: 1px solid #d1d1d1;
