### ISSUE TITLE
How to use images for questions and responses?

### ISSUE THREAD

**Issue by tangi75** [campsych/concerto-platform#40]
The concerto demo shows a Raven test. I believe it has been implemented on Concerto4.
Is it possible to do something similar on Concerto5 or would it require new nodes?

**Comment by davidstillwell** [comment]
It doesn't require new nodes. You can put images into questionnaire/cat/polycat nodes using HTML instead of just text for the question/response. e.g. for a Raven question you'd have something like:

'<img src="whatever.jpg" />'

**Comment by davidstillwell** [comment]
This wiki page might help too: https://github.com/campsych/concerto-platform/wiki/Uploading-files-and-referring-to-them-in-your-code

**Comment by tangi75** [comment]
Ok, I'll try to that. Thank you.
