### ISSUE TITLE
How to compute things on the info node?

### ISSUE THREAD

**Issue by tangi75** [campsych/concerto-platform#41]
Hi, I'm implementing a MBTI-like test and would need to concatenate the dominant letter of each trait to get the final profile (e.g. INTP if Introversion > Extraversion, iNtuition > Sensing, Thinking > Feeling and Perception > Judging). Is it possible to do that using the info node or any other way?

**Comment by davidstillwell** [comment]
The info node will only display things that are sent to it. However, you can edit the variable before it arrives using R code. e.g. you have a questionnaire node, and then an info node (as in the questionnaire video example). When you connect up the 'scores' output from the questionnaire node, to the 'inserts' input of the info node, you'll see a menu icon in the middle of the link between the two nodes. If you click on this, you get an R code section where you can edit the scores variable. So, you could put code like this:

`if(scores$introversion > 10) { scores$introversion = "I" } else { scores$introversion = "E" }`

I know I haven't explained this perfectly but I hope this is useful to start with. Please ask any clarification questions.

**Comment by tangi75** [comment]
Thank you David for your answer.
I suppose I could put these two lines of codes : 

`scores$profile = paste(ifelse(scores$IE < 0, "I", "E"), ifelse(scores$SN < 0, "S", "N"), ifelse(scores$FT < 0, "F", "T"), ifelse(scores$JP < 0, "J", "P"))`
`scores`


The scores object on the last line being the one to insert.
I still have to declare the new "profile" attribute of "scores" somewhere I guess...

**Comment by tangi75** [comment]
I made it by one-lining the code using ";" as separator! Thanks a lot.

**Comment by davidstillwell** [comment]
Great stuff, glad it works. It should be possible to code it on multiple lines. Although one line appears by default, pressing enter should lead to multiple lines. Was there an issue with that?
