### ISSUE TITLE
setup.exe for Native Windows Installer does not work on my computer

### ISSUE THREAD

**Issue by BBCansevgisi** [campsych/concerto-platform#43]
Dear All,

I tried to install Concerto Platform to use it offline on Windows. After I run setup.exe, I cannot find any icons that I can use to reach the installed program, and also, after I restart (as requested by setup.exe) and tried to run setup.exe again, It installs the pre-installed program again.

My computer specifications are:
Windows 10 Enterprice
64-bit Operating System, x64-based processor

I would be grateful if you can help me.

Best regards,
Bilge Bozkurt

**Comment by davidstillwell** [comment]
Hi Bilge Bozkurt,

It should install a program called "Concerto Launcher" Can you do a search for it and let us know if it isn't there?

Thanks,
David

**Comment by przemyslawlis** [comment]
Can you please copy paste program output log (available from within app)?
Do I understand correctly that it installs the same program over and over again? What is the name of the prerequisite that creates the loop?

**Comment by BBCansevgisi** [comment]
Hi,

The ConcertoLauncher Setup installs the same program over and over again.
Please find the attached image.

I cannot view the pop-up the image of which is included on "
https://github.com/campsych/concerto-platform/wiki/Native-Windows-Installer",
namely ConcertoLauncher v09.9.0.

I would be grateful if you can help me.

Thanks in advance.

Best regards,
Bilge

**Comment by przemyslawlis** [comment]
@BBCansevgisi : there is no image attached.

**Comment by przemyslawlis** [comment]
Closing because of lack of response.
