### ISSUE TITLE
Error while running a test

### ISSUE THREAD

**Issue by chuenlok** [campsych/concerto-platform#45]
I installed the concerto on a ubuntu machine. I can login and create tests. While I tried to run the test, it shows `Error encountered. Execution halted.` and in the console, I am seeing 
```
Loading required package: concerto5
Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called 'concerto5'
Error: could not find function "fromJSON"
Execution halted
```
I can load libraries `concerto5` and `rjson` in a separated R console.

Did I miss some step to configure the R environment for the apache server?

Thank you very much.

**Comment by przemyslawlis** [comment]
Please see: https://github.com/campsych/concerto-platform/wiki/Linux-installation#installation-steps
Did you do installation step 6? If yes, did you do it with sudo?

**Comment by chuenlok** [comment]
Thanks for the reply.

I ran the installation command with `sudo`. I tried to log in as `root` and ran the command again to unsure it is in root's environment.

Now I cannot see anything in the console. Instead, I got 
```
{"source":2,"code":-1,"debug":""}
```
from the request.

**Comment by przemyslawlis** [comment]
Are you running it in debug mode? 
If not, please run it in debug mode and see if there is something more in the console then.

**Comment by chuenlok** [comment]
Now I can run the test successfully. I found that I need to log in as root and install some packages again( `RMysql`, `concerto5` and `Rjson`) . It seems that `sudo` is not enough.

**Comment by chuenlok** [comment]
I think this issues can be closed?
