### ISSUE TITLE
installation Problem

### ISSUE THREAD

**Issue by rositar** [campsych/concerto-platform#53]
I am trying to install v0.9.13.0 on windows 7 (64-bit). I installed all required open source software before. However concerto launcher can not configure mysql server service. (mysql server is up running on my machine).

I have attached a screen shot as well. 
Any clue why it is not going through this step?

Thanks[
![installationissue](https://cloud.githubusercontent.com/assets/17633831/19336515/d1718a0c-9157-11e6-90b6-82307c1d7c5f.png)

**Comment by przemyslawlis** [comment]
Does the step fail with any error message or does it just hang in position on the screenshot above?
Do I understand correctly that you already had a MySQL server running before starting the Launcher for the first time?

**Comment by Abuamany** [comment]
Pls help us we have problem like this.
![concerto1](https://cloud.githubusercontent.com/assets/16170999/19505750/a79092c2-95ef-11e6-8e5f-21c0969df274.png)

**Comment by przemyslawlis** [comment]
@Abuamany: Can you reproduce it and paste full installation log?

**Comment by rositar** [comment]
It does not produce any error message and just hang in the position
Yes I had mysql server service up and running.

Thanks

**Comment by Abuamany** [comment]
now running
![concerto2](https://cloud.githubusercontent.com/assets/16170999/19540154/b637a8c2-9687-11e6-9f2f-b29258848366.png)

**Comment by rositar** [comment]
would you please provide some information? how did you fix the problem?

Thanks

**Comment by petersteger** [comment]
1. During the Windows installation the installer asked me for an answer prefix ! someting about bower.json. I just entered "!1" as answer. 
2. You have to answer REPAIR on .NET when restarting the installer after a reboot to get further with the installation


Without IT knowledge, I don't think any teacher could install this...Even I had to restart the setup a few times because of .net installation. 
I hope that will change one time, I remember half a year ago we tried to install it on linux, 2 IT guys had about 1 day to get it run!

**Comment by rositar** [comment]
Yes it is not easy to install it..

Thanks anyway for the reply. I went through the repair step before and it didn't work.

**Comment by przemyslawlis** [comment]
> During the Windows installation the installer asked me for an answer prefix ! someting about bower.json. I just entered "!1" as answer.

^ this is no longer required after c1181176eba5a86e225662ce8a52b53f47746e83

@rositar : I'm investigating right now the issue you had with trying to start WAMP MySQL service when other MySQL service is already running. I will leave a comment here when this is resolved.

**Comment by przemyslawlis** [comment]
@rositar: 

> It does not produce any error message and just hang in the position
Yes I had mysql server service up and running.

Did you had a WAMP already installed BEFORE running the launcher for the first time? If yes, which WAMP version? Which MySQL server version does it contain?

**Comment by przemyslawlis** [comment]
Closing due to lack of response. Feel free to respond and I'll reopen it. Problem is being investigated.
