### ISSUE TITLE
Error: scope.rightClickEvent is null

### ISSUE THREAD

**Issue by aboukhary** [campsych/concerto-platform#54]
All installation steps have been followed successfully and test runner works; however, it seems that I cannot add objects in the flowchart test. 
The right click returns an error: Error: scope.rightClickEvent is null
It seems that there is no other way to add test events. Please advise.

**Comment by przemyslawlis** [comment]
What browser is this happening on (name, version)?
What version of Concerto Platform are you on currently?

**Comment by przemyslawlis** [comment]
Closing because of no response.

**Comment by aboukhary** [comment]
Update: The problem is associated with Firefox browser. 

The installation work fine with Chrome.
