### ISSUE TITLE
login error 

### ISSUE THREAD

**Issue by Abuamany** [campsych/concerto-platform#56]
hello I have been installed concerto native windows version, and update the launcher.  
![123](https://cloud.githubusercontent.com/assets/16170999/19518945/e25007b4-9633-11e6-901d-68e33cc57ffe.png)

**Comment by przemyslawlis** [comment]
Does launcher report that there is a new version of Concerto Platform available? 
Do you see "Update" button in the Launcher main window when all the checks are finished?
If yes, please try to "Update" the platform and see if the problem still persist.
Have you recently updated your Concerto Platform version?

**Comment by Abuamany** [comment]
this is concerto launcher preview
![concerto2](https://cloud.githubusercontent.com/assets/16170999/19539362/2bf0f0aa-9683-11e6-9ab3-2f13cc8d95f9.png)

**Comment by przemyslawlis** [comment]
Is the issue solved? I'm asking because you closed it.

**Comment by Abuamany** [comment]
sorry, the problem is not solved the same error still appears and I can not log in  into the concerto system.

**Comment by przemyslawlis** [comment]
Have you recently updated your Concerto Platform version?

**Comment by Abuamany** [comment]
yes, I've updated, the launcher has been declared Concerto Platform update not possible right now.

**Comment by Abuamany** [comment]
precisely the error that appeared after I update

**Comment by Abuamany** [comment]
This results in the concerto update launcher

![concerto2](https://cloud.githubusercontent.com/assets/16170999/19539991/b4c185b8-9686-11e6-8682-a46c815ad39e.png)

**Comment by Abuamany** [comment]
Still error came after I tried to log onto concerto
![concerto3](https://cloud.githubusercontent.com/assets/16170999/19540074/3838adc2-9687-11e6-9495-d21b14443466.png)

**Comment by przemyslawlis** [comment]
v0.9.14.1 of Launcher has been just published. Among other improvements, it let's you force update your Concerto Platform installation. This might solve your problem. 
Can you please update (by clicking 'update' button in Launcher) your Concerto Platform and report if the problem is fixed?

**Comment by Abuamany** [comment]
I've tried, and succeeded, thank you very much for your help
