### ISSUE TITLE
How to contribute to the documentation?

### ISSUE THREAD

**Issue by tangi75** [campsych/concerto-platform#59]
Here are two tutorials I wrote based on what I learned from implementing a MBTI-like test on Concerto:

- [Test flow tutorial.md](https://github.com/campsych/concerto-platform/files/558754/Test.flow.tutorial.md.txt)
- [Custom-node-creation-part-1.md](https://github.com/campsych/concerto-platform/files/558253/Custom-node-creation-part-1.md.txt) : example of a new ipsative questionnaire node

The [Helping-Concerto](https://github.com/campsych/concerto-platform/wiki/Helping-Concerto) page tells that "[the wiki pages] are editable by everyone who has a (free) GitHub account" but I don't see any Edit button. I tried to create a pull request on the wiki repo (having added this new file on a new branch) but got an permission denied. I obviously don't have the required rights to do so.

**Comment by Abuamany** [comment]
Thanks fo your share Tangi75, I will try...

**Comment by Abuamany** [comment]
Dear Tangi75

I've tried ipsative node and add 2 items in a question bank as an example of this image
![screenshot from 2016-11-04 15-21-23](https://cloud.githubusercontent.com/assets/16170999/19999084/fabca0de-a2a2-11e6-9324-8f87673ed821.png)
the result will be like this image
![screenshot from 2016-11-04 15-21-56](https://cloud.githubusercontent.com/assets/16170999/19999162/47a2de86-a2a3-11e6-96b7-1a25d6a622ae.png)

How the question number 2 and 3 are out precisely the order of items is not the item itself.

**Comment by tangi75** [comment]
There is obviously an offset somewhere as a non reverse option B appears on the left (perfectionnist).
Could you export your ipsative questionnaire node and share it (dropbox link or whatever) so I can debug it.
There may be a bug in my tutorial as you are possibly the first one to test it.

**Comment by Abuamany** [comment]
Yes, but we need your email for share the link.

**Comment by tangi75** [comment]
I made my email public on my profile.

**Comment by tangi75** [comment]
There is indeed a problem with direct table. This is something I don't use, I prefer custom tables.
When I add a trace (print(str(ib$direct_table[[i]]))) before line 35 of the source code of the test logic, I get : 

> List of 7
>  $ id              : chr "1"
>  $ question        : chr "<p>Example question 1</p>\n"
>  $ order           : chr "1"
>  $ trait           : chr "first_trait"
>  $ reversed_score  : chr "0"
>  $ question_optionA: chr "<p>Introvert</p>\n"
>  $ question_optionB: chr "<p>Extrovert</p>\n"
> NULL

There shouldn't be any question field. I don't know where it comes from as it doesn't appear in the your field group definition.
You may try with a custom table until I troubleshoot this.

**Comment by tangi75** [comment]
Couldn't this be caused by hidden data resulting of the direct table having been initialized for the test node before the test wizard has been modified (the question field replaced by the two options)?

**Comment by davidstillwell** [comment]
Hm, I did think the wiki was editable but apparently not. @przemyslawlis - can this be enabled?

Thanks so much for the tutorial Tangi! Great stuff. Let's get it on the wiki...

**Comment by przemyslawlis** [comment]
@tangi75: 

> Couldn't this be caused by hidden data resulting of the direct table having been initialized for the test node before the test wizard has been modified (the question field replaced by the two options)?

^ There might be some leftovers if you modify data structure. Just ignore them.

@davidstillwell: 

> Hm, I did think the wiki was editable but apparently not. @przemyslawlis - can this be enabled?

^ Only authorised users can edit wiki. Unfortunately Github doesn't let do PR for wiki pages. Best way to submit changes to wiki for now is precisely as @tangi75  did - by making issue report with changes.
