### ISSUE TITLE
Bower Installation Failed

### ISSUE THREAD

**Issue by rcdp** [campsych/concerto-platform#60]
Hello,
I just tried to install the native concerto, but failed during bower installation.
log and snapshot attached.

![concertoinstallationfailed](https://cloud.githubusercontent.com/assets/20432305/20048388/c142f22e-a4ee-11e6-8679-158060673460.JPG)
[concertoinstallationlog.txt](https://github.com/campsych/concerto-platform/files/574612/concertoinstallationlog.txt)
http://concertoplatform.com/installers/concertolauncher/x64/node-v6.2.1-x64.msi.
13:33:52 - Node installed successfuly.
13:33:52 - Checking for Node installation...
13:33:54 - Node already installed.
13:33:54 - Installing bower...
13:36:09 - Bower installation failed!
13:49:38 - Checking if x86_2008 is installed...
13:49:38 - x86_2008 installation found.

**Comment by tangi75** [comment]
I recently had a similar issue on : 
`sudo -u www-data bash -c "cd /var/www/vhosts/concerto/src/Concerto/PanelBundle/Resources/public/angularjs && bower install"`
It was a depencies conflict with jquery. I solved it by forcing the install of the latest packages : 
`sudo -u www-data bash -c "cd /var/www/vhosts/concerto/src/Concerto/PanelBundle/Resources/public/angularjs && bower install -F"`

**Comment by przemyslawlis** [comment]
@tangi75: 
> I recently had a similar issue

This is something different. The issue you had is already solved in c1181176eba5a86e225662ce8a52b53f47746e83 .

@rcdp:
Is this something you can reproduce? Does it happen all the time when it tries to install bower?

**Comment by przemyslawlis** [comment]
No response - closing. Will be reopened when the response is given.
