### ISSUE TITLE
Configuration from local database to Amazon relational database

### ISSUE THREAD

**Issue by phpvrin** [campsych/concerto-platform#61]
Hi, I have done concerto setup in aws by following installation steps in from https://github.com/campsych/concerto-platform/wiki/Linux-installation. I found that database is setup locally and I require RDS in aws with concerto platform. 

For that I have change the configuration in parameters.yml as mentioned below to save all quiz data in RDS:
    database_host: host_name
    database_port: 3306
    database_name: DB_name
    database_user: user_name
    database_password: password
Still all data saved locally. Please provide you support on same.

**Comment by przemyslawlis** [comment]
You might need to clear your cache located in **/app/cache/prod** folder before the changes will take effect (just remove whole **/app/cache/prod** with it's content).

**Comment by phpvrin** [comment]
I have removed the cache still issue not solved

**Comment by przemyslawlis** [comment]
Please paste your full parameters.yml file. Remove any password line located there.

**Comment by phpvrin** [comment]
parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: databasename
    database_user: username
    database_password: XXXXXX
    database_path: null
    database_unix_socket: null
    test_database_name: ThisIsYourTestDatabaseName
    test_database_user: ThisIsYourTestDatabaseUserName
    test_database_password: ThisIsYourTestDatabaseUserPassword
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en_GB
    secret: ThisTokenIsNotSoSecretChangeIt

**Comment by przemyslawlis** [comment]
You're telling it to connect to a database located at localhost:

> database_host: localhost

Set a proper **database_host** value.

**Comment by phpvrin** [comment]
after removing cache from prod folder, concerto platform is not working.

**Comment by przemyslawlis** [comment]
Is there any error message?
When changing database you need to recreate table structure in new database. 
You can do that by doing step no. 8 and 9 at: https://github.com/campsych/concerto-platform/wiki/Linux-installation.

**Comment by phpvrin** [comment]
Please check with admin login with default credential : http://52.63.217.64/. I am unable to create a test. If I am using localhost database then its working fine. But facing issue with RDS database.

**Comment by przemyslawlis** [comment]
Please allow dev mode from any IP temporary. See https://github.com/campsych/concerto-platform/wiki/Reporting-Issues#running-concerto-platform-in-debug-mode on how to do it and let me know when it's done.

**Comment by phpvrin** [comment]
Sorry for the delay in reply. Please check the screenshot : https://nimbus.everhelper.me/client/notes/share/653902/tg3vxs48ez27kp7fqqqc and https://nimbus.everhelper.me/client/notes/share/653904/pf1md3zc7ad7pty9uuwv . There is no 500 error.
![concerto_error1](https://cloud.githubusercontent.com/assets/23330925/20471027/f4c370b6-afd3-11e6-830e-f3d3d5cf6980.png)
![concerto_error2](https://cloud.githubusercontent.com/assets/23330925/20471029/f52f2770-afd3-11e6-834f-8ce2d9b06a12.png)

**Comment by przemyslawlis** [comment]
> Please allow dev mode from any IP temporary. See https://github.com/campsych/concerto-platform/wiki/Reporting-Issues#running-concerto-platform-in-debug-mode on how to do it and let me know when it's done.

^ It seems like you haven't turn on access to dev mode from outside of localhost. You need to comment out two lines in **web/app_dev.php**. Check the link above for instructions on how to do it and please let me know when it's done so I can check it out.

**Comment by phpvrin** [comment]
Yesterday I have email you with all details. Please let me know if need more information.

**Comment by przemyslawlis** [comment]
Closing as we'll continue our talk on private channel.
