### ISSUE TITLE
Error Message With dbEscapeStrings

### ISSUE THREAD

**Issue by aboukhary** [campsych/concerto-platform#62]
I have recently migrated to Concerto v5 after several years with v4. 

I have a fresh installation of v5 and it seems that something some not well functioning with my installation. 

I am receiving the following message with R table query code. The same code was working perfectly on v4. 

Error in (function (classes, fdef, mtable) : unable to find an inherited method for function ‘dbEscapeStrings’ for signature ‘"NULL", "character"’

I am wondering if this is a coding error or an installation problem (something related to security or libraries or ...)

Update : I managed to extract the debugger messages:

concerto_test_directive.js:138 Loading required package: concerto5
Loading required package: session
Loading required package: rjson
[1] "LC_CTYPE=en_US.utf8;LC_NUMERIC=C;LC_TIME=en_US.utf8;LC_COLLATE=en_US.utf8;LC_MONETARY=en_US.utf8;LC_MESSAGES=C;LC_PAPER=C;LC_NAME=C;LC_ADDRESS=C;LC_TELEPHONE=C;LC_MEASUREMENT=C;LC_IDENTIFICATION=C"
Loading required package: RMySQL
Loading required package: DBI
Loading required package: methods
[1] "running test #38..."
[1] "updating session..."
[1] "responding to server..."
[1] "responded to server"
[1] "listening to server..."

placeholder.html:1 Error in event handler for runtime.onMessage: TypeError: Cannot read property 'getBoundingClientRect' of null
    at chrome-extension://cjabmdjcfcfdmffimndhafhblfmpjdpe/toolbar.js:1:21892
concerto_test_directive.js:187 [1] "listened to server"
<simpleError in (function (classes, fdef, mtable) {    methods <- .findInheritedMethods(classes, fdef, mtable)    if (length(methods) == 1L)         return(methods[[1L]])    else if (length(methods) == 0L) {        cnames <- paste0("\"", sapply(classes, as.character),             "\"", collapse = ", ")        stop(gettextf("unable to find an inherited method for function %s for signature %s",             sQuote(fdef@generic), sQuote(cnames)), domain = NA)    }    else stop("Internal error in finding inherited methods; didn't return a unique method",         domain = NA)})(list("NULL", "character"), structure(function (con, strings,     ...) {    standardGeneric("dbEscapeStrings")}, generic = structure("dbEscapeStrings", package = "RMySQL"), package = "RMySQL", group = list(), valueClass = character(0), signature = c("con", "strings"), default = `\001NULL\001`, skeleton = (function (con,     strings, ...) stop("invalid call in method dispatch to 'dbEscapeStrings' (no default method)",     domain = NA))(con, strings, ...), class = structure("nonstandardGenericFunction", package = "methods")),     <environment>): unable to find an inherited method for function ‘dbEscapeStrings’ for signature ‘"NULL", "character"’>
[1] "responding to server..."
[1] "responded to server"
[1] "updating session..."
Error in value[[3L]](cond) : Error executing test logic.
Calls: tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
In addition: Warning message:
Closing open result sets 
Execution halted

**Comment by przemyslawlis** [comment]
Can you please paste your R code so I can check out what might be the source of the problem?

**Comment by aboukhary** [comment]
concerto.table.query(sql=paste("INSERT INTO `concerto`.`sessions` SET 
`sessionID`='",dbEscapeStrings(concerto$db$connection,toString(concerto$session$id)),"',
`username`='",dbEscapeStrings(concerto$db$connection,toString(user_list$username)),"'
",sep=""),params=list())

session is a custom database, and user_list$username is a variable.

**Comment by przemyslawlis** [comment]
Are you sure that **user_list$username** is not NULL? Can you check that please?

**Comment by aboukhary** [comment]
Thank you. This was probably the case.

**Comment by AnandGanesh7** [comment]
Hello, I seem to have the same error 

> <simpleError in (function (classes, fdef, mtable) { methods <- .findInheritedMethods(classes, fdef, mtable) if (length(methods) == 1L) return(methods[[1L]]) else if (length(methods) == 0L) { cnames <- paste0(""", sapply(classes, as.character), """, collapse = ", ") stop(gettextf("unable to find an inherited method for function %s for signature %s", sQuote(fdef@generic), sQuote(cnames)), domain = NA) } else stop("Internal error in finding inherited methods; didn't return a unique method", domain = NA)})(list("NULL", "character"), structure(function (con, strings, ...) { standardGeneric("dbEscapeStrings")}, generic = structure("dbEscapeStrings", package = "RMySQL"), package = "RMySQL", group = list(), valueClass = character(0), signature = c("con", "strings"), default = \001NULL\001, skeleton = (function (con, strings, ...) stop("invalid call in method dispatch to 'dbEscapeStrings' (no default method)", domain = NA))(con, strings, ...), class = structure("nonstandardGenericFunction", package = "methods")), ): unable to find an inherited method for function ‘dbEscapeStrings’ for signature ‘"NULL", "character"’>

when I run a test. It worked fine on v4 but not on v5. I have the following code and after debugging I found out that concerto$db$connection is NULL! 
`## Intro page
person.info <- concerto.template.show(31)
print (person.info) # debugging - Check to see if person.info contains null values - (UPDATE:doesn't)
print (concerto$db$connection) # debugging - Checking to see if connection string is NULL (THIS IS NULL!!!!)
concerto.table.query(
  sql=paste("
INSERT
INTO `concerto`.`SF36_responses`
SET 
`person_id`='",dbEscapeStrings(concerto$db$connection,toString(person.info$assigned_id)),"'
,
`person_name`='",dbEscapeStrings(concerto$db$connection,toString(person.info$fullname)),"'
,
`age`='",dbEscapeStrings(concerto$db$connection,toString(person.info$age)),"'
,
`sex`='",dbEscapeStrings(concerto$db$connection,toString(person.info$sex)),"'
",sep=""),
)
print ("Successfully reached line 36 and inserted values into SF36_responses") # Never reaches this point`

Any idea why this is happening? I have setup the MySQL database according to the instructions in the wiki and I'm able to retrieve data in other places as well. @aboukhary and @przemyslawlis  have you faced a similar situation before? Unlike the case above, my form variables person.info$** are all not NULL (I verified).

**Comment by chandangs16** [comment]
Hello. Is there a way to ensure that **concerto$db$connection** is not **NULL**?? I've been facing the same issue. Could you suggest any methods to resolve the problem? Thank you.

**Comment by chandangs16** [comment]
Well we resolved the issue, and it turns out, there are a lot of changes in syntax from version 4 to version 5. dbEscapeStrings() is no longer used. Instead of using:
concerto.table.query(
 sql=paste("UPDATE `concerto`.`SF36_responses` SET `q", i, "_id`='", question.id, "'WHERE `person_id` = '",dbEscapeStrings(concerto$db$connection,toString(person.info$assigned_id)),"'",sep=""),params=list() ) 
we used:
concerto.table.query( sql="UPDATE `concerto`.`SF36_responses`  SET `q{{i}}_id`='{{question_id}}'
         WHERE `person_id` = '{{assigned_id}}'",
params=list( i=i, question_id=question.id,  assigned_id=person.info$assigned_id)
). 
Hope this helps.
