### ISSUE TITLE
installing bower. At 'Prefix the choice with ! to persist it to bower.json'. Answer: ......Invalid choice

### ISSUE THREAD

**Issue by psychometrixeu** [campsych/concerto-platform#63]

**Comment by przemyslawlis** [comment]
Can you please be more specific what the problem is?
A screenshot would be helpful too.

**Comment by psychometrixeu** [comment]
Hi there,

At the prompt: "Prefix the choice with ! to persist it to bower.json.  
Answer _"
None of the options progress the installation (Y, N, !Y, !N).

Terry

----- Message from przemyslawlis <notifications@github.com> ---------
    Date: Thu, 10 Nov 2016 05:17:13 -0800

**Comment by przemyslawlis** [comment]
Thanks.
This is issue is already taken care of in c1181176eba5a86e225662ce8a52b53f47746e83 .
It should be part of the **master** branch next few days.

**Comment by psychometrixeu** [comment]
Thanks but when you say 'taken care of' what does it mean; i only  
downloaded the programs today and what should i do now to complete the  
installation?

----- Message from przemyslawlis <notifications@github.com> ---------
    Date: Thu, 10 Nov 2016 05:58:12 -0800

**Comment by psychometrixeu** [comment]
I closed out that dialogue box and after some other installations it  
came up with message "Concerto platform installation failed" Recheck  
doesn't solve the problem. Please advise.

----- Message from przemyslawlis <notifications@github.com> ---------
    Date: Thu, 10 Nov 2016 05:58:12 -0800

**Comment by przemyslawlis** [comment]
This has already been fixed, but the fix is for now only available in **dev** branch. 
Concerto Launcher pulls the source from **master** branch.
Changes from dev branch should be merged with master branch in next few days. When it's merged you should be able to run it without problems.
