### ISSUE TITLE
Arithmetic Operations & Passing Variables

### ISSUE THREAD

**Issue by aboukhary** [campsych/concerto-platform#66]
I have created a test that measures trait1 and passes the variable to the info node; however, I would like to calculate a grade for the trait, for example if trait > 10 grade = A & if trait < 10 grade = B

Can you please show me an example on how to perform the operation using existing nodes and how both the original trait and calculated grade can both be passed to the final info node?

**Comment by tangi75** [comment]
Hello,
Look at the tutorial submitted in https://github.com/campsych/concerto-platform/issues/59

**Comment by przemyslawlis** [comment]
You might want to take a look at **Feedback** node. It should do precisely what you asked for.
