### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by drtyner** [campsych/concerto-platform#68]
We have installed Concerto on a Windows computer, offline.  We go through the prerun and all tests pass.  Clicking Run takes us to our web browser where we receive:

Not Found
The requested URL /concerto-platform/admin was not found on this server.
Apache/2.4.17 (Win64) PHP/5.6.16 Server at 127.0.0.1 Port 80

The error provided from the developer error tool in Chrome:
Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by przemyslawlis** [comment]
Did you already had WAMP installed prior to running Concerto Launcher for the first time?

**Comment by drtyner** [comment]
no

**Comment by przemyslawlis** [comment]
Can you please paste the contents of your:
* **[wamp install path]/apps** directory
* **[wamp install path]/bin/apache/apache2.4.17/conf/httpd.conf** file

**Comment by przemyslawlis** [comment]
No response - closing. Please respond and the issue report will be reopened.

**Comment by roseKQ** [comment]
Hello - I am having this issue - Before installing concerto I had wamp installed previously but have now uninstalled it in favour of wamp64(which was installed by the concerto launcher). 

The contents of my [wamp install path]/apps directory are : 

concerto-platform
phpmyadmin4.5.2
phpsysinfo3.2.3
sqlbuddy1.3.3

The contents of my [wamp install path]/bin/apache/apache2.4.17/conf/httpd.conf file is massive - should I cut and paste it here?!

Please help and thanks in advance!
