### ISSUE TITLE
installation stops at ggplot

### ISSUE THREAD

**Issue by ggdelucca** [campsych/concerto-platform#69]
11:11:02 - digest R package installed successfully.
11:11:02 - Installing ggplot2 R package...

at this point it seems to stop, meaning that after more than  20 minutes is still there.

Windows 10 64 bit.

**Comment by przemyslawlis** [comment]
This might take some time to finish. Can you please give it at least an hour and report if it got pass this step?

**Comment by ggdelucca** [comment]
it is working. Thanks
