### ISSUE TITLE
Question - secret and hash

### ISSUE THREAD

**Issue by xinxiang** [campsych/concerto-platform#73]
In parameters.yml, last line:
  `secret: ThisTokenIsNotSoSecretChangeIt`

Whose secret is this for?

In parameters_nodes.yml, last line:
  `hash: someRandomHash`

What is that hash for? How should I create a value for it?

Thank you.

**Comment by przemyslawlis** [comment]
> In parameters.yml, last line:
secret: ThisTokenIsNotSoSecretChangeIt
Whose secret is this for?

See http://symfony.com/doc/current/reference/configuration/framework.html#secret

> In parameters_nodes.yml, last line:
hash: someRandomHash
What is that hash for? How should I create a value for it?

Ignore it. It's for multi-instance Concerto Platform setup. It's experimental, undocumented and unsupported right now.
