### ISSUE TITLE
Save Data Bug

### ISSUE THREAD

**Issue by aboukhary** [campsych/concerto-platform#74]
When the test taker doesn't provide any responses, save data after the linear test generates an error, probably because the vector length is zero. 

How can this be resolved?

Below is the debugging error message:

[1] "running test #9..."
<simpleError in list2env(list(), NULL, <environment>): names(x) must be a character vector of the same length as x>
[1] "responding to server..."
[1] "responded to server"
[1] "updating session..."
Error in value[[3L]](cond) : Error executing test logic.
Calls: tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>

**Comment by aboukhary** [comment]
Bug resolved. 

I added the condition: if(length(new_data)>0) in line 20 of the save data node source code to prevent save node from generating an error when the test taker arbitrarily doesn't provide any responses.

**Comment by davidstillwell** [comment]
@przemyslawlis Can you add this to the code for this starter content node? Also with a printed warning so test creators can see what happened.

**Comment by przemyslawlis** [comment]
Latest **save_data** allows empty lists. 

> <simpleError in list2env(list(), NULL, ): names(x) must be a character vector of the same length as x>

^ This error seems more like a problem with the **new_data** type. It should be a **list** with key=value pairs for its elements.

In latest commit ( 2d80752d8eca0b4f6cf3549e96fd5a086b815d97 ), I've updated the **save_data** to validate the type of the **new_data** parameter at the beginning and print out appropriate message when the validation fails.
