### ISSUE TITLE
Linux Installation - Step 4: PHP dependencies - Deprecation Notice

### ISSUE THREAD

**Issue by xinxiang** [campsych/concerto-platform#75]
Warning in the result of `php -dmemory_limit=1G composer.phar install --prefer-source --no-interaction`. 

`Deprecation Notice: The callback Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::prepareDeploymentTarget declared at concerto-platform/vendor/sensio/distribution-bundle/Sensio/Bundle/DistributionBundle/Composer/ScriptHandler.php accepts a Composer\Script\CommandEvent but post-install-cmd events use a Composer\Script\Event instance. Please adjust your type hint accordingly, see https://getcomposer.org/doc/articles/scripts.md#event-classes in phar:///concerto-platform/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:290`

I wonder if this has anything to do with my failure at "Run Test".

**Comment by przemyslawlis** [comment]
This can be ignored.
It doesn't have anything to do with the failure at running the test.
