### ISSUE TITLE
Duplicate an assessment

### ISSUE THREAD

**Issue by reidma** [campsych/concerto-platform#76]
Once I have created an assessment, it seems it should be possible to duplicate the assessment and all its properties, rather than creating a new one from scratch (e.g. for weekly assignments in a course, differing only by content, not format). Is there a simple way to do this, short of exporting the assessment, editing the text file manually to change the name in several locations, and then re-uploading it?

**Comment by przemyslawlis** [comment]
There is a **Copy** button that you click on to copy the test and all of it's properties. See below:
![copy](https://cloud.githubusercontent.com/assets/6590627/21987511/2b4e8682-dc04-11e6-82ed-f1b6802610ff.png)
