### ISSUE TITLE
Where are the questions stored?

### ISSUE THREAD

**Issue by xinxiang** [campsych/concerto-platform#78]
I wonder where are the created questions stored? And in what format are they stored?  I looked through the concerto database, but I didn't find any there. I also looked the directories and didn't find them there either.

**Comment by przemyslawlis** [comment]
If you mean the item banks from starter content that you can fill by test wizards then they are stored in database. 
See TestNodePort (if they are declared on flow based test), or TestVariable (otherwise).
They are stored in JSON format.

**Comment by xinxiang** [comment]
Thank you. But I mean the questions that I created via the interface or CVS upload. Where are these question items stored?

**Comment by xinxiang** [comment]
Ah, yes, I found my question in TestNodePort. Thanks.
