### ISSUE TITLE
All Tests Are Not Visible After Export Import

### ISSUE THREAD

**Issue by aboukhary** [campsych/concerto-platform#79]
I have made an export import function that didn't work properly. Afterwards I no longer see any of the tests, despite having the admin account. 

All tests are still there, and the test links still work fine, but I can't see any of them. 

This behavior is very similar to the case where security settings are not configured properly. 

Is there any possibility the lost tests could be recovered?

The version used is v5.0.beta.2.160. 

![image](https://cloud.githubusercontent.com/assets/17113039/21496781/aac22ec2-cc29-11e6-90d9-bf0cfae24178.png)

**Comment by przemyslawlis** [comment]
Can you please check your browser console log?
Are there any errors there?

**Comment by aboukhary** [comment]
This is the error message: 
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
/admin/Test/collection?filters=%7B%7D&paging=%7B%22page%22:1,%22pageSize%22:500%7D

**Comment by przemyslawlis** [comment]
There must be something wrong with the installation.
Please run the same request in debug mode ( see: https://github.com/campsych/concerto-platform/wiki/Reporting-Issues#running-concerto-platform-in-debug-mode ) and paste content of response.

**Comment by aboukhary** [comment]
The installation was working perfectly until I made an import of an exported file of the same version. 

I accessed in debugging mode and here are the GET results. 

Failed to load resource: net::ERR_EMPTY_RESPONSE

![image](https://cloud.githubusercontent.com/assets/17113039/21607638/34aac798-d1c0-11e6-89b0-5b9dab48d493.png)

**Comment by Abuamany** [comment]
We have same problem and this issue appear at console
![screenshot from 2017-01-07 21-00-41](https://cloud.githubusercontent.com/assets/16170999/21742225/b5a77cd8-d51c-11e6-96e9-fa1c8421be88.png)

**Comment by Abuamany** [comment]
![screenshot from 2017-01-07 21-28-19](https://cloud.githubusercontent.com/assets/16170999/21742393/8ee4b6c0-d520-11e6-97a2-ec702f4896c6.png)

**Comment by przemyslawlis** [comment]
Please paste full response body of any 500 errors while in dev mode (see: https://github.com/campsych/concerto-platform/wiki/Reporting-Issues#how-to-check-for-server-side-errors-in-chrome).
Otherwise I can't identify the source of the issue.

**Comment by przemyslawlis** [comment]
No response - closing. Feel free to give response and the issue will be reopened.
