### ISSUE TITLE
Unable to add elements to test flowchart

### ISSUE THREAD

**Issue by foolswood** [campsych/concerto-platform#8]
I'm running the AMI (set up as per the guide) v5.0.beta.2.109 .
When I try to add elements to the test flow I get a 500 in response to the AJAX post request (made to http://[ip]/admin/Test/[testno]/node/add).
Thus no nodes can be added, therefore no questions.
I wonder if I might be able to get around this by using the code test type, are there any examples for this?

**Comment by przemyslawlis** [comment]
Can you please check the logs and see what is the error message on 500 response?

**Comment by foolswood** [comment]
I've got errors about being unable to open the log:

[Tue Apr 05 17:41:24.791407 2016] [:error] [pid 26247] [client 176.115.245.137:31551] PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'The stream or file "/var/www/html/concerto-platform/app/logs/prod.log" could not be opened: failed to open stream: Permission denied' in /var/www/html/concerto-platform/app/cache/prod/classes.php:5945\nStack trace:\n#0 /var/www/html/concerto-platform/app/cache/prod/classes.php(5883): Monolog\\Handler\\StreamHandler->write(Array)\n#1 /var/www/html/concerto-platform/app/cache/prod/classes.php(6054): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)\n#2 /var/www/html/concerto-platform/app/cache/prod/classes.php(6363): Monolog\\Handler\\FingersCrossedHandler->handle(Array)\n#3 /var/www/html/concerto-platform/app/cache/prod/classes.php(6470): Monolog\\Logger->addRecord(500, 'Uncaught PHP Ex...', Array)\n#4 /var/www/html/concerto-platform/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/ExceptionListener.php(89): Monolog\\Logger->critical('Uncaught PHP Ex...', Array)\n#5 /var/www/html/concerto-platform/vendor/symfony/symfony/src/Symfony/Comp in /var/www/html/concerto-platform/app/cache/prod/classes.php on line 5945
ubuntu@ip-172-31-37-206:~$ less /var/log/apache2/error.log 
ubuntu@ip-172-31-37-206:~$ grep error /var/log/apache2/error.log 
[Tue Apr 05 17:33:30.719174 2016] [:error] [pid 25888] [client 176.115.245.137:31508] PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Unable to create the cache directory (/var/www/html/concerto-platform/app/cache/prod)\n' in /var/www/html/concerto-platform/app/bootstrap.php.cache:2682\nStack trace:\n#0 /var/www/html/concerto-platform/app/bootstrap.php.cache(2643): Symfony\\Component\\HttpKernel\\Kernel->buildContainer()\n#1 /var/www/html/concerto-platform/app/bootstrap.php.cache(2422): Symfony\\Component\\HttpKernel\\Kernel->initializeContainer()\n#2 /var/www/html/concerto-platform/app/bootstrap.php.cache(2453): Symfony\\Component\\HttpKernel\\Kernel->boot()\n#3 /var/www/html/concerto-platform/web/app.php(23): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#4 {main}\n  thrown in /var/www/html/concerto-platform/app/bootstrap.php.cache on line 2682
[Tue Apr 05 17:41:24.781467 2016] [:error] [pid 26247] [client 176.115.245.137:31551] PHP Warning:  SessionHandler::read(): open(/var/www/html/concerto-platform/app/cache/prod/sessions/sess_gn5i0jp1oupm5q0ur22tbep9t0, O_RDWR) failed: Permission denied (13) in /var/www/html/concerto-platform/app/cache/prod/classes.php on line 417
[Tue Apr 05 17:41:24.791407 2016] [:error] [pid 26247] [client 176.115.245.137:31551] PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'The stream or file "/var/www/html/concerto-platform/app/logs/prod.log" could not be opened: failed to open stream: Permission denied' in /var/www/html/concerto-platform/app/cache/prod/classes.php:5945\nStack trace:\n#0 /var/www/html/concerto-platform/app/cache/prod/classes.php(5883): Monolog\\Handler\\StreamHandler->write(Array)\n#1 /var/www/html/concerto-platform/app/cache/prod/classes.php(6054): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)\n#2 /var/www/html/concerto-platform/app/cache/prod/classes.php(6363): Monolog\\Handler\\FingersCrossedHandler->handle(Array)\n#3 /var/www/html/concerto-platform/app/cache/prod/classes.php(6470): Monolog\\Logger->addRecord(500, 'Uncaught PHP Ex...', Array)\n#4 /var/www/html/concerto-platform/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/ExceptionListener.php(89): Monolog\\Logger->critical('Uncaught PHP Ex...', Array)\n#5 /var/www/html/concerto-platform/vendor/symfony/symfony/src/Symfony/Comp in /var/www/html/concerto-platform/app/cache/prod/classes.php on line 5945
[Tue Apr 05 17:41:24.795609 2016] [:error] [pid 26247] [client 176.115.245.137:31551] PHP Warning:  SessionHandler::write(): open(/var/www/html/concerto-platform/app/cache/prod/sessions/sess_gn5i0jp1oupm5q0ur22tbep9t0, O_RDWR) failed: Permission denied (13) in /var/www/html/concerto-platform/app/cache/prod/classes.php on line 421

**Comment by foolswood** [comment]
My apologies, that error was non fatal and the log was opened:

[2016-06-29 14:14:02] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO TestNode (type, posX, posY, updated, created, tags, flowTest_id, sourceTest_id, updatedBy_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["0", null, null, "2016-06-29 14:14:02", "2016-06-29 14:14:02", "", 33, 12, null]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'posX' cannot be null" at /var/www/html/concerto-platform/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO TestNode (type, posX, posY, updated, created, tags, flowTest_id, sourceTest_id, updatedBy_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"0\", null, null, \"2016-06-29 14:14:02\", \"2016-06-29 14:14:02\", \"\", 33, 12, null]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'posX' cannot be null at /var/www/html/concerto-platform/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'posX' cannot be null at /var/www/html/concerto-platform/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'posX' cannot be null at /var/www/html/concerto-platform/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []

**Comment by foolswood** [comment]
Unfortunately clearing the cache didn't help.

**Comment by przemyslawlis** [comment]
How did you tried to add a new node? Did you tried to do it manually by creating POST request, or have you tried to do it by right clicking on the flowchart and selecting a new node to insert? 
What browser are you using?

**Comment by foolswood** [comment]
Trying to do it via the right click menu. Firefox.

**Comment by przemyslawlis** [comment]
Is it possible for me to get an access to your panel and see it reproduced? Can you send me an access details to przemek@concertoplatform.com?

**Comment by przemyslawlis** [comment]
Fixed in 2225b3ec0f71c4b29634b4a1bfdfc393821fd9e2 - closing.
