### ISSUE TITLE
Performance Problem with Questionnaire Node Direct Items

### ISSUE THREAD

**Issue by aboukhary** [campsych/concerto-platform#81]
Hello everyone, 

We are now using a new installation of v5.0.beta.2.171 and it seems that the questionnaire node performance deteriorates a lot when the node is loaded with any number of direct items. 

This problem was not observed in the questionnaire node when the items are retrieved from database.

**Comment by przemyslawlis** [comment]
Hi aboukary,
This is already fixed in latest **dev** branch.

**Comment by aboukhary** [comment]
There seems to be a CSV upload problem with v5.0.beta.2.171. 

When a CSV file is directly uploaded into the linear test node, the items are not saved. I wonder if this has to do with the same bug.
