### ISSUE TITLE
Concent Node Content Not Visible

### ISSUE THREAD

**Issue by aboukhary** [campsych/concerto-platform#84]
Version: v5.0.beta.2.171	

The consent object doesn't show text inside of it, and the demo text seems to be misplaced. 

![image](https://cloud.githubusercontent.com/assets/17113039/21604404/b52fe39a-d1ab-11e6-89d2-b4a272b3ebd8.png)

Any idea why objects get corrupted? Any advice to solve this problem?

**Comment by przemyslawlis** [comment]
Sorry but I don't quite understand what is the problem here. I don't see anything wrong with the screenshot. Can you please explain?

**Comment by przemyslawlis** [comment]
No response - closing. Feel free to give response and the issue will be reopened.
