### ISSUE TITLE
Item Bank Table Structure Direct vs Database

### ISSUE THREAD

**Issue by aboukhary** [campsych/concerto-platform#85]
I have noticed some differences between the item bank table structure in v5.0.beta.2.171 between the direct format, which embeds the correct answer inside the json object, and the item bank database structure, which holds the correct answer as a standalone column. 
This makes it difficult to manipulate large item pools, and I hope to see this change in the future.

**Comment by przemyslawlis** [comment]
Can you please post a screenshot of both?
There are no precreated item bank database tables. Maybe you're comparing direct table item bank to database table response bank?

**Comment by aboukhary** [comment]
The direct format screenshot 
![image](https://cloud.githubusercontent.com/assets/17113039/21607821/5c0adac0-d1c1-11e6-8c1a-f3711e205839.png)

Whereas the database item bank includes an additional field (Correct) as shown below

![image](https://cloud.githubusercontent.com/assets/17113039/21607845/8181a946-d1c1-11e6-92c9-4d7320269ab9.png)
