### ISSUE TITLE
Export & Import with Oriental Languages Such As Arabic & Hebrew

### ISSUE THREAD

**Issue by aboukhary** [campsych/concerto-platform#86]
We have been facing many difficulties with export and import, and we finally figured out why!

Apparently Arabic content and alphabet is converted into different characters; which seems to damage the original node structure. 

I am wondering if UTF is used to maintain content integrity or not.

<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">

**Comment by przemyslawlis** [comment]
Yes, UTF-8 is used for encoding.

Can you please tell what exactly did you try to import and where? Can you please post the problematic export file so I can check it out and see if I can reproduce it?

**Comment by przemyslawlis** [comment]
No response - closing. Feel free to give response and the issue will be reopened.
