### ISSUE TITLE
Inserting Variables in Info Node

### ISSUE THREAD

**Issue by aboukhary** [campsych/concerto-platform#87]
I have extracted a linear test results from default_data_table and posted the results into a new variable called results_var using R code node. 

Now I would like to pass this variable to the info page to display results, I am not sure how the inserts are managed in this case. Can you please elaborate on this?

Also I need to embed some HTML, CSS and JS code to display results visually, what is the most effective way to reach this objective?

**Comment by przemyslawlis** [comment]
You can pass any variables to your **info** page through **inserts** parameter. It accepts key-value pairs list type, so, for example, if you want to pass two variable **first_name** and **last_name** to your info page  **content** here, your **content** could be a string with following value:

<pre>Welcome {{first_name}} {{last_name}}! Nice to meet you!</pre>

... and your **inserts** param could have a value of:

<pre>list(first_name="me",last_name="myself")</pre>

You can insert any HTML, CSS, JS this way.
