### ISSUE TITLE
building concerto platfrom using dockerfile

### ISSUE THREAD

**Issue by hadyrashwan** [campsych/concerto-platform#89]
I'm trying to build concerto in docker 
https://gist.github.com/hadyrashwan/e7458bb148e9d384eb0adf4c1be134a3
but it failed with  this error 
                                                                                                                                                                                            
```sh

Generating autoload files

[RuntimeException]                                                                                                                                                                        
  Could not scan for classes inside "/var/www/vhosts/concerto/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Resources/stubs" which does not appear to be a file nor a folder  
                                                                                                                                                                                            

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...
```

I know that I put all those in one run in a shell script but due to downloading huge amount of dependencies 
I did that way for the time being then will refactor 

I tried this https://hub.docker.com/r/lelmarir/docker-concerto/ and got me the  same error

**Comment by przemyslawlis** [comment]
There will be an official docker image available very soon for Concerto Platform. I will comment in this issue report when it will be available.

**Comment by viztastic** [comment]
@przemyslawlis Thanks that's really exciting. Given that concerto relies on a database and other services, it would be great to see an example of a `docker-compose` file in addition to just the `Dockerfile` as well. Thanks!

**Comment by hadyrashwan** [comment]
I build this https://github.com/hadyrashwan/concerto-docker-build/ 
the db password is hardcoded ARG n ENV should be used instead also creating docker-compose from this point is way easier hope it helps

**Comment by fthamura** [comment]
azyeval::lazy_eval
lazyeval::make_call
lazyeval::missing_arg
Saved: 2188/2188 | 100%
R documentation cache generated.

                                                                             
  [Doctrine\DBAL\Exception\ConnectionException]                              
  An exception occured in driver: SQLSTATE[HY000] [2002] Connection refused  
                                                                             

                                             
  [Doctrine\DBAL\Driver\PDOException]        
  SQLSTATE[HY000] [2002] Connection refused  
                                             

                                             
  [PDOException]                             
  SQLSTATE[HY000] [2002] Connection refused  
                                             

concerto:content:import [--convert] [--] [<input>]

**Comment by fthamura** [comment]
i wait a docker in dockerhub , to run it :) heheh

**Comment by hadyrashwan** [comment]
I had similar problems with MySQL on  Azure A0 basic  Ubuntu 16.4 LTS machines by just upgrading to A1 standard it was solved. you could wait for the official  docker repo

**Comment by fthamura** [comment]
what is A1? @hadyrashwan , i install it in my notebook.

**Comment by hadyrashwan** [comment]
its a machine size on Microsoft Azure will give it another try  tomorrow . and try to trace your bug

**Comment by przemyslawlis** [comment]
See [docker-compose Install guide](https://github.com/campsych/concerto-platform/wiki/docker-compose-Installation-guide) for docker installation guide. Closing.
