### ISSUE TITLE
RTL Questionnaire Formatting

### ISSUE THREAD

**Issue by aboukhary** [campsych/concerto-platform#91]
For the questionnaire template to have the same format in both directions, the following must be added in the questionnaire content template:

.questionnaireQuestionCell{
border-left: 1px solid #d1d1d1;
}

**Comment by przemyslawlis** [comment]
Thanks for reporting this.
It's already fixed internally. I'll update this issue report when the commit will be pushed to public repository.

**Comment by przemyslawlis** [comment]
Fixed in 742e8277374b10f02454459cd60c67a01b394a9c. Closing.
