### ISSUE TITLE
Error encountered. Execution halted error

### ISSUE THREAD

**Issue by junaidia2005** [campsych/concerto-platform#92]
Hi,

I've installed Concerto v5 using the instructions given for AWS.
Once running the test, I've got the following error.

Error encountered. Execution halted error.

Have anybody get the same error? Any guide to solve it?

Thanks.

**Comment by przemyslawlis** [comment]
This is most probably your test logic error.
Please debug your test to check what is the source of the problem. 
See: https://github.com/campsych/concerto-platform/wiki/Bug-checking
