### ISSUE TITLE
Error encountered. Execution halted

### ISSUE THREAD

**Issue by junaidia2005** [campsych/concerto-platform#93]
Hi,

I'm from Malaysia and have installed Concerto v5 AMI using AWS by following the tutorial given (Concerto Platform AMI launch guide). When I run the test, I received the following message:

Error encountered. Execution halted.

When I run the debug test, I received the following message. 

[1] "LC_CTYPE=en_US.utf8;LC_NUMERIC=C;LC_TIME=en_US.utf8;LC_COLLATE=en_US.utf8;LC_MONETARY=en_US.utf8;LC_MESSAGES=C;LC_PAPER=C;LC_NAME=C;LC_ADDRESS=C;LC_TELEPHONE=C;LC_MEASUREMENT=C;LC_IDENTIFICATION=C"
Loading required package: concerto5
Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called âconcerto5â
Error in loadNamespace(name) : there is no package called âconcerto5â
Calls: ::: ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted

Any help would be much appreciated. 
Thank you in advance.

**Comment by przemyslawlis** [comment]
Please try to recreate the instance using the guide at: https://github.com/campsych/concerto-platform/wiki/Concerto-Platform-AMI-launch-guide .
I've changed the contents just now of what needs to be pasted into **Advenced Details** as the previous instructions could lead to some problems on latest version.

**Comment by junaidia2005** [comment]
It is working now..
Thank You przemyslawlis
