### ISSUE TITLE
CAT module crashes if no response options are specified (for open questions)

### ISSUE THREAD

**Issue by chvancooten** [campsych/concerto-platform#94]
The CAT module throws a fatal error if no response options are defined in Concerto 5 (v5.0.beta.2.186), since section_classes and section_styles fail to be defined.

Temporary workaround: Add the following lines to your source_CAT file (in tests):

```
section_classes = "";
section_styles = "";
```

**Comment by przemyslawlis** [comment]
Thank you for your report. This is fixed internally and should be soon pushed to public repository.

**Comment by davidstillwell** [comment]
Just to add clarification - the two above lines need to be added to beginning of the source_CAT node.
