### ISSUE TITLE
Concerto 5 unable to resume sessions

### ISSUE THREAD

**Issue by chvancooten** [campsych/concerto-platform#95]
If the start_session node is used with the "resume session" option checked, Concerto crashes when an existing user signs in (at any point in the test, which contains only an info node, CAT test and another info node in my case.

Debug returns the following:
`[1] "resuming session..." _hash_ 
[1] "restore flow session..." 
<simpleError in concerto.session.restoreFlow(hash): session file not found!> 
[1] "responding to server..."
[1] "responded to server"
[1] "updating session..."
Error in value[[3L]](cond) : Error executing test logic.
Calls: tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
In addition: Warning messages:
1: Closing open result sets 
2: Closing open result sets 
Execution halted
`

**Comment by chvancooten** [comment]
Another case with only linear tests (randomly served and with random content ordering, session node is highlighted):
![image](https://cloud.githubusercontent.com/assets/25614522/23557741/550b27e0-0031-11e7-9893-da40fa2ee3e0.png)

This setup crashes with the same error when "resume session" is enabled.

**Comment by przemyslawlis** [comment]
Unfortunately there is no documentation yet for it. 
You need to have a saved session state for **resume session** to work.
You could, for example, tell it to save session state before showing each template, by adding this code to R code node somewhere at the beginning of your test logic:

<pre>
#this function will be called right before showing each template
concerto.onBeforeTemplateShow <<- function(params) {
  #here we save our session state
  save.session(concerto$sessionFile)
}
</pre>

**Comment by chvancooten** [comment]
Thank you so much! Adding this to the module logic flawlessly fixed the issue.
