### ISSUE TITLE
What's the default login  credentials 

### ISSUE THREAD

**Issue by MrLeolong** [campsych/concerto-platform#96]
Hi, Sorry to ask the simple question. But right now I cannot login to the dashboard. What's the default login credentials? Thanks.

![default](https://cloud.githubusercontent.com/assets/25660577/22779249/f2bfae3c-eef4-11e6-8192-676a7353632c.png)

**Comment by przemyslawlis** [comment]
Defaults are:
login: **admin**
password: **admin**
See: https://github.com/campsych/concerto-platform/wiki/Linux-installation#launching-concerto-platform

**Comment by MrLeolong** [comment]
Thanks.
