### ISSUE TITLE
system not responding while uploading 200 items

### ISSUE THREAD

**Issue by MrLeolong** [campsych/concerto-platform#97]
system not responding while uploading 200 items

In fact, i was trying to upload 500 or more items. But it failed in a smaller amount.

**Comment by davidstillwell** [comment]
Can you give some details about what exactly you were doing? Was it uploading a csv file into an item table in the Tables tab? Or uploading images? If it's an item table, then in the worst case you can just upload 100 items per time and keep appending to the table.

**Comment by davidstillwell** [comment]
I'll close this since it has been a while. Feel free to re-open if necessary.
